import {COMICS,COMIC_LABELS,LESSON_COMICS,JAPAN_COMICS} from './MathComicData.mjs';
export {COMICS,LESSON_COMICS,JAPAN_COMICS};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=new URL('../../assets/comics/piko-math-scenes.png',import.meta.url).href;
export const comicButtonLabel=locale=>COMIC_LABELS.open[locale]||COMIC_LABELS.open.en;
function grid(cols,rows,filled=cols*rows,x=40,y=30,size=32){return Array.from({length:cols*rows},(_,i)=>`<rect x="${x+i%cols*size}" y="${y+Math.floor(i/cols)*size}" width="${size}" height="${size}" fill="${i<filled?'#8fd6c7':'#fffdf6'}" stroke="#245653" stroke-width="1.5"/>`).join('');}
export function diagram(type){
 let shapes='';
 if(['half','quarter','twoquarters'].includes(type)){const n=type==='half'?2:4,f=type==='quarter'?1:type==='half'?1:2;shapes=Array.from({length:n},(_,i)=>`<rect x="${40+i*240/n}" y="62" width="${240/n}" height="60" fill="${i<f?'#8fd6c7':'#fffdf6'}" stroke="#245653" stroke-width="1.5"/>`).join('')+`<text x="160" y="170">${f}/${n}</text>`;}
 else if(type==='numberline'){shapes='<path d="M35 110H285" stroke="#245653" stroke-width="3"/>';for(let i=0;i<5;i++)shapes+=`<path d="M${35+i*62.5} 100v20" stroke="#245653" stroke-width="2"/><text x="${35+i*62.5}" y="146">${['0','1/4','1/2','3/4','1'][i]}</text>`;shapes+='<circle cx="160" cy="110" r="7" fill="#bd4e35"/>';}
 else if(['perimeter','perimeterTry','area','areaTry','unit'].includes(type)){const cols=type==='unit'?1:type.endsWith('Try')?3:4,rows=type==='unit'?1:2,s=45,x=(320-cols*s)/2,y=60;shapes=type.startsWith('area')||type==='unit'?grid(cols,rows,cols*rows,x,y,s):`<rect x="${x}" y="${y}" width="${cols*s}" height="${rows*s}" fill="#fffdf6" stroke="#bd4e35" stroke-width="5"/>`;shapes+=`<text x="160" y="42">${cols} m</text><text x="${x+cols*s+27}" y="${y+rows*s/2+6}">${rows} m</text>`;if(type.startsWith('perimeter'))shapes+=`<text x="160" y="${y+rows*s+27}">${cols} m</text><text x="${x-27}" y="${y+rows*s/2+6}">${rows} m</text>`;}
 else if(type.startsWith('layers')){const count=Number(type.slice(-1));for(let i=0;i<count;i++)shapes+=grid(3,2,6,112,10+i*75,28);}
 else if(type.startsWith('percent'))shapes=grid(10,10,Number(type.replace('percent','')),60,12,20);
 else if(type.startsWith('ratio')){const mult=type==='ratioDouble'?2:1;shapes=grid(2*mult,1,2*mult,32,45,28)+grid(3*mult,1,0,32,110,28)+`<text x="250" y="65">${2*mult}</text><text x="250" y="130">${3*mult}</text><text x="160" y="190">${2*mult} : ${3*mult}</text>`;}
 return `<svg viewBox="0 0 320 240" aria-hidden="true" focusable="false" style="font:16px system-ui;text-anchor:middle;fill:#193e3b">${shapes}</svg>`;
}
let active=null;
export function openMathComic(id,initialLocale='en'){
 const comic=COMICS[id];if(!comic)return false;if(active)active();
 let locale=['zh','ja','en'].includes(initialLocale)?initialLocale:'en',index=0,selected=null;
 const opener=document.activeElement,host=document.createElement('div'),shadow=host.attachShadow({mode:'open'});document.body.append(host);
 const dialog=document.createElement('dialog');dialog.setAttribute('aria-labelledby','comic-title');shadow.append(dialog);
 const style=document.createElement('style');style.textContent=`:host{font:18px/1.65 system-ui,sans-serif;color:#193e3b}*{box-sizing:border-box}dialog{border:2px solid #245653;border-radius:22px;padding:0;width:min(760px,calc(100vw - 24px));max-height:90dvh;color:#193e3b;background:#fffaf0;box-shadow:0 20px 90px #0006}dialog::backdrop{background:#102b35bb}header,footer{padding:16px 22px;background:#f4ecd9}header{display:flex;gap:12px;justify-content:space-between;align-items:center;flex-wrap:wrap}h1{font-size:23px;margin:0}h2{font-size:22px;margin:0 0 12px}button,select{font:inherit;min-height:56px;padding:10px 16px;border:2px solid #245653;border-radius:12px;background:white;color:#193e3b;cursor:pointer}button:hover{background:#e1f4ed}button:focus-visible,select:focus-visible{outline:4px solid #b85330;outline-offset:3px}button:disabled{opacity:.45;cursor:default}main{padding:22px}.scene{width:100%;aspect-ratio:2/1;border-radius:14px;background-image:url('${asset}');background-size:200% 400%;background-repeat:no-repeat;background-position-x:var(--x);background-position-y:var(--y);margin-bottom:18px}.lesson{display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:20px}.diagram{background:#fff;border:1px solid #b8cfc7;border-radius:14px}.diagram svg{width:100%;display:block}p{margin:10px 0}footer{display:flex;gap:10px;align-items:center;justify-content:space-between;flex-wrap:wrap}.choices{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.choices [aria-pressed=true]{background:#d1ebdf;border-width:3px}.feedback{min-height:2em;font-weight:600}.count{font-size:15px;letter-spacing:2px}@media(max-width:540px){header,footer,main{padding:14px}.lesson{grid-template-columns:1fr;gap:12px}h1{font-size:20px}.scene{aspect-ratio:1.65/1}button,select{font-size:16px}dialog{max-height:94dvh}}`;shadow.prepend(style);
 function close(){dialog.close();host.remove();if(active===close)active=null;window.removeEventListener('pagehide',close);if(opener?.isConnected)opener.focus();}
 function render(focus=false){const p=comic.panels[index],t=k=>COMIC_LABELS[k][locale];dialog.lang=locale;dialog.innerHTML=`<header><h1 id="comic-title">${esc(comic.title[locale])}</h1><select aria-label="中文 / 日本語 / English">${[['zh','中文'],['ja','日本語'],['en','English']].map(([v,label])=>`<option value="${v}" ${v===locale?'selected':''}>${label}</option>`).join('')}</select></header><main><p class="count">${index+1} / ${comic.panels.length} · PIKO</p>${index===0?`<div class="scene" aria-hidden="true" style="--x:${comic.scene%2?100:0}%;--y:${comic.scene<2?16:84}%"></div>`:''}<div class="lesson"><div><h2 tabindex="-1">${esc(p.title[locale])}</h2><p>${esc(p.text[locale])}</p></div><div class="diagram">${diagram(p.diagram)}</div></div>${index===comic.panels.length-1?`<div class="choices" role="group" aria-label="${esc(t('check'))}">${comic.choices.map((c,i)=>`<button data-choice="${i}" aria-pressed="${selected===i}">${esc(c)}</button>`).join('')}</div><p class="feedback" role="status">${selected===null?'':esc(t(selected===comic.answer?'yes':'no'))}</p>`:''}</main><footer><button data-action="prev" ${index===0?'disabled':''}>${esc(t('prev'))}</button><button data-action="close">${esc(t('close'))}</button><button data-action="next" ${index===comic.panels.length-1?'disabled':''}>${esc(t('next'))}</button></footer>`;if(focus){dialog.querySelector('h2').focus();dialog.scrollTop=0;}}
 dialog.addEventListener('change',e=>{if(e.target.tagName==='SELECT'){locale=e.target.value;render();dialog.querySelector('select').focus();}});
 dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const action=b.dataset.action;if(action==='close'){close();return;}if(action==='next'||action==='prev'){index+=action==='next'?1:-1;selected=null;render(true);}else if(b.dataset.choice!==undefined){selected=Number(b.dataset.choice);render();dialog.querySelector(`[data-choice="${selected}"]`).focus();}});
 dialog.addEventListener('cancel',e=>{e.preventDefault();close();});window.addEventListener('pagehide',close,{once:true});active=close;render();dialog.showModal();return true;
}
