import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {mkdir} from 'node:fs/promises';
import {startTownPreview} from '../scripts/preview-town.mjs';
const preview=await startTownPreview(0),browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});await mkdir('.wrangler/town-loading',{recursive:true});
try{for(const width of [390,820]){
 const page=await browser.newPage({viewport:{width,height:900},hasTouch:true,isMobile:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.loadSteps=[];window.encodes=0;const encode=HTMLCanvasElement.prototype.toDataURL;HTMLCanvasElement.prototype.toDataURL=function(...a){encodes++;return encode.apply(this,a);};new MutationObserver(()=>{const v=document.querySelector('[data-town-loading]')?.dataset.progress;if(v!==undefined&&loadSteps.at(-1)!==Number(v))loadSteps.push(Number(v));}).observe(document,{subtree:true,attributes:true,childList:true});});
 await page.route('**/src/town/TownScene3D.mjs*',async route=>{await new Promise(r=>setTimeout(r,350));await route.continue();});await page.goto(preview.origin+'/town.html?locale=zh',{waitUntil:'domcontentloaded'});await page.locator('[data-town-loading]:visible').waitFor();await page.screenshot({path:`.wrangler/town-loading/loading-${width}.png`});await page.locator('[data-town-loading]').waitFor({state:'hidden',timeout:60000});await page.locator('[data-game-preload][data-ready=true]').waitFor({state:'attached',timeout:60000});const steps=await page.evaluate(()=>loadSteps);assert.equal(steps.at(-1),100);assert.ok(steps.length>=6);assert.ok(steps.every((v,i)=>i===0||v>=steps[i-1]));
 await page.locator('[data-action=begin]').click();const consent=page.locator('[data-consent=necessary]');if(await consent.isVisible())await consent.click();await page.evaluate(async()=>{const {startArcade}=await import('/src/arcade/ArcadeHub.mjs');const before=encodes,t=performance.now();window.session=startArcade('bubble',{locale:'zh'});window.openMetrics={ms:performance.now()-t,generatedThumbnails:encodes-before};});assert.equal(await page.evaluate(()=>openMetrics.generatedThumbnails),0);assert.equal(await page.locator('[data-floating-panel=projects]').isVisible(),true);await page.locator('[data-town-exit]').click();await page.waitForFunction(()=>!document.querySelector('.arcade-shell'));assert.deepEqual(errors,[]);console.log(`Town loading ${width}: real monotonic progress, all game modules and gallery preloaded; warmed designer ${JSON.stringify(await page.evaluate(()=>openMetrics))}`);await page.close();
}
 const page=await browser.newPage({viewport:{width:390,height:900}});await page.route('**/src/town/TownScene3D.mjs*',r=>r.abort());await page.goto(preview.origin+'/town.html?locale=zh');await page.locator('[data-town-loading][data-error=true]').waitFor();assert.equal(await page.locator('[data-town-loading] button').isVisible(),true);await page.close();console.log('Town loading failure: visible retry instead of a permanently blank town');
}finally{await browser.close();await preview.close();}
