import assert from 'node:assert/strict';
import { goHarness } from './go-harness.mjs';
import { lessonState } from '../src/arena/GoLearn.mjs';
import { group, play } from '../src/arena/GoRules.mjs';
const {mf,db}=await goHarness();const origin='http://localhost:4173';let checks=0;
const check=(value,msg)=>{assert.ok(value,msg);checks++;};
try {
  async function api(cookie,path,body={}) {
    const r=await mf.dispatchFetch(`${origin}/api/arena/${path}`,{method:body===null?'GET':'POST',headers:{origin,cookie:cookie||'','content-type':'application/json','cf-connecting-ip':crypto.randomUUID()},body:body===null?undefined:JSON.stringify(body)});
    return {status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0],data:await r.json()};
  }
  const cookies=[];for(let i=0;i<4;i++)cookies.push((await api('','identity')).cookie);
  const [a,b,c,d]=cookies;
  check((await api(a,'profile',{name:'<script>',avatar:'🐼',visible:true})).data.error==='INVALID_NAME','invalid nickname rejected');
  check((await api(a,'profile',{name:'安全昵称',avatar:'🐼',visible:true,parentalGateAck:false})).data.visible===false,'public visibility requires parental ack');
  const profiles=[];for(const cookie of cookies)profiles.push((await api(cookie,'profile',{name:'同名伙伴',avatar:'🐼',visible:true,parentalGateAck:true})).data);
  check(new Set(profiles.map(p=>p.publicId)).size===4,'duplicate names have distinct ids');
  check((await api(a,'identity')).data.name==='同名伙伴','profile survives next request');
  await api(a,'tutorial',{step:4});await api(a,'tutorial',{step:2});check((await api(a,'identity')).data.tutorial===4,'tutorial progress never regresses');
  const ta=crypto.randomUUID(),tb=crypto.randomUUID();
  await api(a,'presence',{tab:ta,status:'idle',parentalGateAck:true});await api(a,'presence',{tab:crypto.randomUUID(),status:'playing',parentalGateAck:true});
  let list=(await api(b,'presence',{tab:tb,status:'idle',parentalGateAck:true})).data;
  check(list.players.length===2&&list.players.find(p=>p.key===profiles[0].publicId).status==='playing','tabs deduplicated and active game takes priority');
  check(!JSON.stringify(list).includes('g:')&&!JSON.stringify(list).includes('actor_id'),'directory hides private ids');
  await api(a,'profile',{name:'爸爸',avatar:'🐻',visible:false,parentalGateAck:false});
  list=(await api(a,'presence',{tab:ta,status:'idle',parentalGateAck:true})).data;
  check(!list.players.some(p=>p.key===profiles[0].publicId),'privacy choice removes all sessions');
  await api(a,'profile',{name:'爸爸',avatar:'🐻',visible:true,parentalGateAck:true});await api(a,'presence',{tab:ta,status:'idle',parentalGateAck:true});
  list=(await api(a,'invitation',{type:'invite',target:profiles[1].publicId})).data;
  const invite=list.invites[0];check(invite&&!invite.family,'pending invitation has no family access link');
  check((await api(c,'invitation',{type:'accept',invite:invite.id})).data.error==='INVITE_EXPIRED','third party cannot accept invitation');
  list=(await api(b,'invitation',{type:'accept',invite:invite.id})).data;const invitedFamily=list.invites[0].family;
  check((await api(a,`families/${invitedFamily}`,{type:'get'})).data.members.length===2,'accepted invitation creates shared private room');
  let family=(await api(a,'families',{tab:ta})).data;
  const path=`families/${family.id}`;
  check((await api(c,path,{type:'get'})).data.error==='NOT_MEMBER','room members cannot be read without joining');
  family=(await api(b,path,{type:'join',tab:tb})).data;
  family=(await api(c,path,{type:'join',tab:crypto.randomUUID()})).data;
  check(family.members.length===3&&family.seats.length===2,'family supports more members than game seats');
  check(!JSON.stringify(family).includes('g:')&&!JSON.stringify(family).includes('userId'),'family view hides identities');
  check((await api(b,path,{type:'settings',revision:family.revision,gameType:'go',size:9,rules:'chinese',seats:family.seats})).data.error==='HOST_ONLY','only host selects players');
  family=(await api(a,path,{type:'settings',revision:family.revision,gameType:'go',size:19,rules:'japanese',seats:family.seats})).data;
  check((await api(a,path,{type:'ready',revision:family.revision-1})).data.error==='FAMILY_STALE','stale family mutation rejected');
  family=(await api(a,path,{type:'ready',revision:family.revision})).data;
  family=(await api(b,path,{type:'ready',revision:family.revision})).data;
  const starts=await Promise.all([api(a,path,{type:'start',revision:family.revision}),api(a,path,{type:'start',revision:family.revision})]);
  family=(await api(a,path,{type:'get'})).data;
  check(family.game&&starts.some(r=>r.data.game===family.game),'concurrent start creates one game');
  let game=(await api(a,`rooms/${family.game}`,null)).data;
  check(game.phase==='playing'&&game.game.size===19&&game.game.rules==='japanese'&&game.family===family.id,'family launch preserves rules and starts after readiness');
  check((await api(c,`rooms/${game.id}`,null)).data.error==='NOT_PLAYER','nonparticipants cannot access board');
  game=(await api(a,`rooms/${game.id}`,{type:'resign',revision:game.revision})).data;
  const old=game.id;
  game=(await api(a,`rooms/${old}`,{type:'rematch'})).data;
  check(game.rematchVotes.length===1&&!game.nextRoom,'one player cannot force rematch');
  game=(await api(a,`rooms/${old}`,{type:'rematch',accept:false})).data;check(!game.rematchVotes.length,'rematch can be cancelled');
  check((await api(d,`rooms/${old}`,{type:'rematch'})).data.error==='NOT_PLAYER','rematch requires original participant');
  await api(a,`rooms/${old}`,{type:'rematch'});
  const replies=await Promise.all([api(b,`rooms/${old}`,{type:'rematch'}),api(b,`rooms/${old}`,{type:'rematch'})]);
  check(replies[0].data.nextRoom===replies[1].data.nextRoom&&replies[0].data.nextRoom,'rematch idempotent under concurrent acceptance');
  const next=replies[0].data.nextRoom;
  game=(await api(a,`rooms/${next}`,null)).data;
  check(game.seat===2&&game.phase==='playing'&&game.game.moves.length===0&&game.remaining[0]===900000,'rematch swaps colors and resets board and clock');
  check((await api(a,path,{type:'get'})).data.game===next,'family follows next game');
  check(!!await db.prepare('SELECT room_id FROM go_games WHERE room_id=?').bind(old).first(),'old game archived before new game');
  game=(await api(a,`rooms/${next}`,{type:'resign',revision:game.revision})).data;
  await api(a,`rooms/${next}`,{type:'rematch'});await api(b,`rooms/${next}`,{type:'rematch'});
  check((await db.prepare('SELECT COUNT(*) AS n FROM go_games WHERE room_id IN (?,?)').bind(old,next).first()).n===2,'consecutive games keep separate histories');
  const space=await mf.unsafeGetDurableObjectStorage('go-backend','PlayroomSpace',{name:`family:${family.id}`});
  check(!!space,'family state persisted in SQLite');
  await mf.unsafeEvictDurableObject('go-backend','PlayroomSpace',{name:`family:${family.id}`});
  check((await api(a,path,{type:'get'})).data.members.length===3,'family survives instance eviction');
  const directoryStorage=await mf.unsafeGetDurableObjectStorage('go-backend','PlayroomSpace',{name:'public:v1'});
  await directoryStorage.exec(`UPDATE state SET json=json_set(json, '$.people."${profiles[1].publicId}".tabs."${tb}".at',0)`);
  list=(await api(c,'presence',{tab:crypto.randomUUID(),status:'idle'})).data;
  check(!list.players.some(p=>p.key===profiles[1].publicId),'expired online lease disappears');
  const f=(await api(a,path,{type:'get'})).data;
  check((await api(a,path,{type:'settings',revision:f.revision,gameType:'go',size:9,rules:'chinese',seats:[profiles[0].publicId,profiles[0].publicId]})).data.error==='INVALID_SETTINGS','cannot occupy both seats');
  check((await api(c,path,{type:'leave',revision:0})).data.ok,'leaving does not require a fresh room revision');
  const liberties=group(lessonState(1).board,20).liberties;check(liberties.length===4,'tutorial teaches actual liberties');
  const capture=play(lessonState(2),29);check(capture.board[20]===0&&capture.captures[0]===1,'tutorial capture uses production rules');
  check(play(play(lessonState(4),null),null).phase==='scoring','tutorial ending uses two passes');
  console.log(`Playroom: ${checks} checks passed.`);
} finally {await mf.dispose();}
