import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {mkdir} from 'node:fs/promises';
import {startRacePreview} from '../scripts/preview-race.mjs';
const preview=await startRacePreview(),browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});await mkdir('.wrangler/designer-engineering',{recursive:true});
try{for(const width of [1440,390]){
 const context=await browser.newContext({viewport:{width,height:844},isMobile:width<500,hasTouch:width<500}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(preview.origin);
 await page.evaluate(async()=>{game.destroy();shell.destroy();const {openArcadeShell}=await import('/src/arcade/ArcadeShell.mjs'),{createBubbleGame}=await import('/src/arcade/BubbleGame.mjs');window.exitCount=0;window.shell=openArcadeShell({gameId:'bubble',locale:'zh',onExit(){exitCount++;game.destroy();shell.destroy();},onRetry(){}});window.game=createBubbleGame({canvas:shell.canvas,locale:'zh',onHud:s=>shell.setHud(s)});window.watermarks=[];const fill=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,...args){if(text==='piko-game.com')watermarks.push({w:this.canvas.width,h:this.canvas.height});return fill.call(this,text,...args);};});
 const open=async id=>{if(!await page.locator(`[data-floating-panel=${id}]`).isVisible())await page.locator(`[data-panel=${id}]`).click();};const close=()=>page.locator('[data-floating-panel]:visible [data-close-panel]').click();
 for(const kit of ['airliner','jet','sport','suv','truck','pro','ring','rocket','robot','yacht','house']){
  await page.evaluate(id=>game.selectProject(id),kit);await open('projects');await page.locator('[data-demo]').click();await close();await page.locator('[data-view]').click();
  for(const side of ['front','back','left','right','top']){await page.locator(`[data-camera=${side}]`).click();await page.screenshot({path:`.wrangler/designer-engineering/${kit}-${side}-${width}.png`});}await page.locator('[data-return-2d]').click();await open('projects');await page.locator('[data-demo]').click();await close();
 }
 await page.evaluate(()=>game.selectProject('sport'));await open('details');for(const n of ['3','4','6','8','12']){await page.locator('[data-engine-count]').selectOption(n);await page.locator('[data-add-engine]').click();}assert.ok(await page.evaluate(()=>game.getState().parts.length>400));await close();await page.locator('[data-view]').click();await page.locator('[data-camera=reset]').click();await page.screenshot({path:`.wrangler/designer-engineering/engines-${width}.png`});assert.ok(await page.evaluate(()=>game.getState().preview3d.parts>390));await page.locator('[data-return-2d]').click();
 await page.evaluate(()=>game.selectProject('pro'));await open('tools');await page.locator('[data-tool=brush]').click();await page.mouse.move(width*.3,550);await page.mouse.down();await page.mouse.move(width*.7,630,{steps:12});await page.mouse.up();await open('tools');await page.locator('[data-make-drawing]:visible').click();assert.equal(await page.evaluate(()=>game.getState().parts.at(-1).kind),'drawing');assert.equal(await page.evaluate(()=>game.getState().strokes),0);await open('transform');await page.locator('[data-duplicate]').click();await page.locator('[data-depth=".15"]').click();await page.locator('[data-mirror]').click();await page.locator('[data-tilt="15"]').click();await page.locator('[data-turn="-15"]').click();assert.equal(await page.evaluate(()=>game.getState().parts.at(-1).tilt),15);assert.equal(await page.evaluate(()=>game.getState().parts.at(-1).turn),-15);assert.equal(await page.evaluate(()=>game.getState().parts.at(-1).depthPosition),.15);assert.equal(await page.evaluate(()=>game.getState().parts.at(-1).symmetric),false);await close();
 await open('tools');await page.locator('[data-tool=move]').click();const pos=await page.evaluate(async()=>{const {designTransform}=await import('/src/arcade/DesignerRender.mjs'),{DESIGN_KITS}=await import('/src/arcade/DesignerCatalog.mjs');const state=game.getState(),p=state.parts.at(-1),t=designTransform(innerWidth,innerHeight,DESIGN_KITS[state.kitId]);return {x:t.x+p.x*t.scale,y:t.y+p.y*t.scale};});await page.mouse.move(pos.x,pos.y);await page.mouse.down();await page.mouse.move(width-35,814,{steps:15});await page.mouse.up();assert.ok(await page.evaluate(()=>game.getState().parts.at(-1).y>530),'drawn part moves beyond phone reference bounds');
 await page.locator('[data-view]').click();await open('save');const d3=page.waitForEvent('download');await page.locator('[data-export-3d]').click();await (await d3).saveAs(`.wrangler/designer-engineering/3d-${width}.png`);await page.locator('[data-screenshot]').click();const shot=page.waitForEvent('download');await page.locator('[data-capture-save]').click();await (await shot).saveAs(`.wrangler/designer-engineering/screen-${width}.png`);await page.locator('[data-capture-close]').click();const art=page.waitForEvent('download');await page.locator('[data-download]').click();await (await art).saveAs(`.wrangler/designer-engineering/art-${width}.png`);assert.equal(await page.evaluate(()=>watermarks.length),3);await close();
 await page.locator('[data-focus]').click();assert.equal(await page.locator('[data-town-exit]').isVisible(),true);await page.locator('[data-town-exit]').click();assert.equal(await page.evaluate(()=>exitCount),1);assert.equal(await page.locator('.arcade-shell').count(),0);assert.deepEqual(errors,[]);await context.close();console.log(`Engineering browser ${width}: 11 kits × 5 directions, all cylinder assemblies, custom drawing/free drag/duplicate/depth/symmetry, three watermarked PNG exports and direct exit passed`);
}}finally{await browser.close();await preview.close();}
