import assert from 'node:assert/strict';import {chromium} from 'playwright-core';import {mkdir,readFile} from 'node:fs/promises';import {DESIGN_KITS} from '../src/arcade/DesignerCatalog.mjs';import {startRacePreview} from '../scripts/preview-race.mjs';
const preview=await startRacePreview(),browser=await chromium.launch({channel:'chrome',headless:true});await mkdir('.wrangler/designer-polish',{recursive:true});
try{for(const width of [1440,390]){const context=await browser.newContext({viewport:{width,height:844},hasTouch:width<500,isMobile:width<500}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/arcade/leaderboard*',r=>r.fulfill({json:{entries:[{rank:1,name:'Player-test',score:520}]}}));await page.goto(preview.origin);await page.evaluate(async()=>{game.destroy();shell.destroy();const {openArcadeShell}=await import('/src/arcade/ArcadeShell.mjs');const {createBubbleGame}=await import('/src/arcade/BubbleGame.mjs');window.shell=openArcadeShell({gameId:'bubble',locale:'zh',onExit(){},onRetry(){}});window.game=createBubbleGame({canvas:shell.canvas,locale:'zh',onHud:s=>shell.setHud(s),onEnd:r=>shell.showResult(r)});shell.root.addEventListener('click',e=>{if(e.target.closest('[data-shell="pause"],[data-shell="board"]'))queueMicrotask(()=>shell.paused?game.pause():game.resume());});});
 const point=async p=>page.evaluate(async p=>{const {designTransform}=await import('/src/arcade/DesignerRender.mjs');const {DESIGN_KITS}=await import('/src/arcade/DesignerCatalog.mjs');const r=document.querySelector('.designer-canvas').getBoundingClientRect(),t=designTransform(r.width,r.height,DESIGN_KITS[game.getState().kitId]);return {x:r.x+t.x+p.x*t.scale,y:r.y+t.y+p.y*t.scale};},p);
 for(const [id,kit]of Object.entries(DESIGN_KITS)){
  await page.evaluate(id=>game.selectProject(id),id);await page.locator('[data-demo]').click();assert.equal(await page.locator('[data-finish]').isDisabled(),true);await page.screenshot({path:`.wrangler/designer-polish/${id}-preview-${width}.png`});await page.locator('[data-demo]').click();await page.locator('[data-finish]').click();assert.equal(await page.evaluate(()=>game.getState().ended),false);
  const first=kit.parts[0],target=await point(first),library=await page.locator(`[data-part="${first.id}"]`).boundingBox();await page.mouse.move(library.x+library.width/2,library.y+library.height/2);await page.mouse.down();await page.mouse.move(target.x,target.y,{steps:12});await page.mouse.up();assert.equal(await page.evaluate(id=>game.getState().parts.find(p=>p.id===id).placed,first.id),true,JSON.stringify({id,width,target,library,canvas:await page.locator('.designer-canvas').boundingBox(),part:await page.evaluate(id=>game.getState().parts.find(p=>p.id===id),first.id)}));
  for(const p of kit.parts.slice(1))await page.locator(`[data-part="${p.id}"]`).click();assert.equal(await page.evaluate(()=>game.getState().parts.filter(p=>p.placed).length),kit.parts.length);
  await page.locator('[data-rotate="15"]').click();const last=kit.parts.at(-1);assert.equal(await page.evaluate(id=>game.getState().parts.find(p=>p.id===id).rotation,last.id),15);await page.locator('[data-undo]').click();assert.equal(await page.evaluate(id=>game.getState().parts.find(p=>p.id===id).rotation,last.id),0);await page.locator('[data-redo]').click();assert.equal(await page.evaluate(id=>game.getState().parts.find(p=>p.id===id).rotation,last.id),15);await page.locator('[data-rotate="-15"]').click();
  await page.locator('[data-tool="brush"]').click();const a=await point({x:kit.bounds.x+40,y:kit.bounds.y+kit.bounds.h-25}),b=await point({x:kit.bounds.x+170,y:kit.bounds.y+kit.bounds.h-40});await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:10});await page.mouse.up();assert.ok(await page.evaluate(()=>game.getState().strokes>0));
  await page.screenshot({path:`.wrangler/designer-polish/${id}-assembled-${width}.png`});
  assert.equal(await page.evaluate(()=>{const root=document.querySelector('.designer-studio');return root.scrollWidth<=root.clientWidth+1;}),true,'studio must not overflow');
 }

 if(width<500){const cdp=await context.newCDPSession(page),row=page.locator('.designer-parts');await row.evaluate(el=>el.scrollLeft=0);const r=await row.boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width-35,y:r.y+30,id:1}]});for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x+r.width-35-i*25,y:r.y+30,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(200);assert.ok(await row.evaluate(el=>el.scrollLeft>0),'touch swipe must scroll parts');await row.evaluate(el=>el.scrollLeft=0);await page.waitForTimeout(100);await page.locator('[data-tool="move"]').click();const first=DESIGN_KITS.ring.parts[0],a=await page.locator('[data-part="'+first.id+'"] .designer-drag-handle').boundingBox(),b=await point({x:first.x+40,y:first.y});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x+a.width/2,y:a.y+a.height/2,id:2}]});for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a.x+a.width/2+(b.x-a.x-a.width/2)*i/12,y:a.y+a.height/2+(b.y-a.y-a.height/2)*i/12,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(Math.abs((await page.evaluate(()=>game.getState().parts[0].x))-(first.x+40))<12,'touch drag must move part '+JSON.stringify({a,b,x:await page.evaluate(()=>game.getState().parts[0].x)}));}
 const beforeFocus=await page.locator('.designer-board').boundingBox();await page.locator('[data-focus]').click();const focused=await page.locator('.designer-board').boundingBox();if(width<500)assert.ok(focused.height>beforeFocus.height+80);await page.screenshot({path:'.wrangler/designer-polish/focus-'+width+'.png'});
 await page.locator('[data-screenshot]').click();await page.locator('.designer-capture img').waitFor();const capture=await page.evaluate(()=>document.querySelector('.designer-capture img').src);assert.ok(capture.startsWith('data:image/png;base64,'));const png=Buffer.from(capture.split(',')[1],'base64');assert.ok(png.readUInt32BE(16)>=width);assert.ok(png.readUInt32BE(20)>400);const shotPromise=page.waitForEvent('download');await page.locator('[data-capture-save]').click();const shot=await shotPromise;assert.match(shot.suggestedFilename(),/screenshot\.png$/);await shot.saveAs(`.wrangler/designer-polish/workspace-capture-${width}.png`);await page.locator('[data-capture-close]').click();await page.locator('[data-focus]').click();
 const exportPromise=page.waitForEvent('download');await page.locator('[data-download]').click();const exported=await exportPromise;assert.match(exported.suggestedFilename(),/artwork\.png$/);await exported.saveAs(`.wrangler/designer-polish/artwork-${width}.png`);const art=await readFile(`.wrangler/designer-polish/artwork-${width}.png`);assert.equal(art.readUInt32BE(16),1800);assert.equal(art.readUInt32BE(20),1200);
 await page.locator('[data-shell="pause"]').click();assert.equal(await page.locator('.designer-studio').isVisible(),false);await page.locator('[data-shell="pause"]').click();assert.equal(await page.locator('.designer-studio').isVisible(),true);await page.locator('[data-finish]').click();await page.locator('[data-overlay][data-outcome="success"]').waitFor();await page.getByText('Player-test').waitFor();assert.ok(await page.evaluate(()=>game.getState().score<=600));await page.evaluate(()=>{game.destroy();shell.destroy();});assert.deepEqual(errors,[]);await context.close();console.log(`Designer browser ${width}: seven real assemblies, drag, transforms, drawing, undo/redo, PNG screenshot/export, pause and clear passed`);}}finally{await browser.close();await preview.close();}

