import './test_designer_browser.mjs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {mkdir} from 'node:fs/promises';
import {startRacePreview} from '../scripts/preview-race.mjs';
const preview=await startRacePreview(),browser=await chromium.launch({channel:'chrome',headless:true});await mkdir('.wrangler/creative',{recursive:true});
try{for(const width of [1440,390]){const page=await browser.newPage({viewport:{width,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/arcade/leaderboard*',r=>r.fulfill({json:{entries:[{rank:1,name:'Player-test',score:520}]}}));await page.goto(preview.origin);await page.evaluate(async()=>{game.destroy();shell.destroy();window.requestAnimationFrame=()=>0;const {openArcadeShell}=await import('/src/arcade/ArcadeShell.mjs');const {createBubbleGame}=await import('/src/arcade/BubbleGame.mjs');window.shell=openArcadeShell({gameId:'bubble',locale:'zh',onExit(){},onRetry(){}});window.game=createBubbleGame({canvas:shell.canvas,locale:'zh',onHud:s=>shell.setHud(s),onEnd:r=>shell.showResult(r)});});
 await page.evaluate(()=>{game.destroy();shell.destroy();});
 await page.evaluate(async()=>{const {openArcadeShell}=await import('/src/arcade/ArcadeShell.mjs');const {createRhythmGame}=await import('/src/arcade/RhythmGame.mjs');window.shell=openArcadeShell({gameId:'rhythm',locale:'zh',onExit(){},onRetry(){}});window.game=createRhythmGame({canvas:shell.canvas,locale:'zh',onHud:s=>shell.setHud(s),onEnd:r=>shell.showResult(r)});});await page.locator('[data-music-start]').click();await page.evaluate(()=>{for(let i=0;i<70;i++)game.tick(.02);game.draw();});await page.screenshot({path:`.wrangler/creative/rhythm-${width}.png`});for(let n=0;n<48;n++){const lane=await page.evaluate(()=>{const n=game.getState().notes.find(n=>!n.done);while(game.getState().clock<n.at-.01)game.tick(.005);game.draw();return n.lane;});await page.locator(`[data-kids-pad="${lane}"]`).click();}assert.equal(await page.evaluate(()=>game.getState().hits),48);await page.locator('[data-overlay][data-outcome="success"]').waitFor();await page.evaluate(()=>game.destroy());assert.deepEqual(errors,[]);await page.close();console.log('Creative browser desktop/mobile passed',width);}}finally{await browser.close();await preview.close();}
