import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {mkdir,readFile} from 'node:fs/promises';
import {DESIGN_KITS} from '../src/arcade/DesignerCatalog.mjs';
import {startRacePreview} from '../scripts/preview-race.mjs';
const preview=await startRacePreview(),browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});await mkdir('.wrangler/designer-immersive',{recursive:true});
try{for(const width of (process.env.DESIGN_WIDTH?[Number(process.env.DESIGN_WIDTH)]:[1440,390])){
 const context=await browser.newContext({viewport:{width,height:844},hasTouch:width<500,isMobile:width<500}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/arcade/leaderboard*',r=>r.fulfill({json:{entries:[{rank:1,name:'Player-test',score:520}]}}));await page.goto(preview.origin);
 await page.evaluate(async()=>{game.destroy();shell.destroy();const {openArcadeShell}=await import('/src/arcade/ArcadeShell.mjs');const {createBubbleGame}=await import('/src/arcade/BubbleGame.mjs');window.shell=openArcadeShell({gameId:'bubble',locale:'zh',onExit(){},onRetry(){}});window.game=createBubbleGame({canvas:shell.canvas,locale:'zh',onHud:s=>shell.setHud(s),onEnd:r=>shell.showResult(r)});shell.root.addEventListener('click',e=>{if(e.target.closest('[data-shell="pause"],[data-shell="board"]'))queueMicrotask(()=>shell.paused?game.pause():game.resume());});});
 const open=async id=>{const panel=page.locator(`[data-floating-panel="${id}"]`);if(!await panel.isVisible())await page.locator(`[data-panel="${id}"]`).click();return panel;};
 const close=async()=>{const p=page.locator('[data-floating-panel]:visible');if(await p.count())await p.locator('[data-close-panel]').click();};
 const point=async p=>page.evaluate(async p=>{const {designTransform}=await import('/src/arcade/DesignerRender.mjs');const {DESIGN_KITS}=await import('/src/arcade/DesignerCatalog.mjs');const r=document.querySelector('.designer-canvas').getBoundingClientRect(),t=designTransform(r.width,r.height,DESIGN_KITS[game.getState().kitId]);return {x:r.x+t.x+p.x*t.scale,y:r.y+t.y+p.y*t.scale};},p);
 const board=await page.locator('.designer-board').boundingBox();assert.equal(board.width,width);assert.equal(board.height,844);assert.equal(await page.locator('[data-floating-panel]:visible').count(),0);
 await open('projects');assert.equal(await page.locator('[data-project]').count(),7);for(const category of ['rocket','robot','boat','building']){await page.locator(`[data-project="${category}"]`).click();assert.equal(await page.evaluate(()=>game.getState().project),category);}await close();
 for(const [id,kit]of Object.entries(DESIGN_KITS)){
  await page.evaluate(id=>{game.setView('2d');game.selectProject(id);},id);
  await open('projects');await page.locator('[data-demo]').click();await close();await page.screenshot({path:`.wrangler/designer-immersive/${id}-example-${width}.png`});await open('projects');await page.locator('[data-demo]').click();await close();
  await open('parts');for(const p of kit.parts)await page.locator(`[data-part="${p.id}"]`).click();await close();assert.equal(await page.evaluate(()=>game.getState().parts.filter(p=>p.placed).length),kit.parts.length);
  await open('transform');await page.locator('[data-rotate="15"]').click();await close();await open('tools');await page.locator('[data-undo]').click();assert.equal(await page.evaluate(()=>game.getState().parts.at(-1).rotation),0);await page.locator('[data-redo]').click();await close();
  await open('transform');await page.locator('[data-rotate="-15"]').click();await close();await open('tools');await page.locator('[data-tool="brush"]').click();
  const a=await point({x:kit.bounds.x+kit.bounds.w*.4,y:kit.bounds.y+kit.bounds.h*.8}),b=await point({x:kit.bounds.x+kit.bounds.w*.6,y:kit.bounds.y+kit.bounds.h*.8});await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();assert.ok(await page.evaluate(()=>game.getState().strokes>0));
  await page.locator('[data-view]').click();assert.equal(await page.evaluate(()=>game.getState().view),'3d');assert.ok(await page.evaluate(()=>game.getState().preview3d.meshes>10));
  await page.screenshot({path:`.wrangler/designer-immersive/${id}-3d-${width}.png`});const before=await page.evaluate(()=>game.getState().preview3d);await page.mouse.move(width*.48,350);await page.mouse.down();await page.mouse.move(width*.72,420,{steps:12});await page.mouse.up();const rotated=await page.evaluate(()=>game.getState().preview3d);assert.ok(Math.abs(rotated.yaw-before.yaw)>.1);await page.locator('[data-camera="back"]').click();assert.ok(Math.abs((await page.evaluate(()=>game.getState().preview3d.yaw))-Math.PI)<.01);await page.locator('[data-camera="top"]').click();assert.ok(await page.evaluate(()=>game.getState().preview3d.pitch>1));await page.locator('[data-camera="reset"]').click();await page.locator('[data-return-2d]').click();assert.equal(await page.evaluate(()=>game.getState().parts.filter(p=>p.placed).length),kit.parts.length);
 }
 await page.evaluate(()=>game.selectProject('rocket'));await open('tools');await page.locator('[data-tool="move"]').click();await open('parts');const core=DESIGN_KITS.rocket.parts[0],handle=await page.locator('[data-part="core"] .designer-drag-handle').boundingBox(),drop=await point({x:core.tx+60,y:core.ty});
 if(width<500){const cdp=await context.newCDPSession(page),scroll=page.locator('[data-floating-panel="parts"] .designer-panel-content'),r=await scroll.boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+30,y:r.y+r.height-40,id:3}]});for(let i=1;i<=6;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x+30,y:r.y+r.height-40-i*30,id:3}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(700);assert.ok(await scroll.evaluate(e=>e.scrollTop>0));await scroll.evaluate(e=>e.scrollTop=0);await page.waitForTimeout(100);const a=await page.locator('[data-part="core"] .designer-drag-handle').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x+22,y:a.y+22,id:4}]});for(let i=1;i<=10;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a.x+22+(drop.x-a.x-22)*i/10,y:a.y+22+(drop.y-a.y-22)*i/10,id:4}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 else{await page.mouse.move(handle.x+22,handle.y+22);await page.mouse.down();await page.mouse.move(drop.x,drop.y,{steps:12});await page.mouse.up();}
 assert.ok(Math.abs((await page.evaluate(()=>game.getState().parts[0].x))-(core.tx+60))<10,'part drag respects canvas coordinates '+JSON.stringify({width,handle,drop,state:await page.evaluate(()=>game.getState().parts[0])}));await close();
 const panel=await open('tools');await panel.locator('[data-panel-anchor="tr"]').click();const anchored=await panel.boundingBox();assert.ok(Math.abs(anchored.x+anchored.width-width+12)<2);const grip=await panel.locator('[data-panel-grip]').boundingBox();await page.mouse.move(grip.x+30,grip.y+20);await page.mouse.down();await page.mouse.move(grip.x+10,grip.y+55,{steps:5});await page.mouse.up();assert.ok((await panel.boundingBox()).y>anchored.y+20);await close();assert.equal((await page.locator('.designer-board').boundingBox()).width,width);
 await page.locator('[data-focus]').click();assert.equal(await page.locator('.designer-dock').isVisible(),false);await page.locator('[data-focus]').click();assert.equal(await page.locator('.designer-dock').isVisible(),true);await page.locator('[data-view]').click();
 if(width<500){const cdp=await context.newCDPSession(page),before=await page.evaluate(()=>game.getState().preview3d);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:160,y:350,id:1},{x:230,y:350,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:140,y:350,id:1},{x:250,y:350,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok((await page.evaluate(()=>game.getState().preview3d.zoom))>before.zoom);}
 await open('save');const d3=page.waitForEvent('download');await page.locator('[data-export-3d]').click();assert.match((await d3).suggestedFilename(),/-3d\.png$/);await page.locator('[data-screenshot]').click();await page.locator('.designer-capture img').waitFor();assert.ok(await page.locator('.designer-capture img').evaluate(e=>e.src.startsWith('data:image/png;base64,')));const shot=page.waitForEvent('download');await page.locator('[data-capture-save]').click();await (await shot).saveAs(`.wrangler/designer-immersive/studio-${width}.png`);await page.locator('[data-capture-close]').click();
 const artwork=page.waitForEvent('download');await page.locator('[data-download]').click();await (await artwork).saveAs(`.wrangler/designer-immersive/artwork-${width}.png`);const png=await readFile(`.wrangler/designer-immersive/artwork-${width}.png`);assert.equal(png.readUInt32BE(16),1800);assert.equal(png.readUInt32BE(20),1200);await close();
 await open('session');await page.locator('[data-shell="pause"]').click();assert.equal(await page.locator('.designer-studio').isVisible(),false);await page.locator('[data-shell="pause"]').click();assert.equal(await page.locator('.designer-studio').isVisible(),true);await close();await open('save');await page.locator('[data-finish]').click();await page.locator('[data-overlay][data-outcome="success"]').waitFor();await page.getByText('Player-test').waitFor();assert.ok(await page.evaluate(()=>game.getState().score<=600));await page.evaluate(()=>{game.destroy();shell.destroy();});assert.deepEqual(errors,[]);await context.close();console.log(`Designer ${width}: full-viewport canvas, seven categories, eleven editable assemblies, real 3D rotation, pinch, exports, pause and rewards passed`);
}}finally{await browser.close();await preview.close();}
