import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {mkdir} from 'node:fs/promises';
import {startRacePreview} from '../scripts/preview-race.mjs';
const preview=await startRacePreview(),browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});await mkdir('.wrangler/designer-achievement',{recursive:true});
try{for(const width of [1440,390]){
 const page=await browser.newPage({viewport:{width,height:844},hasTouch:width<500,isMobile:width<500}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(preview.origin);await page.evaluate(()=>{game.destroy();shell.destroy();});
 for(const id of ['sport','airliner','yacht','rocket','robot','house','pro','engine-4']){
  await page.evaluate(async id=>{const {openArcadeShell}=await import('/src/arcade/ArcadeShell.mjs'),{createBubbleGame}=await import('/src/arcade/BubbleGame.mjs');window.shell=openArcadeShell({gameId:'bubble',locale:'zh'});window.ends=0;window.game=createBubbleGame({canvas:shell.canvas,locale:'zh',onEnd:r=>{ends++;shell.showResult(r);}});game.selectProject(id);},id);
  assert.equal(await page.locator('[data-floating-panel=projects]').isVisible(),true);await page.locator('[data-close-panel]:visible').click();
  if(id==='engine-4'){await page.locator('[data-panel=projects]').click();await page.locator('[data-assemble-all]').click();await page.locator('[data-close-panel]:visible').click();assert.equal(await page.evaluate(()=>game.getState().parts.every(p=>p.placed)),true);}else await page.evaluate(()=>{for(const p of game.getState().parts)game.placePart(p.id);});
  await page.locator('[data-panel=tools]').click();await page.locator('[data-color="#e65843"]').click();await page.locator('[data-close-panel]:visible').click();await page.locator('[data-panel=save]').click();await page.locator('[data-finish]').click();assert.equal(await page.evaluate(()=>game.getState().ended),true,id+' completed');await page.locator('.designer-celebration-bar:visible').waitFor();assert.equal(await page.evaluate(()=>ends),1);assert.equal(await page.locator('[data-overlay]').isVisible(),false);await page.waitForTimeout(450);const first=await page.evaluate(()=>document.querySelector('.designer-3d-canvas').toDataURL());await page.waitForTimeout(450);assert.notEqual(await page.evaluate(()=>document.querySelector('.designer-3d-canvas').toDataURL()),first,id+' animated pixels');await page.screenshot({path:`.wrangler/designer-achievement/${id}-${width}.png`});await page.locator('[data-town-exit]').isVisible();
  if(id!=='sport')await page.locator('[data-celebration-done]').click();await page.locator('[data-overlay][data-outcome=success]').waitFor({timeout:12000});assert.equal(await page.evaluate(()=>ends),1);await page.evaluate(()=>{game.destroy();shell.destroy();});
 }
 await page.evaluate(async()=>{const {openArcadeShell}=await import('/src/arcade/ArcadeShell.mjs'),{createBubbleGame}=await import('/src/arcade/BubbleGame.mjs');window.shell=openArcadeShell({gameId:'bubble',locale:'zh',onExit(){game.destroy();shell.destroy();}});window.game=createBubbleGame({canvas:shell.canvas,locale:'zh',onEnd:r=>shell.showResult(r)});for(const p of game.getState().parts)game.placePart(p.id);game.transformPart('rotate',15);game.finish();});await page.locator('[data-town-exit]').click();await page.waitForTimeout(100);assert.equal(await page.locator('.arcade-shell').count(),0);assert.deepEqual(errors,[]);await page.close();console.log(`Achievement ${width}: eight work categories animate original colored parts, default menu, independent engine assembly, auto completion/skip, one reward and exit cleanup passed`);
}}finally{await browser.close();await preview.close();}
