import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHmac} from 'node:crypto';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
const secret='local-ranking-test',bundle=await build({entryPoints:['worker/index.js'],bundle:true,write:false,format:'esm',platform:'browser'}),mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2025-04-01',d1Databases:['DB'],bindings:{JWT_SECRET:secret,APP_ORIGIN:'http://localhost'},port:0}));
try{const db=await mf.getD1Database('DB');for(const file of ['0001_d1_data_platform.sql','0016_arcade_rankings.sql'])for(const sql of (await readFile('migrations/'+file,'utf8')).split(/;(?=(?:[^']*'[^']*')*[^']*$)/).map(s=>s.trim()).filter(Boolean))await db.prepare(sql).run();const tokens={};for(const u of ['a','b']){const now=Date.now();await db.prepare('INSERT INTO users(user_id,display_name,email,primary_provider,created_at,updated_at,last_login_at) VALUES(?1,?2,?3,?4,?5,?5,?5)').bind(u,'PRIVATE',u+'@private.test','google',now).run();await db.prepare('INSERT INTO auth_sessions(jti,user_id,provider,created_at,expires_at) VALUES(?1,?2,?3,?4,?5)').bind(u,u,'google',now,now+3600000).run();const h=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),b=Buffer.from(JSON.stringify({sub:u,jti:u,exp:Math.floor(now/1000)+3600})).toString('base64url');tokens[u]=`${h}.${b}.${createHmac('sha256',secret).update(`${h}.${b}`).digest('base64url')}`;}
async function api(path,body,u,origin){const r=await mf.dispatchFetch('http://localhost/api/arcade/'+path,{method:body?'POST':'GET',headers:{...(body?{'content-type':'application/json'}:{}),...(u?{authorization:'Bearer '+tokens[u]}:{}),...(origin?{origin}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,...await r.json()};}
assert.equal((await api('start',{game:'rhythm',level:1})).status,401);assert.equal((await api('start',{game:'rhythm',level:1},'a','https://bad.test')).status,403);assert.equal((await api('start',{game:'bad',level:1},'a')).status,400);
for(const [u,score]of [['a',100],['a',500],['b',500]]){const run=await api('start',{game:'rhythm',level:1},u);assert.equal(run.status,200);assert.equal((await api('finish',{id:run.id,score},u)).status,400);await db.prepare('UPDATE arcade_runs SET started_at=?1 WHERE run_id=?2').bind(Date.now()-2000,run.id).run();assert.equal((await api('finish',{id:run.id,score},u==='a'?'b':'a')).status,404);assert.equal((await api('finish',{id:run.id,score},u)).status,200);assert.equal((await api('finish',{id:run.id,score},u)).status,409);}
const board=await api('leaderboard?game=rhythm&level=1');assert.equal(board.entries.length,2);assert.deepEqual(board.entries.map(r=>[r.rank,r.score]),[[1,500],[1,500]]);assert.ok(!JSON.stringify(board).includes('PRIVATE')&&!JSON.stringify(board).includes('@'));assert.equal((await api('leaderboard?game=rhythm&level=2')).entries.length,0);assert.equal((await api('leaderboard?game=bubble&level=1')).entries.length,0);console.log('D1 ranking: account best, ties, isolation, privacy, auth, origin, replay and duration checks passed');}finally{await mf.dispose();}
