import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {chromium} from 'playwright-core';
import {startTownPreview} from '../scripts/preview-town.mjs';
import {questionFor,MODES} from '../src/town/ArcadeRules.mjs';
const preview=await startTownPreview(0,{built:process.env.TOWN_TEST_BUILT==='1'});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
const artifacts='.wrangler/town-3d-tests';await mkdir(artifacts,{recursive:true});const errors=[];let checks=0;
const mark=s=>console.log(`ok ${++checks} - ${s}`),save=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('piko-town-v1')));
async function open(page){page.on('pageerror',e=>errors.push(e.message));await page.goto(`${preview.origin}/town.html?locale=zh`);await page.locator('[data-action="begin"]').click();const consent=page.locator('[data-consent="necessary"]');try{await consent.waitFor({timeout:4000});await consent.click();}catch{}await page.locator('#town-canvas[data-renderer="webgl-3d"]').waitFor();}
async function solve(page,mode){let run=(await save(page)).expansion.runs[mode];while(!run.solved){const q=questionFor(run);const answer=page.locator(`[data-answer-platform="${q.answer}"]`);await answer.waitFor();await page.waitForFunction(i=>!document.querySelector(`[data-answer-platform="${i}"]`)?.disabled,q.answer);await answer.click();const beforeIndex=run.memoryIndex;await page.waitForFunction(({mode,beforeIndex})=>{const r=JSON.parse(localStorage.getItem('piko-town-v1')).expansion.runs[mode];return r.solved||r.memoryIndex!==beforeIndex;},{mode,beforeIndex},{timeout:25000});run=(await save(page)).expansion.runs[mode];}}
try{
 const context=await browser.newContext({viewport:{width:1440,height:1050}}),page=await context.newPage();page.setDefaultTimeout(15000);await open(page);await page.waitForTimeout(900);await page.screenshot({path:`${artifacts}/town-3d-desktop.png`,fullPage:true});
 assert.equal(await page.locator('.graphics-error').count(),0);assert.equal(await page.locator('[data-game]').count(),5);mark('real WebGL town loads with five island entrances');
 const before=(await save(page)).player;await page.locator('#town-canvas').focus();await page.keyboard.down('ArrowRight');await page.waitForTimeout(350);await page.keyboard.up('ArrowRight');await page.waitForTimeout(250);assert.ok((await save(page)).player.x>before.x);await page.locator('[data-camera="left"]').click();await page.locator('[data-camera="jump"]').click();mark('3D movement, orbit and jump controls accept input');
 await page.locator('#character').click();await page.locator('[data-character-id="robot"]').click();assert.equal((await save(page)).expansion.character,'robot');await page.screenshot({path:`${artifacts}/character-studio.png`});await page.locator('.close-button').click();await page.reload();await page.locator('#town-canvas[data-renderer]').waitFor();assert.equal((await save(page)).expansion.character,'robot');mark('six 3D avatars, live preview, selection and reload');
 for(const mode of MODES){await page.locator(`[data-game="${mode}"]`).click();await page.locator(`#town-canvas[data-mode="${mode}"]`).waitFor();await page.screenshot({path:`${artifacts}/${mode}-stage.png`,fullPage:true});await solve(page,mode);assert.equal((await save(page)).expansion.runs[mode].solved,true);const coins=(await save(page)).coins;await page.locator('[data-next-stage]').click();assert.equal((await save(page)).expansion.runs[mode].stage,2);assert.equal((await save(page)).coins,coins);await page.locator('[data-exit-game]').last().click();mark(`${mode}: physical travel to correct platforms clears stage and generates the next`);}
 await page.locator('[data-arcade-shop]').click();const coins=(await save(page)).coins;await page.locator('[data-buy-item="backpack"]').click();assert.equal((await save(page)).coins,coins-12);await page.locator('[data-equip-item="backpack"]').click();assert.equal((await save(page)).expansion.accessory,'backpack');await page.screenshot({path:`${artifacts}/adventure-shop.png`});await page.locator('.close-button').click();mark('earned coins buy an accessory and equip it on the 3D character');
 await page.locator('[data-game="obby"]').click();assert.equal((await save(page)).expansion.runs.obby.stage,2);await page.reload();await page.locator('[data-game="obby"]').click();assert.equal((await save(page)).expansion.runs.obby.stage,2);await page.locator('[data-exit-game]').last().click();mark('island progress survives leaving and reloading');
 for(const lang of ['en','ja','zh']){await page.locator('#locale').selectOption(lang);assert.equal(await page.locator('[data-game]').count(),5);assert.equal(await page.locator('html').getAttribute('lang'),lang);}mark('town, islands, and controls switch among three languages');
 const phone=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1}),mp=await phone.newPage();await open(mp);for(const width of [320,390,820]){await mp.setViewportSize({width,height:844});assert.ok(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mp.screenshot({path:`${artifacts}/town-${width}.png`,fullPage:true});}await mp.setViewportSize({width:390,height:844});await mp.locator('[data-game="runner"]').tap();assert.ok(await mp.locator('.arcade-panel').isVisible());await mp.screenshot({path:`${artifacts}/phone-runner.png`,fullPage:true});mark('320, 390 and 820 layouts and touch game entry');
 await phone.setOffline(true);await solve(mp,'runner');await phone.setOffline(false);mark('loaded 3D game and local engine keep working offline');
 assert.deepEqual(errors,[]);mark('no unhandled JavaScript exceptions');console.log(`Town 3D browser: ${checks} groups passed. ${artifacts}`);
}catch(error){for(const c of browser.contexts())for(const p of c.pages()){console.log('failure state',await save(p),await p.locator('#town-canvas').getAttribute('data-position'));await p.screenshot({path:`${artifacts}/failure.png`,fullPage:true});}throw error;}finally{await browser.close();await preview.close();}
