// UI strings for the AMC hub page (amc.html): level switch, tabs, real-style
// sets, the 25-question mock and the registration view.
export const HUB_TEXT={
 zh:{title:'AMC 数学竞赛',eyebrow:'PIKO GAME · MATH EXPLORER',language:'语言',eikenLink:'英检',footerBack:'返回首页',
  intro:'AMC 是美国数学协会（MAA）举办的系列数学竞赛：AMC 8、AMC 10 和 AMC 12。选择级别，再选“练习”“学习”或“报名指南”。',
  levelLabel:'选择级别',levels:{8:'8 年级及以下 · 40 分钟',10:'10 年级及以下 · 75 分钟',12:'12 年级及以下 · 75 分钟'},
  tabs:{practice:'练习',learn:'学习',register:'报名指南'},
  realTitle:'真题风格练习',realIntro:'每道题都是本站原创，按真实 AMC 题目的题型、结构和难度编写：A–E 五个选项，难度由易到难。每题注明仿照的真题，并链接到 AoPS Wiki 原题页面。',
  realCount:n=>`${n} 道题`,realStart:'开始一组（最多 10 题）',best:'最高成绩',
  mockTitle:'25 题模拟测验',mockIntro:{8:'从题库中按难度抽取 25 题，限时 40 分钟。按 AMC 8 规则计分：答对 1 分，不扣分。',10:'从题库中按难度抽取 25 题，限时 75 分钟。按 AMC 10 规则计分：答对 6 分、留空 1.5 分、答错 0 分。',12:'从题库中按难度抽取 25 题，限时 75 分钟。按 AMC 12 规则计分：答对 6 分、留空 1.5 分、答错 0 分。'},mockStart:'开始模拟',
  drillsTitle:'基础练习（填写、排序、选择）',drillsIntro:'刚开始学 AMC 8？先从这 600 道小学基础原创练习开始。',
  pastTitle:'历年真题（外部链接）',pastIntro:'在 AoPS Wiki 上查看历年英文原题与解答。',pastCredit:'真题版权归 MAA 所有；本站只提供链接。',
  bankNote:'本站题目均为原创，仅仿照真题的题型与难度；真题文字版权归 MAA 所有。',
  modeled:'原创题',viewOriginal:'查看原题（AoPS）↗',bands:{1:'基础',2:'进阶',3:'挑战'},
  question:'第',questionSuffix:'题',of:'/',exit:'← 退出',blank:'留空（不作答）',check:'确认答案',next:'下一题 →',prev:'← 上一题',finish:'交卷',finishConfirm:'还有题目没有作答，确定交卷吗？',
  correct:'答对了！',wrong:'答错了，看看讲解。',blanked:'已留空。看看讲解吧。',solution:'分步讲解',answerIs:'正确答案',yourAnswer:'你的答案',noAnswer:'未作答',
  timeLeft:'剩余时间',timeUp:'时间到，已自动交卷。',answered:'已作答',
  resultTitle:'本组完成！',mockResult:'模拟测验结果',score:'得分',correctCount:'答对',blankCount:'留空',wrongCount:'答错',retry:'再来一组',backHub:'返回',review:'逐题复习',
  aimeYes:{10:'达到 AIME 线（AMC 10 ≥ 100 分）！这只是练习，不代表正式成绩。',12:'达到 AIME 线（AMC 12 ≥ 85 分）！这只是练习，不代表正式成绩。'},
  aimeNo:{10:'AIME 线是 AMC 10 ≥ 100 分。继续加油！',12:'AIME 线是 AMC 12 ≥ 85 分。继续加油！'},
  amc8Score:'AMC 8 不扣分：不会的题也要估算后选一个。',
  account:{guestTitle:'未登录：成绩只保存在这个浏览器',guestBody:'登录后，AMC 8/10/12 的成绩、课程进度和模拟考记录会保存到你的账号，换设备也能继续。这个浏览器里已有的进度会在第一次登录时自动合并进账号。',login:'登录并保存进度',loading:'正在确认登录状态…',user:name=>`已登录：${name}`,synced:'进度已保存到账号 ✓',saving:'正在保存到账号…',retrying:'暂时无法保存到账号，稍后会自动重试。',offline:'现在离线：恢复网络后会自动保存。',expired:'登录已过期。请重新登录，最新进度会在登录后保存。',loadingSync:'正在从账号读取进度…',merged:'这个浏览器里的本地进度已合并到你的账号。',guestLocal:'未登录：成绩只保存在这个浏览器。',unavailable:'此浏览器无法保存成绩；仍可继续练习。登录后可保存到账号。',footerGuest:'未登录时，成绩只保存在这个浏览器里。登录后会保存到你的账号。',footerUser:'成绩和学习进度已绑定到你的账号，换设备登录也能看到。',lessonGuest:'未登录时，课程进度只保存在这个浏览器里；登录后会保存到账号。',recent:'最近成绩',localDev:'本地开发模式下无法登录。'},
  saved:'成绩只保存在此浏览器中。',unavailable:'此浏览器无法保存成绩；仍可继续练习。',error:'题目暂时无法载入，请返回后重试。',
  lessonReal:'真题风格练习：',lessonDrill:'基础练习：',lessonMock:'25 题模拟测验',models:'参考真题（AoPS Wiki）',modelLink:(c,n)=>`${c} 第${n}题`},
 en:{title:'AMC math competitions',eyebrow:'PIKO GAME · MATH EXPLORER',language:'Language',eikenLink:'EIKEN',footerBack:'Back to home',
  intro:'The AMC are maths competitions run by the Mathematical Association of America (MAA): AMC 8, AMC 10 and AMC 12. Choose a level, then Practise, Learn or Registration.',
  levelLabel:'Choose a level',levels:{8:'Grade 8 and below · 40 min',10:'Grade 10 and below · 75 min',12:'Grade 12 and below · 75 min'},
  tabs:{practice:'Practise',learn:'Learn',register:'Registration'},
  realTitle:'Real-style practice',realIntro:'Every problem is original to this site, written to match the type, structure and difficulty of real AMC problems: five choices A–E, getting harder as you go. Each one names the real problem it is modelled on and links to that page on the AoPS Wiki.',
  realCount:n=>`${n} problems`,realStart:'Start a set (up to 10)',best:'Best',
  mockTitle:'25-question mock',mockIntro:{8:'25 problems drawn by difficulty, 40 minutes. Scored like AMC 8: 1 point per correct answer, no penalty.',10:'25 problems drawn by difficulty, 75 minutes. Scored like AMC 10: 6 for correct, 1.5 for blank, 0 for wrong.',12:'25 problems drawn by difficulty, 75 minutes. Scored like AMC 12: 6 for correct, 1.5 for blank, 0 for wrong.'},mockStart:'Start the mock',
  drillsTitle:'Foundation drills (written answers, ordering, choices)',drillsIntro:'New to AMC 8? Start with these 600 original primary-level exercises.',
  pastTitle:'Past papers (external links)',pastIntro:'Read the original English problems and solutions on the AoPS Wiki.',pastCredit:'Past problems © MAA; this site only links to them.',
  bankNote:'All problems here are original and only follow the type and difficulty of real ones; the real problem texts are © MAA.',
  modeled:'Original',viewOriginal:'See the original (AoPS) ↗',bands:{1:'Warm-up',2:'Core',3:'Challenge'},
  question:'Question ',questionSuffix:'',of:' / ',exit:'← Exit',blank:'Leave blank',check:'Check answer',next:'Next →',prev:'← Previous',finish:'Submit',finishConfirm:'Some questions are unanswered. Submit anyway?',
  correct:'Correct!',wrong:'Not quite — read the solution.',blanked:'Left blank. Read the solution.',solution:'Step-by-step solution',answerIs:'Correct answer',yourAnswer:'Your answer',noAnswer:'Blank',
  timeLeft:'Time left',timeUp:'Time is up — your answers were submitted.',answered:'Answered',
  resultTitle:'Set complete!',mockResult:'Mock results',score:'Score',correctCount:'Correct',blankCount:'Blank',wrongCount:'Wrong',retry:'Try another set',backHub:'Back',review:'Review each problem',
  aimeYes:{10:'At or above the AIME line (AMC 10 ≥ 100)! This is practice, not an official score.',12:'At or above the AIME line (AMC 12 ≥ 85)! This is practice, not an official score.'},
  aimeNo:{10:'The AIME line is 100 on AMC 10. Keep going!',12:'The AIME line is 85 on AMC 12. Keep going!'},
  amc8Score:'AMC 8 has no penalty: estimate and choose an answer even when you are unsure.',
  account:{guestTitle:'Not signed in: scores stay in this browser only',guestBody:'Sign in to save your AMC 8/10/12 scores, lesson progress and mock exam history to your account and continue on any device. Progress already saved in this browser is merged into your account the first time you sign in.',login:'Sign in to save progress',loading:'Checking your sign-in…',user:name=>`Signed in as ${name}`,synced:'Progress saved to your account ✓',saving:'Saving to your account…',retrying:'Could not save to your account yet. Retrying automatically.',offline:'You are offline. Progress will be saved when you reconnect.',expired:'Your sign-in has expired. Sign in again and your latest progress will be saved.',loadingSync:'Loading your progress from your account…',merged:'Progress from this browser has been merged into your account.',guestLocal:'Not signed in: scores stay in this browser only.',unavailable:'Scores cannot be saved in this browser. You can still practise, or sign in to save to your account.',footerGuest:'While signed out, scores are kept in this browser only. Sign in to save them to your account.',footerUser:'Scores and learning progress are saved to your account and follow you to any device.',lessonGuest:'While signed out, lesson progress is kept in this browser only. Sign in to save it to your account.',recent:'Recent',localDev:'Sign-in is not available in local development mode.'},
  saved:'Scores are saved in this browser only.',unavailable:'Scores cannot be saved in this browser. You can still practise.',error:'The problems could not load. Go back and try again.',
  lessonReal:'Real-style practice: ',lessonDrill:'Drills: ',lessonMock:'25-question mock',models:'Real model problems (AoPS Wiki)',modelLink:(c,n)=>`${c} Problem ${n}`},
 ja:{title:'AMC 数学コンテスト',eyebrow:'PIKO GAME · MATH EXPLORER',language:'ことば',eikenLink:'英検',footerBack:'ホームへ戻る',
  intro:'AMC はアメリカ数学協会（MAA）が実施する数学コンテストのシリーズです：AMC 8・AMC 10・AMC 12。レベルを選んでから「練習」「学ぶ」「申し込み」を選ぼう。',
  levelLabel:'レベルを選ぶ',levels:{8:'8年生以下 · 40分',10:'10年生以下 · 75分',12:'12年生以下 · 75分'},
  tabs:{practice:'練習',learn:'学ぶ',register:'申し込み'},
  realTitle:'本番形式の練習',realIntro:'問題はすべてこのサイトのオリジナルで、本物の AMC の問題の形式・構成・難しさに合わせて作っています。A〜E の5択で、だんだん難しくなります。どの問題にも参考にした本番の問題を記し、AoPS Wiki のページにリンクしています。',
  realCount:n=>`${n} 問`,realStart:'セットをはじめる（最大10問）',best:'ベスト',
  mockTitle:'25問の模試',mockIntro:{8:'難しさの順に25問、40分。AMC 8 と同じく、正解1点・減点なし。',10:'難しさの順に25問、75分。AMC 10 と同じく、正解6点・無回答1.5点・不正解0点。',12:'難しさの順に25問、75分。AMC 12 と同じく、正解6点・無回答1.5点・不正解0点。'},mockStart:'模試をはじめる',
  drillsTitle:'基礎練習（記入・並べかえ・選択）',drillsIntro:'AMC 8 がはじめてなら、小学校レベルのオリジナル練習600問から始めよう。',
  pastTitle:'過去問（外部リンク）',pastIntro:'AoPS Wiki で、英語の本番の問題と解説を見られます。',pastCredit:'過去問の権利は MAA に帰属します。このサイトはリンクのみです。',
  bankNote:'このサイトの問題はすべてオリジナルで、本番の問題の形式と難しさだけを参考にしています。本番の問題文の権利は MAA にあります。',
  modeled:'オリジナル',viewOriginal:'もとの問題を見る（AoPS）↗',bands:{1:'基本',2:'標準',3:'挑戦'},
  question:'第',questionSuffix:'問',of:' / ',exit:'← やめる',blank:'答えない（空欄）',check:'答えをたしかめる',next:'つぎへ →',prev:'← まえへ',finish:'提出する',finishConfirm:'まだ答えていない問題があります。提出しますか？',
  correct:'正解！',wrong:'おしい！解説を読もう。',blanked:'空欄にしました。解説を読もう。',solution:'順に考えよう',answerIs:'正しい答え',yourAnswer:'あなたの答え',noAnswer:'空欄',
  timeLeft:'残り時間',timeUp:'時間になりました。答えを提出しました。',answered:'回答ずみ',
  resultTitle:'セット完了！',mockResult:'模試の結果',score:'得点',correctCount:'正解',blankCount:'空欄',wrongCount:'不正解',retry:'もう1セット',backHub:'もどる',review:'1問ずつふりかえる',
  aimeYes:{10:'AIME の基準（AMC 10 で 100 点以上）に届きました！ 練習なので公式の成績ではありません。',12:'AIME の基準（AMC 12 で 85 点以上）に届きました！ 練習なので公式の成績ではありません。'},
  aimeNo:{10:'AIME の基準は AMC 10 で 100 点。この調子で！',12:'AIME の基準は AMC 12 で 85 点。この調子で！'},
  amc8Score:'AMC 8 は減点なし。わからなくても見積もって1つ選ぼう。',
  account:{guestTitle:'ログインしていません：記録はこのブラウザーだけに保存されます',guestBody:'ログインすると、AMC 8/10/12 の点数・課の進み具合・模試の記録がアカウントに保存され、ほかの端末でも続きから練習できます。このブラウザーにある記録は、はじめてログインしたときに自動でアカウントへまとめます。',login:'ログインして記録を保存',loading:'ログイン状態を確認しています…',user:name=>`ログイン中：${name}`,synced:'記録はアカウントに保存されました ✓',saving:'アカウントに保存しています…',retrying:'まだアカウントに保存できていません。自動でもう一度ためします。',offline:'オフラインです。つながったら自動で保存します。',expired:'ログインの有効期限が切れました。もう一度ログインすると、最新の記録が保存されます。',loadingSync:'アカウントから記録を読み込んでいます…',merged:'このブラウザーの記録をアカウントにまとめました。',guestLocal:'ログインしていません：記録はこのブラウザーだけに保存されます。',unavailable:'このブラウザーでは記録を保存できません。練習は続けられます。ログインするとアカウントに保存できます。',footerGuest:'ログインしていないあいだ、記録はこのブラウザーだけに保存されます。ログインするとアカウントに保存されます。',footerUser:'点数と学習の記録はアカウントに保存され、どの端末でも見られます。',lessonGuest:'ログインしていないあいだ、課の進み具合はこのブラウザーだけに保存されます。ログインするとアカウントに保存されます。',recent:'最近の記録',localDev:'ローカル開発モードではログインできません。'},
  saved:'記録はこのブラウザーだけに保存します。',unavailable:'このブラウザーでは記録を保存できません。練習は続けられます。',error:'問題を読み込めませんでした。もどってもう一度お試しください。',
  lessonReal:'本番形式の練習：',lessonDrill:'基礎練習：',lessonMock:'25問の模試',models:'参考にする本番の問題（AoPS Wiki）',modelLink:(c,n)=>`${c} 第${n}問`}
};
