// "How to register" guide for AMC 8 / 10 / 12, 2026-27 season.
// Last verified 2026-10-03 against the official pages linked in each section.
// Only MAA and MAA-authorized regional organizers are linked — never agencies
// or training businesses. Items we could not verify are flagged `unverified`.
import {T} from './AmcRealCore.mjs';

export const REG_VERIFIED='2026-10-03';
const L=(url,label)=>({url,label});
const MAA_INTL='https://maa.org/amc-international/';

export const REGISTRATION={
 title:T('报名指南（2026-27 赛季）','How to register (2026-27 season)','申し込みガイド（2026-27 年度）'),
 intro:T('学生和家长不能直接向 MAA 报名，而是通过所在地区的官方组织方或学校考点参加。下面按地区整理了 2026-27 赛季的日期与官方链接。所有时间都标注了时区，并换算成日本时间（JST）。','Students and parents cannot register with the MAA directly; you take part through the official organizer for your region or through a school test site. Below are the 2026-27 dates and official links by region. Every time shows its time zone, with a conversion to Japan time (JST).','MAA に生徒や保護者が直接申し込むことはできません。地域の公式主催団体か、学校などの会場を通して受験します。地域ごとに 2026-27 年度の日程と公式リンクをまとめました。時刻にはすべてタイムゾーンを記し、日本時間（JST）も示しています。'),
 verified:T('最后核对日期','Last verified','最終確認日'),
 unverifiedLabel:T('未能核实','Not verified','未確認'),
 officialLinks:T('官方链接','Official links','公式リンク'),
 dateCols:[T('项目','Event','項目'),T('当地时间','Local time','現地時間'),T('日本时间','Japan time (JST)','日本時間'),T('报名/备注','Registration / notes','申し込み・備考')],
 caution:T('请认准官方渠道：网上有不少培训或代理机构自称“官方”，日期也可能与官方不同。本页只链接 MAA 及 MAA 授权的地区组织方。日期、费用以组织方最新公告为准。','Use official channels only: some training or agency websites call themselves “official” and may list different dates. This page links only to the MAA and MAA-authorized regional organizers. Always follow the organizer’s latest notice for dates and fees.','公式の窓口を使いましょう。「公式」を名乗る塾や代理店のサイトもあり、日程が違う場合があります。このページは MAA と MAA 公認の地域主催団体だけにリンクしています。日程や費用は主催団体の最新のお知らせを確認してください。'),
 regions:[
  {id:'china',flag:'🇨🇳',title:T('中国大陆','Mainland China','中国本土'),
   organizer:T('阿思丹（ASDAN China）——MAA 国际负责人名单中的“中国·私立学校”组织方，负责中国大陆 AMC 8 / 10 / 12 报名。','ASDAN China (阿思丹) — listed by the MAA as the regional organizer for “China – private schools”; runs AMC 8 / 10 / 12 registration in mainland China.','ASDAN China（阿思丹）— MAA の地域責任者リストで「中国・私立学校」の主催団体。中国本土の AMC 8 / 10 / 12 の申し込みを担当。'),
   how:[T('通过阿思丹官网或其微信小程序报名，或经由阿思丹授权的学校考点报名。阿思丹表示不与培训机构合作设立 AMC 8 考点。','Register on the ASDAN website or its WeChat mini-program, or through an ASDAN-authorized school test centre. ASDAN states it does not work with training institutions to run AMC 8 centres.','ASDAN の公式サイトか WeChat ミニプログラム、または ASDAN 公認の学校会場から申し込みます。ASDAN は塾などと AMC 8 会場を設けていないと説明しています。'),
        T('公立学校的同学：MAA 名单中另有“中国·公立学校”负责人，但我们没有找到其官网，请向本校数学老师了解学校是否为考点。','Public-school students: the MAA list names a separate leader for “China – public schools”, but we found no website — ask your school’s maths teacher whether the school is a test centre.','公立学校の生徒：MAA のリストには「中国・公立学校」の別の責任者がいますが、公式サイトは見つかりませんでした。学校の数学の先生に会場かどうか確認してください。'),
        T('在美国或加拿大的学校就读的学生，不能在中国赛区参加。','Students enrolled at a school in the USA or Canada cannot sit the China region.','アメリカ・カナダの学校に在籍する生徒は中国地区では受験できません。'),
        T('退费：截止前取消扣除 25%，截止后不退（阿思丹规则）。咨询电话 400-9999-615（每天 9:00–18:00）。','Refunds: 25% is deducted if you cancel before the deadline; no refund afterwards (ASDAN policy). Hotline 400-9999-615 (daily 9:00–18:00).','返金：締切前の取り消しは 25% 差し引き、締切後は返金なし（ASDAN の規定）。電話 400-9999-615（毎日 9:00〜18:00）。')],
   dates:[
    {event:T('AMC 10A / 12A','AMC 10A / 12A','AMC 10A / 12A'),local:T('2026 年 11 月 6 日（周五）17:00–18:15 北京时间','Fri Nov 6, 2026, 17:00–18:15 Beijing time (UTC+8)','2026年11月6日（金）17:00〜18:15 北京時間'),jst:T('18:00–19:15 JST','18:00–19:15 JST','18:00〜19:15 JST'),note:T('报名截止日期：阿思丹公开页面尚未列出 2026 年数据','Registration deadline: not yet shown on ASDAN’s public page for 2026','申込締切：ASDAN の公開ページに 2026 年の記載なし'),unverified:true},
    {event:T('AMC 10B / 12B','AMC 10B / 12B','AMC 10B / 12B'),local:T('2026 年 11 月 14 日（周六）17:00–18:15 北京时间','Sat Nov 14, 2026, 17:00–18:15 Beijing time (UTC+8)','2026年11月14日（土）17:00〜18:15 北京時間'),jst:T('18:00–19:15 JST','18:00–19:15 JST','18:00〜19:15 JST'),note:T('同上','Same as above','同上'),unverified:true},
    {event:T('AMC 8','AMC 8','AMC 8'),local:T('2027 年 1 月 22 日（周五）17:00–17:40 北京时间','Fri Jan 22, 2027, 17:00–17:40 Beijing time (UTC+8)','2027年1月22日（金）17:00〜17:40 北京時間'),jst:T('18:00–18:40 JST','18:00–18:40 JST','18:00〜18:40 JST'),note:T('报名截止 2027 年 1 月 12 日；准考证 1 月 16 日 12:00 – 1 月 22 日 17:00 可下载','Registration closes Jan 12, 2027; admission tickets available Jan 16, 12:00 – Jan 22, 17:00','申込締切 2027年1月12日。受験票は1月16日12:00〜1月22日17:00')}
   ],
   unverified:[T('费用：请以阿思丹公告为准（公开页面未列出）。','Fees: see the organizer (not listed on the public pages).','費用：主催団体で確認してください（公開ページに記載なし）。'),T('AMC 10/12 的 2026 年报名截止日期。','The 2026 AMC 10/12 registration deadline.','2026年 AMC 10/12 の申込締切。'),T('是否全部为线下考试。','Whether all sittings are in person.','すべて会場受験かどうか。')],
   links:[L('https://www.seedasdan.asia/amc10/',T('阿思丹 AMC 10 页面','ASDAN AMC 10 page (Chinese)','ASDAN AMC 10 ページ（中国語）')),L('https://www.seedasdan.asia/amc12/',T('阿思丹 AMC 12 页面','ASDAN AMC 12 page (Chinese)','ASDAN AMC 12 ページ（中国語）')),L('https://www.seedasdan.asia/amc8/',T('阿思丹 AMC 8 页面','ASDAN AMC 8 page (Chinese)','ASDAN AMC 8 ページ（中国語）')),L('https://www.seedasdan.asia/en/amc8-en/',T('阿思丹 AMC 8 英文页面','ASDAN AMC 8 page (English)','ASDAN AMC 8 ページ（英語）')),L(MAA_INTL,T('MAA 国际负责人名单','MAA AMC International leaders','MAA 国際責任者リスト'))]},
  {id:'japan',flag:'🇯🇵',title:T('日本','Japan','日本'),
   organizer:T('Magic Square Association（香港，MSA）——MAA 指定的香港、澳门和日本 AMC 组织方。目前没有日本本地的日语官方报名窗口。','Magic Square Association (Hong Kong, MSA) — the MAA-designated AMC host for Hong Kong, Macau and Japan. There is no Japan-based, Japanese-language official registration office.','Magic Square Association（香港、MSA）— MAA が指定した香港・マカオ・日本の AMC 主催団体。日本国内の日本語による公式窓口はありません。'),
   how:[T('在 msa.com.hk 网站注册并报名（英文/中文）。','Register on msa.com.hk (English/Chinese).','msa.com.hk で登録・申し込み（英語／中国語）。'),
        T('日本考生的确切考试时间和考场以准考证为准；考场没有公开列出。','For candidates in Japan, the exact time and venue are given on the admission ticket; venues are not published.','日本の受験者の正確な時間と会場は受験票で案内されます。会場は公開されていません。'),
        T('电脑作答：请自带笔记本电脑或 iPad，以及打印好的准考证（AMC 8 还需带照片身份证件）。','Computer-based: bring your own laptop or iPad and a printed admission ticket (plus photo ID for AMC 8).','コンピューターで解答：ノートPCか iPad、印刷した受験票を持参（AMC 8 は写真付き身分証も）。'),
        T('报名期内取消可全额退款，之后不退。联系邮箱 msahk@vip.qq.com。','Full refund if you cancel during the registration period; none afterwards. Contact: msahk@vip.qq.com.','申込期間中の取り消しは全額返金、期間後は返金なし。連絡先 msahk@vip.qq.com。'),
        T('已经通过所在学校（例如部分国际学校）报名的同学，不要重复报名。','If your school (for example some international schools) has already registered you, do not register again.','学校（一部のインターナショナルスクールなど）経由で申し込み済みなら、重ねて申し込まないでください。')],
   dates:[
    {event:T('AMC 10A / 12A','AMC 10A / 12A','AMC 10A / 12A'),local:T('2026 年 11 月 6 日（周五）17:00–18:15 香港时间','Fri Nov 6, 2026, 17:00–18:15 Hong Kong time (UTC+8)','2026年11月6日（金）17:00〜18:15 香港時間'),jst:T('18:00–19:15 JST（以准考证为准）','18:00–19:15 JST (check your ticket)','18:00〜19:15 JST（受験票で確認）'),note:T('报名截止 2026 年 10 月 28 日；准考证 11 月 4 日起','Registration closes Oct 28, 2026; tickets from Nov 4','申込締切 2026年10月28日。受験票は11月4日から')},
    {event:T('AMC 10B / 12B','AMC 10B / 12B','AMC 10B / 12B'),local:T('2026 年 11 月 14 日（周六）17:00–18:15 香港时间','Sat Nov 14, 2026, 17:00–18:15 Hong Kong time (UTC+8)','2026年11月14日（土）17:00〜18:15 香港時間'),jst:T('18:00–19:15 JST（以准考证为准）','18:00–19:15 JST (check your ticket)','18:00〜19:15 JST（受験票で確認）'),note:T('报名截止 2026 年 10 月 28 日；准考证 11 月 12 日起','Registration closes Oct 28, 2026; tickets from Nov 12','申込締切 2026年10月28日。受験票は11月12日から')},
    {event:T('AMC 8','AMC 8','AMC 8'),local:T('2027 年 1 月 22 日（周五）17:30–18:10 香港时间','Fri Jan 22, 2027, 17:30–18:10 Hong Kong time (UTC+8)','2027年1月22日（金）17:30〜18:10 香港時間'),jst:T('18:30–19:10 JST（以准考证为准）','18:30–19:10 JST (check your ticket)','18:30〜19:10 JST（受験票で確認）'),note:T('报名截止：说明文字为 2027 年 1 月 8 日，但网站数据显示 2026 年 12 月 29 日——建议尽早报名','Deadline: the text says Jan 8, 2027, but the portal data shows Dec 29, 2026 — register early','締切：本文は2027年1月8日、ポータルのデータは2026年12月29日 — 早めの申し込みを'),unverified:true}
   ],
   unverified:[T('费用：请以组织方为准（未公开）。','Fees: see the organizer (not published).','費用：主催団体で確認（非公開）。'),T('日本的考场位置。','Venue locations in Japan.','日本の会場の場所。'),T('AMC 8 的准确报名截止日（1 月 8 日或 12 月 29 日）。','The exact AMC 8 deadline (Jan 8 or Dec 29).','AMC 8 の正確な締切（1月8日か12月29日か）。')],
   links:[L('https://msa.com.hk/',T('MSA 报名网站（msa.com.hk）','MSA registration portal (msa.com.hk)','MSA 申込サイト（msa.com.hk）')),L('https://magicsquareassociation.org/main',T('Magic Square Association 介绍','Magic Square Association information','Magic Square Association の案内')),L(MAA_INTL,T('MAA 国际负责人名单','MAA AMC International leaders','MAA 国際責任者リスト'))]},
  {id:'usa',flag:'🇺🇸',title:T('美国（及加拿大）','USA (and Canada)','アメリカ（とカナダ）'),
   organizer:T('MAA 直接管理考点。学生通过自己的学校，或附近已注册的考点（大学、数学圈、学习中心等）参加。','The MAA runs the test sites directly. Students take the AMC through their own school or a nearby registered site (a university, maths circle or learning centre).','MAA が会場を直接管理しています。自分の学校か、近くの登録済み会場（大学・数学サークル・学習センターなど）で受験します。'),
   how:[T('先问学校是否举办；如果没有，查看 MAA 公布的 2026-27 考点名单并自行联系。家庭学校（homeschool）不能当考点，但可以去其他考点参加。','Ask your school first. If it does not host, use the MAA’s public list of 2026-27 sites and contact one yourself. Home schools cannot be sites, but homeschoolers can test at another site.','まず学校に確認。実施しない場合は MAA の 2026-27 年度会場リストから自分で連絡します。ホームスクールは会場になれませんが、ほかの会場で受験できます。'),
        T('资格：全日制就读并实际在美国或加拿大的学校上学。','Eligibility: full-time enrolment at, and physical attendance of, a school in the USA or Canada.','資格：アメリカかカナダの学校に全日制で在籍し、実際に通学していること。'),
        T('下面的截止日期是考点（学校/机构）向 MAA 注册的截止时间（美国东部时间 23:59）；学生应提前向考点报名。','The deadlines below are for sites registering with the MAA (11:59 PM US Eastern); students should sign up with their site well before.','下の締切は会場（学校など）が MAA に登録する締切（米国東部時間 23:59）。生徒はそれより前に会場へ申し込みます。'),
        T('费用由考点支付给 MAA（每场考点费 55 / 75 / 115 美元，另按每 10 份学生名额 30 美元（AMC 10/12）或 25 美元（AMC 8）计）；考点可能向学生收费，也可能免费。','Fees are paid by the site to the MAA ($55 / $75 / $115 site fee per competition, plus $30 per bundle of 10 students for AMC 10/12 or $25 for AMC 8); sites may charge students or be free.','費用は会場が MAA に支払います（大会ごとに会場費 55 / 75 / 115 ドル、さらに生徒10人分ごとに AMC 10/12 は 30 ドル、AMC 8 は 25 ドル）。会場が生徒に費用を求めることも、無料のこともあります。'),
        T('MAA 咨询：amcinfo@maa.org，1-800-527-3690。','MAA help: amcinfo@maa.org, 1-800-527-3690.','MAA の問い合わせ：amcinfo@maa.org、1-800-527-3690。')],
   dates:[
    {event:T('AMC 10A / 12A','AMC 10A / 12A','AMC 10A / 12A'),local:T('2026 年 11 月 5 日（周四），具体时段由考点安排','Thu Nov 5, 2026 (time set by the site)','2026年11月5日（木）時間は会場が決定'),jst:T('—','—','—'),note:T('考点注册：常规 10 月 15 日（新考点最后期限），逾期 10 月 28 日（仅限往年考点）','Site registration: regular Oct 15 (last day for new sites), late Oct 28 (returning sites only)','会場登録：通常 10月15日（新規会場の最終日）、延長 10月28日（継続会場のみ）')},
    {event:T('AMC 10B / 12B','AMC 10B / 12B','AMC 10B / 12B'),local:T('2026 年 11 月 13 日（周五），具体时段由考点安排','Fri Nov 13, 2026 (time set by the site)','2026年11月13日（金）時間は会場が決定'),jst:T('—','—','—'),note:T('同上','Same as above','同上')},
    {event:T('AMC 8','AMC 8','AMC 8'),local:T('2027 年 1 月 21–27 日中的一天（由考点选择）','One day in Jan 21–27, 2027 (chosen by the site)','2027年1月21〜27日のうち1日（会場が選ぶ）'),jst:T('—','—','—'),note:T('考点注册：早鸟 10 月 28 日，常规 2027 年 1 月 5 日，逾期 1 月 14 日','Site registration: early Oct 28, regular Jan 5, 2027, late Jan 14, 2027','会場登録：早期 10月28日、通常 2027年1月5日、延長 1月14日')},
    {event:T('截止时间换算','Deadline time conversion','締切時刻の換算'),local:T('美国东部时间 23:59','11:59 PM US Eastern','米国東部時間 23:59'),jst:T('次日 12:59 JST（11 月 1 日前）/ 13:59 JST（之后）','Next day 12:59 JST (before Nov 1) / 13:59 JST (after)','翌日 12:59 JST（11月1日まで）／13:59 JST（以降）'),note:T('夏令时于 2026 年 11 月 1 日结束','Daylight saving time ends Nov 1, 2026','夏時間は2026年11月1日に終了')}
   ],
   unverified:[],
   links:[L('https://maa.org/student-programs/amc/',T('MAA AMC 页面','MAA AMC page','MAA AMC ページ')),L('https://maa.org/amcreg/',T('MAA 报名与日期','MAA registration and dates','MAA 申し込みと日程')),L('https://docs.google.com/spreadsheets/d/16mX4qHvr4EEQviRwxSq7JzE3baYCZcFgHYZvTQyPHDo/edit?usp=sharing',T('MAA 2026-27 考点名单（Google 表格）','MAA list of 2026-27 sites (Google Sheet)','MAA 2026-27 年度 会場リスト（Google スプレッドシート）'))]},
  {id:'other',flag:'🌏',title:T('其他国家和地区','Other countries and regions','その他の国・地域'),
   organizer:T('在美国和加拿大以外，AMC 由 MAA 授权的各地区国际负责人（International Group Leader）组织。请通过你所居住国家/地区的负责人报名。','Outside the USA and Canada, AMC is run by MAA-authorized International Group Leaders. Register through the leader for the country or region where you live.','アメリカ・カナダ以外では、MAA 公認の国際グループリーダーが AMC を実施します。住んでいる国・地域のリーダーを通して申し込みます。'),
   how:[T('打开 MAA 的 AMC International 页面，找到你的国家/地区（例如香港、澳门同样由 MSA 负责）。','Open the MAA AMC International page and find your country or region (Hong Kong and Macau are also handled by MSA).','MAA の AMC International ページで自分の国・地域をさがします（香港・マカオも MSA が担当）。'),
        T('MAA 的名单目前标注为 2025-26，可能会更新。','The MAA list is currently labelled 2025-26 and may change.','MAA のリストは現在 2025-26 年度の表記で、変わる可能性があります。')],
   dates:[],unverified:[T('2026-27 赛季的国际负责人名单（MAA 页面仍为 2025-26）。','The 2026-27 list of leaders (the MAA page still says 2025-26).','2026-27 年度のリーダー一覧（MAA のページはまだ 2025-26）。')],
   links:[L(MAA_INTL,T('MAA AMC International（各国负责人名单）','MAA AMC International (list of leaders)','MAA AMC International（各国のリーダー一覧）'))]}
 ],
 path:{
  title:T('晋级路线：AMC 10/12 → AIME → USAJMO / USAMO','The pathway: AMC 10/12 → AIME → USAJMO / USAMO','進むルート：AMC 10/12 → AIME → USAJMO / USAMO'),
  steps:[
   {icon:'1️⃣',title:T('AMC 8（1 月）','AMC 8 (January)','AMC 8（1月）'),body:T('8 年级及以下。不扣分，全部作答。','Grade 8 and below. No penalty — answer every question.','8 年生以下。減点なし、全問答えよう。')},
   {icon:'2️⃣',title:T('AMC 10 / AMC 12（11 月）','AMC 10 / AMC 12 (November)','AMC 10 / AMC 12（11月）'),body:T('A、B 两场都可参加。2026-27 起 AIME 线固定为：AMC 10 ≥ 100 分，或 AMC 12 ≥ 85 分。','You may take both A and B. From 2026-27 the AIME cut-offs are fixed: AMC 10 ≥ 100 or AMC 12 ≥ 85.','A・B 両方受けられます。2026-27 年度から AIME の基準は固定：AMC 10 で 100 点以上、または AMC 12 で 85 点以上。')},
   {icon:'3️⃣',title:T('AIME（2027 年 2 月 5 日或 6 日）','AIME (Feb 5 or 6, 2027)','AIME（2027年2月5日または6日）'),body:T('仅限受邀。参加当天须年满 13 岁。15 题，答案为 0–999 的整数，两段各 90 分钟。在美国和加拿大，AIME 在 Pearson 考试中心用电脑作答，费用 85 美元加税，由学生向 Pearson 支付。','Invitation only. You must be at least 13 on AIME day. 15 questions with integer answers 0–999, two 90-minute parts. In the USA/Canada it is taken on computer at Pearson test centres; the $85 + tax fee is paid by the student to Pearson.','招待制。AIME 当日に 13 歳以上であること。15 問、答えは 0〜999 の整数、90 分 × 2 部。アメリカ・カナダでは Pearson の会場でコンピューター受験、費用 85 ドル＋税は生徒が Pearson に支払います。')},
   {icon:'4️⃣',title:T('USAJMO / USAMO（2027 年 3 月 20–21 日）','USAJMO / USAMO (Mar 20–21, 2027)','USAJMO / USAMO（2027年3月20〜21日）'),body:T('经 AMC 10 晋级者参加 USAJMO，经 AMC 12 晋级者参加 USAMO；入选主要看 AIME 成绩。两天、每天 3 道证明题、各 4.5 小时。','Qualifiers through AMC 10 take the USAJMO and through AMC 12 the USAMO; selection is based mainly on the AIME score. Two days, three proof problems in 4.5 hours each day.','AMC 10 経由は USAJMO、AMC 12 経由は USAMO。選抜は主に AIME の点数。2日間、各日 4.5 時間で証明問題 3 問。')},
   {icon:'5️⃣',title:T('MOP 与美国 IMO 国家队','MOP and the US IMO team','MOP と米国 IMO 代表'),body:T('USAMO/USAJMO 高分者受邀参加暑期 MOP（约 60 人以上），再经选拔测试产生 6 人的美国 IMO 国家队。MOP 要求美国公民或永久居民。','Top USAMO/USAJMO scorers are invited to the summer MOP (60+ students); team selection tests then choose the six-person US IMO team. MOP requires US citizenship or permanent residency.','USAMO/USAJMO の上位者は夏の MOP（60 人以上）に招待され、選抜テストで6人の米国 IMO 代表が決まります。MOP にはアメリカ市民権か永住権が必要。')}
  ],
  intl:T('给中国和日本的同学：AMC 是很好的国际数学“标尺”，成绩和证书都很有意义。不过，MAA 规则中的 AIME 资格面向在美国或加拿大的学校就读的学生；海外考生要按所在地区组织方的规定执行，2027 年中国和日本赛区的 AIME 安排目前尚未公布。USAMO、MOP 和美国 IMO 国家队实际上只面向在美国或加拿大就读的学生（MOP 和国家队还要求美国公民或永久居民身份）。如果目标是 IMO，中国同学的路线是全国中学生数学奥林匹克（CMO）等国内赛事，日本同学的路线是日本数学奥林匹克（JMO）。','For students in China and Japan: AMC is an excellent international benchmark, and the scores and certificates are worth having. However, the AIME eligibility rules published by the MAA are for students at schools in the USA or Canada; students elsewhere follow their regional organizer, and 2027 AIME arrangements for China and Japan have not been announced. The USAMO, MOP and US IMO team are effectively for US/Canada students (MOP and the team also require US citizenship or permanent residency). If your goal is the IMO, the route in China is the national olympiad (CMO) and related contests, and in Japan it is the Japan Mathematical Olympiad (JMO).','中国・日本の皆さんへ：AMC は国際的な数学の「ものさし」としてとても良い大会で、成績や賞状にも価値があります。ただし MAA が定める AIME の資格はアメリカ・カナダの学校の生徒向けで、海外の受験者は地域主催団体の規定に従います。2027 年の中国・日本地区の AIME の扱いはまだ発表されていません。USAMO・MOP・米国 IMO 代表は実質的にアメリカ・カナダの生徒向けです（MOP と代表にはアメリカ市民権か永住権も必要）。IMO をめざすなら、中国では全国中学生数学オリンピック（CMO）など、日本では日本数学オリンピック（JMO）がその道です。'),
  links:[L('https://www.maa.org/maa-invitational-competitions',T('MAA：AIME / USAMO / MOP / IMO','MAA: AIME / USAMO / MOP / IMO','MAA：AIME / USAMO / MOP / IMO')),L('https://maa.org/wp-content/uploads/2026/08/2026-27-AIME-Policies.pdf',T('MAA 2026-27 AIME 规则（PDF）','MAA 2026-27 AIME rules (PDF)','MAA 2026-27 AIME 規則（PDF）'))]
 },
 tips:{title:T('给家长的小贴士','Tips for parents','保護者の方へ'),items:[
  T('留意截止日期：日本赛区 AMC 10/12 报名截止 2026 年 10 月 28 日。','Watch the deadlines: Japan’s AMC 10/12 registration closes Oct 28, 2026.','締切に注意：日本地区の AMC 10/12 は 2026年10月28日締切。'),
  T('中国和日本赛区的考试时间与美国不同，请按本页的当地时间准备。','China and Japan sit at different times from the USA; use the local times on this page.','中国・日本の試験時間はアメリカと異なります。このページの現地時間で準備を。'),
  T('AMC 10/12 成绩与 AIME 邀请通常在 12 月中旬公布（美国）；AMC 8 成绩约在 3 月初。地区组织方可能有自己的发布时间。','AMC 10/12 scores and AIME invitations usually come out in mid-December (USA); AMC 8 scores in early March. Regional organizers may have their own schedule.','AMC 10/12 の結果と AIME の招待は通常12月中旬（アメリカ）、AMC 8 は3月初め頃。地域主催団体の発表時期は異なる場合があります。'),
  T('本站练习题是仿照真题风格的原创题，用于学习，不代表官方题目或成绩预测。','Practice problems on this site are original problems in the real style, for learning only — not official problems or score predictions.','このサイトの練習問題は本番形式のオリジナル問題で、学習用です。公式問題や成績の予測ではありません。')]}
};
