import { Chess } from './vendor/chess.mjs';

const pieces={wk:'♔',wq:'♕',wr:'♖',wb:'♗',wn:'♘',wp:'♙',bk:'♚',bq:'♛',br:'♜',bb:'♝',bn:'♞',bp:'♟'};
const lessons=[
  {fen:null,from:'e2',to:'e4'},
  {fen:'4k3/8/8/8/8/8/8/R3K3 w - - 0 1',from:'a1',to:'a4'},
  {fen:'4k3/8/8/8/8/8/8/2B1K3 w - - 0 1',from:'c1',to:'g5'},
  {fen:null,from:'g1',to:'f3'},
  {fen:'4k3/8/8/3p4/4P3/8/8/4K3 w - - 0 1',from:'e4',to:'d5'},
  {fen:'7k/P7/8/8/8/8/8/4K3 w - - 0 1',from:'a7',to:'a8',promotion:'q'},
  {fen:'4k3/8/8/8/8/8/4R3/4K3 w - - 0 1',from:'e2',to:'e7',check:true},
  {fen:'7k/5Q2/6K1/8/8/8/8/8 w - - 0 1',from:'f7',to:'g7',mate:true}
];
const copy={
 zh:{title:'国际象棋新手课',close:'返回大厅',back:'上一步',next:'下一步',again:'再练一次',done:'完成啦！去下一局',good:'做到了！',retry:'这一步还不行，再观察一下。',hint:'先点要移动的棋子，再点发光的格子。',progress:'课程',names:[['兵先向前','白棋先走。兵通常向前一格，第一次可以走两格。把 e2 的兵走到 e4。'],['车走直线','车可以横着或竖着走，但不能跳过棋子。把 a1 的车走到 a4。'],['象走斜线','象一直沿斜线走，也不能跳过棋子。把 c1 的象走到 g5。'],['马走“日”字','马先走两格，再转一格。它是唯一可以跳过棋子的棋子。把 g1 的马走到 f3。'],['吃掉对方棋子','走到对方棋子所在的格子，就能吃掉它。用 e4 的兵吃掉 d5 的黑兵。'],['兵可以升变','兵走到棋盘另一端，就能变成后、车、象或马。把 a7 的兵走到 a8，变成后。'],['将军','攻击到王，就叫“将军”。被将军的一方下一步必须保护王。把 e2 的车走到 e7。'],['将死就获胜','王被攻击，而且没有任何安全走法，就是“将死”。把 f7 的后走到 g7。']],end:'你已经会开始一局了。王每次走一格；后能走直线和斜线。王车易位能同时移动王和车，但路径不能被占，王也不能穿过被攻击的格子。吃过路兵只会在对方兵刚走两格时出现。连续三次相同局面、五十回合没有兵移动或吃子、子力不足、逼和或双方同意，都可能和棋。'},
 en:{title:'Your first chess lesson',close:'Back to lobby',back:'Previous',next:'Next',again:'Try again',done:'All done! Play a game',good:'You did it!',retry:'That move does not work here. Take another look.',hint:'Tap the piece first, then tap the glowing square.',progress:'Lesson',names:[['Pawns move forward','White moves first. A pawn usually moves one square forward and may move two on its first turn. Move the e2 pawn to e4.'],['Rooks move in straight lines','A rook moves sideways or forward and back. It cannot jump over a piece. Move the a1 rook to a4.'],['Bishops move diagonally','A bishop stays on diagonal lines and cannot jump. Move the c1 bishop to g5.'],['Knights make an L','A knight goes two squares, then turns one. It is the only piece that can jump. Move the g1 knight to f3.'],['Capture a piece','Move onto an opponent’s square to capture that piece. Use the e4 pawn to take the black pawn on d5.'],['Promote a pawn','A pawn reaching the far side becomes a queen, rook, bishop or knight. Move a7 to a8 and choose a queen.'],['Check the king','When you attack the king, that is check. The other player must make the king safe. Move the e2 rook to e7.'],['Checkmate wins','Checkmate means the king is attacked and has no safe reply. Move the f7 queen to g7.']],end:'You can now begin a game. A king moves one square; a queen uses straight and diagonal lines. Castling moves king and rook together when the path is clear and safe. En passant is available only just after an opposing pawn moves two squares. Three repeated positions, fifty moves without a pawn move or capture, insufficient material, stalemate or agreement can end in a draw.'},
 ja:{title:'はじめてのチェス',close:'ロビーにもどる',back:'まえへ',next:'つぎへ',again:'もういちど',done:'できた！たいせんしてみよう',good:'できたね！',retry:'そのうごきはできないよ。もういちどみてみよう。',hint:'まずこまをおして、つぎにひかるマスをおそう。',progress:'レッスン',names:[['ポーンはまえへ','しろがさきにうごくよ。ポーンはふつう1マスまえへ。さいしょだけ2マスすすめるよ。e2からe4へうごかそう。'],['ルークはまっすぐ','ルークは、たてとよこにまっすぐうごくよ。ほかのこまをとびこせないよ。a1からa4へうごかそう。'],['ビショップはななめ','ビショップは、ななめにうごくよ。ほかのこまをとびこせないよ。c1からg5へうごかそう。'],['ナイトはLのかたち','ナイトは2マスすすんで、1マスまがるよ。ほかのこまをとびこせる、たったひとつのこま。g1からf3へうごかそう。'],['あいてのこまをとる','あいてのこまがいるマスへいくと、そのこまをとれるよ。e4のポーンでd5のくろいポーンをとろう。'],['ポーンがへんしん','ポーンがいちばんおくまでいくと、クイーン、ルーク、ビショップ、ナイトにへんしん。a7からa8へすすんで、クイーンになろう。'],['チェック','キングをこうげきすると「チェック」。チェックされたら、つぎにキングをまもるよ。e2のルークをe7へうごかそう。'],['チェックメイトでかち','キングがこうげきされ、どこにもうごけないと「チェックメイト」。f7のクイーンをg7へうごかそう。']],end:'これでたいきょくをはじめられるよ。キングは1マス、クイーンはまっすぐとななめ。キャスリングはキングとルークをいっしょにうごかすよ。みちがあいていて、キングがあぶないマスをとおらないときだけ。アンパッサンは、あいてのポーンが2マスすすんだすぐあとだけ。おなじばめんが3かい、ポーンもうごかずこまもとらず50て、こまがたりない、ステイルメイト、ふたりがOKしたときはひきわけになるよ。'}
};
export function mountChessLearn(host,{locale,progress=0,onProgress,onClose}){
  const t=copy[locale]||copy.en;let step=progress>=lessons.length?0:Math.min(progress,lessons.length-1),chess,selected='',solved=false,mistakes=0,message='';
  const squares=()=>Array.from({length:64},(_,i)=>`${'abcdefgh'[i%8]}${8-Math.floor(i/8)}`);
  function reset(){const lesson=lessons[step];chess=new Chess(lesson.fen||undefined);selected='';solved=false;mistakes=0;message='';render();}
  function render(){const lesson=lessons[step],legal=selected?chess.moves({square:selected,verbose:true}).map(m=>m.to):[];
    host.innerHTML=`<section class="panel learn-panel chess-lesson"><div class="learn-top"><strong>♟ ${t.title}</strong><button data-chess-learn="close">${t.close}</button></div><p class="eyebrow">${t.progress} ${step+1} / ${lessons.length}</p><h2>${t.names[step][0]}</h2><p>${t.names[step][1]}</p><div class="chess-tutorial-scroll"><div class="chess-board tutorial-board">${squares().map(square=>{const p=chess.get(square);return `<button data-learn-square="${square}" class="${selected===square?'selected':''} ${legal.includes(square)?'legal':''}" aria-label="${square}">${p?`<span>${pieces[p.color+p.type]}</span>`:''}</button>`;}).join('')}</div></div><p class="learn-feedback" role="status">${message}</p>${solved&&step===lessons.length-1?`<p>${t.end}</p>`:''}<div class="actions"><button data-chess-learn="back" ${step===0?'disabled':''}>${t.back}</button><button data-chess-learn="reset">${t.again}</button><button class="primary" data-chess-learn="next" ${!solved?'disabled':''}>${step===lessons.length-1?t.done:t.next}</button></div></section>`;
  }
  host.onclick=e=>{const square=e.target.closest('[data-learn-square]')?.dataset.learnSquare;if(square&&!solved){const lesson=lessons[step];if(!selected){if(chess.get(square)?.color==='w'){selected=square;message='';}else{mistakes++;message=mistakes>1?t.hint:t.retry;}}
      else{let move=null;try{move=chess.move({from:selected,to:square,promotion:lesson.promotion||'q'});}catch{}if(move&&selected===lesson.from&&square===lesson.to&&(!lesson.check||chess.isCheck())&&(!lesson.mate||chess.isCheckmate())){solved=true;message=t.good;onProgress(step+1);}else{if(move)chess.undo();mistakes++;message=mistakes>1?t.hint:t.retry;}selected='';}render();return;}
    const action=e.target.closest('[data-chess-learn]')?.dataset.chessLearn;if(action==='close')onClose();if(action==='reset')reset();if(action==='back'&&step){step--;reset();}if(action==='next'&&solved){if(step===lessons.length-1)onClose();else{step++;reset();}}};
  reset();return()=>{host.onclick=null;host.replaceChildren();};
}
