import { boardFromFen, legalMoves, createChessGame, playChess, chessPgn } from './ChessRules.mjs';
import { chessText } from './ChessText.mjs';
import { playroomText } from './PlayroomText.mjs';
import { createPlayroom } from './PlayroomUI.mjs';
import { mountChessLearn } from './ChessLearn.mjs';
import { AuthManager } from '../auth/AuthManager.js';
import { hasParentalAck, requireParentalGate } from '../privacy/ParentalGate.mjs';

const app=document.querySelector('#app'),notice=document.querySelector('#notice'),params=new URLSearchParams(location.search);
const playroomHost=document.querySelector('#playroom');if(playroomHost)playroomHost.hidden=true;if(app)app.hidden=false;
let locale=params.get('lang')||(navigator.language.startsWith('zh')?'zh':navigator.language.startsWith('ja')?'ja':'en');if(!chessText[locale])locale='en';
let room=null,identity=null,busy=false,socket=null,reconnectTimer=null,connectionEpoch=0,reconnectAttempt=0,connected=false,alive=true,pendingRoom=params.get('room'),recent=[],review=null,selected='',promotion=null,offset=0,followingRoom=null;
const pieces={wk:'♔',wq:'♕',wr:'♖',wb:'♗',wn:'♘',wp:'♙',bk:'♚',bq:'♛',br:'♜',bb:'♝',bn:'♞',bp:'♟'};
const auth=new AuthManager({turnstileSiteKey:document.querySelector('meta[name="turnstile-site-key"]').content});
const t=()=>({...playroomText[locale],...chessText[locale]}),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(action,label,cls='',disabled=false)=>`<button type="button" data-chess="${action}" class="${cls}" ${disabled?'disabled':''}>${esc(t()[label]??playroomText[locale][label])}</button>`;
function message(value=''){notice.textContent=value;}
async function api(path,body){const response=await fetch(`/api/arena/${path}`,{method:body===undefined?'GET':'POST',credentials:'include',headers:body===undefined?{}:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(12000)});let data;try{data=await response.json();}catch{throw new Error('UNAVAILABLE');}if(!response.ok||data.error){const error=new Error(data.error||'UNAVAILABLE');error.roomId=data.roomId;throw error;}return data;}
function showError(error){message(t().errors[error.message]||playroomText[locale].errors[error.message]||t().errors.TRY_LATER);}
async function run(fn){if(busy)return;busy=true;render();try{await fn();}catch(error){showError(error);if(error.message==='STALE'&&room)try{update(await api(`chess/rooms/${room.id}`));}catch{}}finally{busy=false;render();}}
function update(next){if(room&&room.id===next.id&&next.revision<room.revision)return;room=next;offset=next.now-Date.now();selected='';promotion=null;render();if(next.nextRoom&&followingRoom!==next.nextRoom){followingRoom=next.nextRoom;void api(`chess/rooms/${next.nextRoom}`).then(fresh=>{if(room?.id===next.id)enter(fresh);}).catch(showError).finally(()=>followingRoom=null);}}
function disconnect(){connectionEpoch++;clearTimeout(reconnectTimer);reconnectTimer=null;if(socket){socket.onclose=null;socket.close();socket=null;}connected=false;}
function connect(){disconnect();if(!room||!alive||room.phase==='expired')return;const epoch=connectionEpoch,id=room.id,url=new URL(`/api/arena/chess/rooms/${id}/socket`,location.origin);url.protocol=location.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(url);socket.onopen=()=>{connected=true;reconnectAttempt=0;renderConnection();};socket.onmessage=event=>{if(event.data==='pong'||epoch!==connectionEpoch)return;try{update(JSON.parse(event.data));}catch{message(t().errors.TRY_LATER);}};socket.onerror=()=>{connected=false;renderConnection();};socket.onclose=event=>{if(epoch!==connectionEpoch||!alive)return;connected=false;renderConnection();if(event.code===4001)return message(t().errors.LOGIN_REQUIRED);if(room&&room.phase!=='expired')reconnectTimer=setTimeout(async()=>{try{update(await api(`chess/rooms/${id}`));connect();}catch(error){showError(error);connect();}},Math.min(15000,1000*2**reconnectAttempt++));};}
function enter(next){disconnect();room=null;review=null;pendingRoom=null;update(next);history.replaceState(null,'',`/arena.html?game=chess&room=${next.id}&lang=${locale}`);connect();}
async function action(type,extra={}){update(await api(`chess/rooms/${room.id}`,{type,revision:room.revision,...extra}));}
async function openGame(type,id,prefetched){if(type==='chess'){if(id)return enter(prefetched||await api(`chess/rooms/${id}`));document.querySelector('.chess-lobby')?.scrollIntoView({behavior:'smooth'});return;}location.href=`/arena.html?lang=${locale}${id?`&room=${id}`:''}`;}
function currentGame(){if(!review)return room?.game;let game=createChessGame(review.game.startFen);for(const move of review.game.moves.slice(0,review.step))game=playChess(game,move.from,move.to,move.promotion||'q');return game;}
function chessBoard(game,disabled=false){const cells=boardFromFen(game.fen),base=Array.from({length:64},(_,i)=>`${'abcdefgh'[i%8]}${8-Math.floor(i/8)}`),squares=room?.seat===2&&!review?[...base].reverse():base,legal=selected?legalMoves(game,selected).map(m=>m.to):[];return `<div class="chess-board ${room?.seat===2&&!review?'black-view':''}" role="grid" aria-label="Chess board">${squares.map(square=>{const file=square.charCodeAt(0)-97,rank=Number(square[1]),piece=cells[base.indexOf(square)],last=game.moves.at(-1);return `<button type="button" role="gridcell" data-square="${square}" class="${(file+rank)%2?'light':'dark'} ${selected===square?'selected':''} ${legal.includes(square)?'legal':''} ${last&&(last.from===square||last.to===square)?'last-square':''}" aria-label="${square}${piece?` ${piece.color==='w'?t().white:t().black}`:''}" ${disabled?'disabled':''}>${piece?`<span class="chess-piece ${piece.color==='w'?'white-piece':'black-piece'}">${pieces[piece.color+piece.type]}</span>`:''}</button>`;}).join('')}</div>`;}
function clocks(){if(!room)return;for(const el of document.querySelectorAll('[data-chess-clock]')){const seat=Number(el.dataset.chessClock),elapsed=room.phase==='playing'&&room.game.turn===seat?Date.now()+offset-room.turnAt:0,seconds=Math.max(0,Math.ceil((room.remaining[seat-1]-elapsed)/1000));el.textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}}
function resultHTML(result){if(!result)return'';return result.winner?`<p class="result">${result.winner===1?t().white:t().black} ${t().win}</p><p>${esc(t().reasons[result.reason])}</p>`:`<p class="result">${t().draw}</p><p>${esc(t().reasons[result.reason])}</p>`;}
function lobby(){return `<section class="chess-lobby"><div class="game-zone-header"><div class="game-zone-title-group"><span class="kid-tag">♔♚ 国际象棋专区</span><h2 class="go-section-title">${esc(playroomText[locale].chessTitle || t().title)}</h2></div><button type="button" class="back-to-hub-btn" data-chess="back-hub">${esc(playroomText[locale].backToHub || '⬅ 返回游戏大厅')}</button></div><p class="kid-sub-desc">${esc(playroomText[locale].chessDesc || t().subtitle)}</p><div class="cards"><article class="card kid-mode-card"><div class="kid-mode-top"><span class="icon">♔</span><span class="kid-mode-badge">${locale==='zh'?'亲友对弈':locale==='ja'?'ともだちと':'Play Friends'}</span></div><h2>${t().invite}</h2><p>${t().inviteDesc}</p>${button('create','create','primary',busy||!identity)}</article><article class="card kid-mode-card"><div class="kid-mode-top"><span class="icon">↔</span><span class="kid-mode-badge">${locale==='zh'?'在线寻找':locale==='ja'?'マッチング':'Quick Match'}</span></div><h2>${t().match}</h2><p>${t().matchDesc}</p>${button('match','match','primary',busy||!identity)}</article><article class="card kid-mode-card"><div class="kid-mode-top"><span class="icon">🎓</span><span class="kid-mode-badge">${locale==='zh'?'规则入门':locale==='ja'?'ルール':'Tutorial'}</span></div><h2>${esc(t().chessLearn || '国际象棋小课堂')}</h2><p>${esc(t().chessLearnHint || '认识棋子与走法，学会将军与将死。')}</p><p><span class="kid-progress-badge">${esc(t().progress || '已完成')} ${identity?.tutorials?.chess || 0} / 8</span></p><button type="button" data-chess="learn" data-pr="learn-chess" class="primary kid-action-btn">🚀 ${esc(t().chessLearn || '开始学习')}</button></article></div><div class="panel join-panel"><div class="card-eyebrow-row"><span class="kid-tag">🔑 ${locale==='zh'?'房间号码':locale==='ja'?'へやのコード':'Room Code'}</span></div><form id="chess-join" class="join"><input name="code" required aria-label="${t().code}" placeholder="${t().code}"><button>${t().join}</button></form></div><details class="kid-history-details"><summary>📜 ${t().history}</summary><p class="muted">${t().noHistory}</p><div class="history">${recent.map((entry,i)=>`<button data-chess-history="${i}">${esc(new Date(entry.finished_at).toLocaleDateString(locale))} · ${t().replay}</button>`).join('')}</div></details></section>`;}
function render(){document.documentElement.lang=locale;document.querySelector('#locale').value=locale;document.querySelector('#title').textContent='Piko Playroom';document.querySelector('.intro .eyebrow').textContent=room?'CHESS · ♔ ♚':'PLAY · CONNECT · LEARN';document.querySelector('#subtitle').textContent=room?t().subtitle:playroomText[locale].tagline;document.querySelector('#login').textContent=identity?.authenticated?(locale==='zh'?'已登录':locale==='ja'?'ログイン中':'Signed in'):(locale==='zh'?'登录保存战绩':locale==='ja'?'ログインして記録':'Sign in to save');document.querySelector('#login').hidden=!!room;
  if(review){const game=currentGame();app.innerHTML=`<div class="table-layout"><section>${chessBoard(game,true)}</section><aside class="panel"><h2>${t().replay}</h2><p>${review.step} / ${review.game.moves.length} ${t().moves}</p><input type="range" id="chess-review" min="0" max="${review.game.moves.length}" value="${review.step}"><div class="actions">${button('review-back',room?'live':'home')}${button('export','export')}</div></aside></div>`;}
  else if(!room)app.innerHTML=pendingRoom?`<section class="panel"><h2>${t().invite}</h2><p class="room-code">${esc(pendingRoom)}</p><div class="actions">${button('join-link','join','primary')}${button('home','home')}</div></section>`:lobby();
  else{const game=room.game,yourTurn=room.phase==='playing'&&room.seat===game.turn,drawFrom=game.drawOffer;app.innerHTML=`<div class="table-layout"><section><div class="players">${[1,2].map(seat=>`<div class="player ${room.phase==='playing'&&game.turn===seat?'active':''}"><strong>${seat===1?'♔':'♚'} ${seat===1?t().white:t().black}${room.seat===seat?` · ${t().you}`:''}</strong><small>${room.players[seat-1]?`${esc(room.players[seat-1].avatar)} ${esc(room.players[seat-1].name)}`:t().empty}</small><span class="clock" data-chess-clock="${seat}"></span></div>`).join('')}</div>${chessBoard(game,busy||!yourTurn)}<p class="preview-note">${game.check?t().check:yourTurn?t().turn:room.phase==='playing'?t().notTurn:''}</p>${promotion?`<div class="promotion panel"><strong>${t().promotion}</strong><div class="actions">${[['q','queen'],['r','rook'],['b','bishop'],['n','knight']].map(([value,label])=>`<button data-promotion="${value}">${pieces[(room.seat===1?'w':'b')+value]} ${t()[label]}</button>`).join('')}</div></div>`:''}</section><aside class="panel"><h2>${t()[room.phase==='ready'?'readyPhase':room.phase]}</h2><p id="connection" class="status"></p>${room.phase==='ready'?button('ready',room.players[room.seat-1]?.ready?'readyDone':'ready','primary',busy||room.players[room.seat-1]?.ready):''}${room.phase==='waiting'?`<p>${t().inviteDesc}</p><div class="actions">${button('copy','copy')}${navigator.share?button('share','share'):''}</div><p class="room-code">${room.id}</p>${button('cancel','cancel')}`:''}${drawFrom&&drawFrom!==room.seat&&room.phase==='playing'?`<p>${t().drawOffer}</p><div class="actions">${button('accept-draw','acceptDraw','primary')}${button('decline-draw','declineDraw')}</div>`:drawFrom===room.seat?`<p>${t().drawWait}</p>`:''}${resultHTML(game.result)}${room.phase==='playing'?`<div class="actions">${!drawFrom?button('offer-draw','offerDraw'):''}${button('resign','resign','danger')}</div>`:''}${room.phase==='finished'?`<div class="actions">${button('rematch',room.nextRoom?'nextGame':'rematch','primary')}${room.rematchVotes.includes(room.seat)&&!room.nextRoom?`<p>${t().rematchWait}</p>${button('rematch-cancel','cancelRematch')}`:''}</div>`:''}<hr><div class="actions">${game.moves.length?button('review','replay'):''}${game.moves.length?button('export','export'):''}${button('home','home')}</div></aside></div>`;}
  if(room?.phase==='finished'&&room.rematchVotes.some(seat=>seat!==room.seat)&&!room.nextRoom){const actions=app.querySelector('[data-chess=rematch]')?.parentElement;actions?.insertAdjacentHTML('beforebegin',`<p>${esc(t().rematchOffer)}</p>`);}
  app.innerHTML+=`<details><summary>${t().rules}</summary><p>${t().rulesText}</p></details>`;renderConnection();clocks();playroom.render();}
function renderConnection(){const el=document.querySelector('#connection');if(el)el.textContent=['finished','expired'].includes(room?.phase)?'':connected?t().connected:t().reconnecting;}
async function start(mode){if(mode==='match'){const ok=hasParentalAck()||await requireParentalGate({purpose:'arena-match',locale});if(!ok){message(t().parentGateNeeded||'Parent approval required for public matchmaking.');return;}}const next=await api(mode==='match'?'chess/match':'chess/rooms',{mode,parentalGateAck:hasParentalAck()||mode!=='match'});message();enter(next);}
async function home(){if(room?.phase==='playing'&&!confirm(t().leaveAsk))return;if(room&&['waiting','ready'].includes(room.phase)){await api('chess/match/cancel',{});await action('cancel');}const family=room?.family;disconnect();room=null;review=null;pendingRoom=null;history.replaceState(null,'',`/arena.html?game=chess&lang=${locale}`);message();await playroom.restoreFamily(family);if(identity?.authenticated)recent=(await api('chess/history')).entries;render();}
app.addEventListener('click',event=>{const square=event.target.closest('[data-square]');if(square&&!square.disabled&&room){const value=square.dataset.square,cells=boardFromFen(room.game.fen),base=Array.from({length:64},(_,i)=>`${'abcdefgh'[i%8]}${8-Math.floor(i/8)}`),piece=cells[base.indexOf(value)],own=piece&&piece.color===(room.seat===1?'w':'b');if(!selected){if(own){selected=value;render();}}else if(own){selected=value;promotion=null;render();}else{const promotions=legalMoves(room.game,selected).filter(m=>m.to===value&&m.promotion);if(promotions.length){promotion={from:selected,to:value};render();}else void run(()=>action('move',{from:selected,to:value}));}return;}const promotionButton=event.target.closest('[data-promotion]');if(promotionButton&&promotion){const move=promotion;void run(()=>action('move',{...move,promotion:promotionButton.dataset.promotion}));return;}const historyButton=event.target.closest('[data-chess-history]');if(historyButton){const entry=recent[Number(historyButton.dataset.chessHistory)];review={game:JSON.parse(entry.game_json),step:0};render();return;}const actionName=event.target.closest('[data-chess]')?.dataset.chess || (event.target.closest('[data-pr=learn-chess]') ? 'learn' : null);if(!actionName)return;void run(async()=>{if(actionName==='back-hub'){location.href=`/arena.html?lang=${locale}`;return;}if(actionName==='learn'){const learning=document.querySelector('#learn-room');const lessonClose=mountChessLearn(learning,{locale,progress:identity?.tutorials?.chess||0,onProgress:step=>{if(identity)identity.tutorials={...identity.tutorials,chess:Math.max(identity.tutorials?.chess||0,step)};if(identity?.configured)void api('tutorial',{game:'chess',step}).catch(showError);},onClose:()=>{lessonClose?.();learning.hidden=true;app.hidden=false;render();}});learning.hidden=false;app.hidden=true;learning.scrollIntoView({block:'start',behavior:'smooth'});return;}if(actionName==='create'||actionName==='match')return start(actionName==='match'?'match':'invite');
if(actionName==='join-link')return enter(await api(`chess/rooms/${pendingRoom}`,{type:'join'}));if(actionName==='ready')return action('ready');if(actionName==='resign'){if(confirm(t().resignAsk))await action('resign');return;}if(actionName==='offer-draw')return action('offer_draw');if(actionName==='accept-draw')return action('accept_draw');if(actionName==='decline-draw')return action('decline_draw');if(actionName==='rematch'){if(room.nextRoom)return enter(await api(`chess/rooms/${room.nextRoom}`));return action('rematch');}if(actionName==='rematch-cancel')return action('rematch',{accept:false});if(actionName==='copy'||actionName==='share'){const url=`${location.origin}/arena.html?game=chess&room=${room.id}&lang=${locale}`;if(actionName==='share'){try{await navigator.share({title:t().title,url});}catch(error){if(error.name!=='AbortError')throw error;}}else try{await navigator.clipboard.writeText(url);message(t().copied);}catch{message(url);}return;}if(actionName==='cancel'||actionName==='home')return home();if(actionName==='review'){review={game:structuredClone(room.game),step:room.game.moves.length};render();return;}if(actionName==='review-back'){review=null;render();return;}if(actionName==='export'){const game=review?.game||room.game,url=URL.createObjectURL(new Blob([chessPgn(game)],{type:'application/x-chess-pgn'})),a=document.createElement('a');a.href=url;a.download='piko-chess.pgn';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});});
app.addEventListener('submit',event=>{if(event.target.id!=='chess-join')return;event.preventDefault();let id=new FormData(event.target).get('code').trim();try{id=new URL(id).searchParams.get('room');}catch{}void run(async()=>{if(!/^[a-f0-9-]{36}$/.test(id))throw new Error('ROOM_NOT_FOUND');enter(await api(`chess/rooms/${id}`,{type:'join'}));});});
app.addEventListener('input',event=>{if(event.target.id==='chess-review'){review.step=Number(event.target.value);render();}});
document.querySelector('#locale').onchange=event=>{locale=event.target.value;render();};document.querySelector('#login').onclick=()=>{if(!identity?.authenticated)void auth.showLogin();};
const playroom=createPlayroom({api,getLocale:()=>locale,getIdentity:()=>identity,setIdentity:next=>identity=next,getRoom:()=>room,openGame,onError:showError,headless:true});
async function initialize(){message(locale==='zh'?'正在连接…':locale==='ja'?'つないでいます…':'Connecting…');try{identity=await api('identity',{});await playroom.initialize();if(pendingRoom&&/^[a-f0-9-]{36}$/.test(pendingRoom)){try{enter(await api(`chess/rooms/${pendingRoom}`));}catch(error){if(!['NOT_PLAYER','ROOM_NOT_FOUND'].includes(error.message))showError(error);}}if(identity.authenticated)recent=(await api('chess/history')).entries;message();}catch(error){showError(error);}render();}
const timer=setInterval(()=>{clocks();},500),heartbeat=setInterval(()=>{if(socket?.readyState===WebSocket.OPEN)socket.send('ping');},25000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&room)void run(async()=>{update(await api(`chess/rooms/${room.id}`));connect();});});window.addEventListener('pagehide',()=>{alive=false;disconnect();clearInterval(timer);clearInterval(heartbeat);playroom.dispose();},{once:true});render();void initialize();
