export const playroomText = {
 zh: {
   tagline:'一起玩，再来一局。',
   hubTitle:'趣味棋类乐园',
   hubDesc:'选一个喜欢的棋盘游戏，开始今天的智慧大冒险吧！',
   goTitle:'围棋大冒险',
   goBadge:'黑白吃子 · 争地盘',
   goDesc:'落子、吃子、围地盘！锻炼超强思维力，新手小棋盘和大棋盘都能玩。',
   chessTitle:'国际象棋城堡',
   chessBadge:'骑士王后 · 益智对决',
   chessDesc:'认识国王、王后与战马，巧妙运子，吃掉对方的国王吧！',
   playGo:'进入围棋大冒险 ➔',
   playChess:'进入国际象棋城堡 ➔',
   backToHub:'⬅ 返回游戏大厅',
   playerCard:'小棋手名片',
   changeAvatar:'修改形象',
   chooseAvatar:'选个喜欢的萌宠头像：',
   namePlaceholder:'输入威风的小棋手名字',
   guestBadge:'临时游客身份',
   guestTip:'已为你分配临时游客身份，免填即可畅玩！随时可点击修改。',
   guestPlay:'直接进入',
   onlineLobbyTitle:'在线大厅',
   onlineLobbyDesc:'这里能看到所有正在 Playroom 乐园里的小伙伴，快来找人对局吧！',
   profile:'我的昵称',
   name:'昵称（最多20字）',
   avatar:'头像',
   visible:'在公共在线名单中显示我',
   privacy:'家庭房间仅成员可见。请用昵称，不必填写真实姓名。',
   parentGateHint:'公开名单与陌生人匹配需要家长确认。默认关闭。',
   parentGateNeeded:'需要家长确认后才能公开显示。',
   report:'举报',
   block:'拉黑',
   reported:'已提交举报',
   blocked:'已拉黑',
   save:'保存',
   saved:'已保存',
   family:'家庭 / 朋友房间',
   createFamily:'创建房间',
   familyHint:'分享链接，邀请家人和朋友。最多8人同桌，每局围棋选择2人。',
   joinFamily:'加入房间',
   code:'家庭房间码或链接',
   members:'同桌伙伴',
   online:'在线',
   offline:'暂时离线',
   idle:'大厅中',
   waiting:'等待开局',
   playing:'围棋对局中',
   public:'在线伙伴',
   empty:'暂时没有公开在线的伙伴。可以分享家庭房间链接一起玩。',
   invite:'邀请',
   incoming:'邀请你一起玩',
   accepted:'邀请已接受',
   accept:'接受',
   decline:'拒绝',
   openFamily:'进入家庭房间',
   copy:'复制家庭邀请',
   copied:'邀请链接已复制',
   leave:'离开家庭房间',
   ready:'准备 / 取消准备',
   readyDone:'已准备',
   notReady:'未准备',
   host:'房主',
   seats:'选择本局两位玩家',
   settings:'保存本局设置',
   start:'开始新局',
   enter:'进入本局',
   backFamily:'回到家庭房间',
   go:'围棋',
   learn:'新手学堂',
   learnHint:'从落子、气、提子到围地，动手学会第一局。',
   progress:'已完成',
   rematch:'再来一局',
   rematchWait:'已邀请再战，等待对方。',
   rematchOffer:'对方想再来一局。',
   cancelRematch:'取消再战请求',
   nextGame:'进入下一局',
   rematchHint:'双方同意后交换黑白，立即开始新局。旧棋谱会保留。',
   refresh:'刷新名单',
   privateRoom:'私密房间',
   leaveAsk:'离开家庭房间？正在进行的棋局不会结束。',
   errors:{INVALID_NAME:'请填写1至20字的昵称，并选择头像。',PROFILE_REQUIRED:'先保存一个昵称，就能和大家一起玩。',FAMILY_NOT_FOUND:'家庭房间不存在或已过期。',NOT_MEMBER:'请通过邀请链接加入家庭房间。',HOST_ONLY:'这一步由房主操作。',FAMILY_STALE:'房间已更新，请再试一次。',NOT_READY:'请选两位在线玩家，并等待他们都准备好。',GAME_ACTIVE:'上一局还在进行，请先完成或认输。',PLAYER_UNAVAILABLE:'对方目前不方便接受邀请。',INVITE_EXPIRED:'邀请已过期。',DIRECTORY_FULL:'在线名单暂时已满，家庭房间仍可使用。',INTERNAL_ERROR:'连接暂时不稳定，请刷新后再试。',UNAVAILABLE:'暂时无法连接游戏服务，请稍后再试。'}
 },
 en: {
   tagline:'Play together. One more round.',
   hubTitle:'Board Game Playground',
   hubDesc:'Pick a board game and jump into a fun brain adventure!',
   goTitle:'Go Adventure',
   goBadge:'Stones & Territory',
   goDesc:'Place stones, capture, and surround territory! Play on 9×9 or 19×19 boards.',
   chessTitle:'Chess Castle',
   chessBadge:'Knights & Kings',
   chessDesc:'Master knights, queens, and pawns to checkmate the king!',
   playGo:'Play Go ➔',
   playChess:'Play Chess ➔',
   backToHub:'⬅ Back to Lobby',
   playerCard:'My Player Badge',
   changeAvatar:'Change',
   chooseAvatar:'Choose your favorite avatar:',
   namePlaceholder:'Enter your player nickname',
   guestBadge:'Guest ID',
   guestTip:'Temporary guest ID assigned! You can play right away without typing.',
   guestPlay:'Play Directly',
   onlineLobbyTitle:'Online Lobby',
   onlineLobbyDesc:'See all players currently in the Piko Playroom and invite them to play!',
   profile:'My nickname',
   name:'Nickname (up to 20 characters)',
   avatar:'Avatar',
   visible:'Show me in the public online list',
   privacy:'Family rooms are visible to members only. Use a nickname; a real name is not needed.',
   parentGateHint:'Public lists and stranger matchmaking need a parent check. Off by default.',
   parentGateNeeded:'A parent must approve before you appear publicly.',
   report:'Report',
   block:'Block',
   reported:'Report submitted',
   blocked:'Blocked',
   save:'Save',
   saved:'Saved',
   family:'Family & friends',
   createFamily:'Create a room',
   familyHint:'Share a link with your people. Up to 8 members; choose 2 players for each Go game.',
   joinFamily:'Join room',
   code:'Family room code or link',
   members:'At the table',
   online:'Online',
   offline:'Away',
   idle:'In the lobby',
   waiting:'Waiting to play',
   playing:'Playing Go',
   public:'Online players',
   empty:'No public players right now. Share a family room link to play together.',
   invite:'Invite',
   incoming:'invites you to play',
   accepted:'Invitation accepted',
   accept:'Accept',
   decline:'Decline',
   openFamily:'Open family room',
   copy:'Copy family invite',
   copied:'Invitation copied',
   leave:'Leave family room',
   ready:'Ready / undo ready',
   readyDone:'Ready',
   notReady:'Not ready',
   host:'Host',
   seats:'Choose two players',
   settings:'Save game settings',
   start:'Start a new game',
   enter:'Open current game',
   backFamily:'Back to family room',
   go:'Go',
   learn:'Learn to play',
   learnHint:'Place stones, find liberties, capture and surround. Learn by trying.',
   progress:'Completed',
   rematch:'Play again',
   rematchWait:'Rematch requested. Waiting for your opponent.',
   rematchOffer:'Your opponent wants another game.',
   cancelRematch:'Cancel rematch request',
   nextGame:'Open next game',
   rematchHint:'Both agree, swap colors, and start immediately. Your old record stays safe.',
   refresh:'Refresh players',
   privateRoom:'Private room',
   leaveAsk:'Leave this family room? Your current game will continue.',
   errors:{INVALID_NAME:'Choose an avatar and a nickname of 1–20 characters.',PROFILE_REQUIRED:'Save a nickname to play together.',FAMILY_NOT_FOUND:'Family room not found or expired.',NOT_MEMBER:'Join using a family invitation.',HOST_ONLY:'Only the host can do this.',FAMILY_STALE:'The room changed. Please try again.',NOT_READY:'Choose two online players and wait for both to be ready.',GAME_ACTIVE:'Finish or resign from the current game first.',PLAYER_UNAVAILABLE:'That player cannot accept an invitation now.',INVITE_EXPIRED:'Invitation expired.',DIRECTORY_FULL:'The public list is full. Family rooms are still available.',INTERNAL_ERROR:'The connection was interrupted. Refresh and try again.',UNAVAILABLE:'The game service is temporarily unavailable. Try again soon.'}
 },
 ja: {
   tagline:'いっしょにあそぼう。もういっかい。',
   hubTitle:'ゲームのひろば',
   hubDesc:'すきなゲームをえらんで、あたまをつかって たのしくあそぼう！',
   goTitle:'いごのぼうけん',
   goBadge:'くろといし・じんとり',
   goDesc:'いしをおいて、あいてのいしをとろう！9マスも19マスもあそべるよ。',
   chessTitle:'チェスのしろ',
   chessBadge:'キングとクイーンのたたかい',
   chessDesc:'こまをうごかして、あいてのキングをおいつめよう！',
   playGo:'いごをあそぶ ➔',
   playChess:'チェスをあそぶ ➔',
   backToHub:'⬅ ひろばにもどる',
   playerCard:'ぼく・わたしのアバター',
   changeAvatar:'えらびなおす',
   chooseAvatar:'すきなアバターをえらんでね：',
   namePlaceholder:'ニックネームをいれてね',
   guestBadge:'ゲストID',
   guestTip:'ゲストIDを用意したよ！名前を入力しなくてもすぐに遊べるよ！',
   guestPlay:'このまま遊ぶ',
   onlineLobbyTitle:'オンラインロビー',
   onlineLobbyDesc:'いまロビーにいるお友だちの一覧だよ。いっしょに対戦しよう！',
   profile:'わたしのニックネーム',
   name:'ニックネーム（20もじまで）',
   avatar:'アバター',
   visible:'みんなのオンラインリストにのせる',
   privacy:'かぞくのへやは、なかまだけにみえます。ほんとうのなまえでなくてもだいじょうぶ。',
   parentGateHint:'こうかいリストや知らない人とのマッチングには保護者の確認が必要です。はじめはオフです。',
   parentGateNeeded:'こうかいにするには保護者の確認が必要です。',
   report:'ほうこく',
   block:'ブロック',
   reported:'ほうこくしました',
   blocked:'ブロックしました',
   save:'ほぞん',
   saved:'ほぞんしました',
   family:'かぞく・ともだちのへや',
   createFamily:'へやをつくる',
   familyHint:'リンクでさそおう。8にんまであつまれます。いごは2にんであそびます。',
   joinFamily:'へやにはいる',
   code:'へやのコード・リンク',
   members:'いっしょにあそぶなかま',
   online:'オンライン',
   offline:'せきをはずしています',
   idle:'ロビーにいます',
   waiting:'じゅんびちゅう',
   playing:'いごでたいせんちゅう',
   public:'オンラインのなかま',
   empty:'いまはこうかいちゅうのなかまがいません。へやのリンクでさそってみよう。',
   invite:'さそう',
   incoming:'からのおさそい',
   accepted:'おさそいがとどきました',
   accept:'いっしょにあそぶ',
   decline:'いまはやめる',
   openFamily:'へやをひらく',
   copy:'しょうたいリンクをコピー',
   copied:'コピーしました',
   leave:'へやをでる',
   ready:'じゅんび / とりけし',
   readyDone:'じゅんびOK',
   notReady:'じゅんびちゅう',
   host:'へやのリーダー',
   seats:'あそぶ2にんをえらぶ',
   settings:'せっていをほぞん',
   start:'あたらしいたいきょく',
   enter:'いまのたいきょくへ',
   backFamily:'かぞくのへやにもどる',
   go:'囲碁',
   learn:'はじめてのいご',
   learnHint:'いしをおく、いきをみつける、いしをとる。ためしながらまなぼう。',
   progress:'できた',
   rematch:'もういっかい',
   rematchWait:'もういっかいのおさそいをおくりました。',
   rematchOffer:'あいてがもういっかいあそびたいそうです。',
   cancelRematch:'おさそいをとりけす',
   nextGame:'つぎのたいきょくへ',
   rematchHint:'ふたりがOKしたら、しろとくろをこうたいしてすぐはじまるよ。まえのきろくはのこります。',
   refresh:'リストをこうしん',
   privateRoom:'なかまだけのへや',
   leaveAsk:'へやをでますか？いまのたいきょくはつづきます。',
   errors:{INVALID_NAME:'1〜20もじのニックネームとアバターをえらんでね。',PROFILE_REQUIRED:'ニックネームをほぞんしてね。',FAMILY_NOT_FOUND:'へやがみつかりません。',NOT_MEMBER:'しょうたいリンクからはいってね。',HOST_ONLY:'へやのリーダーがそうさします。',FAMILY_STALE:'へやがかわりました。もういちどためしてね。',NOT_READY:'オンラインの2にんをえらんで、じゅんびをまってね。',GAME_ACTIVE:'いまのたいきょくをおわらせてね。',PLAYER_UNAVAILABLE:'いまはあいてをさそえません。',INVITE_EXPIRED:'おさそいのじかんがきれました。',DIRECTORY_FULL:'リストがいっぱいです。かぞくのへやはつかえます。',INTERNAL_ERROR:'つうしんがいちどとまりました。ページをこうしんしてね。',UNAVAILABLE:'いまはゲームにつながりません。すこしまってからためしてね。'}
 }
};
