import {PROFILES,SUBJECTS,defaultProfile,profileOptions,yearLabel} from './GradePaths.mjs';
import {readCountry,normalizeCountry,languageForCountry} from '../location/Country.mjs';
import {TEXT} from './WorldText.mjs';
import {FOUNDATION_TEXT} from './FoundationText.mjs';
import {gateUrl,journeyState,readJourneyScores} from './GradeJourney.mjs';

const strings={
 zh:{title:'选择你的学年冒险',intro:'每个年级都有自己的学习地图。选一门学科，从第一关开始收集星星。',profile:'学校学制',choose:'请选择学制',free:'自由选游戏',subjects:{all:'全部地图',math:'数学港',english:'英语挑战岛',coding:'编程基地',art:'图形工坊',music:'节奏花园',language:'语文花园',science:'科学实验室',thinking:'脑力训练舱'},pick:'先选一个年级',empty:'这个年级的学习地图还在准备中。',review:'基础复习',note:'每套学制按自己的学年路径选取学习目标，不把日本题目翻译后冒充本地课程；目前是经过标注的补充练习，尚未覆盖全年课程。',US:'美国各州和学校的课程安排不同，Grade 6 仅在学校适用时选择。',INT:'使用国际通用年级标签，不代表所在国家的正式课程。',start:'进入关卡',back:'重新选择国家',current:'学习星图',progress:'本年级进度',cleared:'关已通过',gate:'关卡',knowledge:'年级任务',action:'操作挑战',locked:'通过上一关解锁',complete:'已通关',open:'可以挑战',map:'年级闯关地图',learning:'学习语言',stages:'小关',englishGoal:'原创英检风格题：词汇、对话、句序与阅读，按 CEFR 逐级进阶。'},
 en:{title:'Choose your school-year adventure',intro:'Every year has its own learning map. Pick a subject, start at Gate 1 and collect stars.',profile:'School system',choose:'Choose a school system',free:'Free play',subjects:{all:'All maps',math:'Number Harbour',english:'English Challenge Isle',coding:'Build & Code',art:'Shape Workshop',music:'Rhythm Garden',language:'Story Sprouts',science:'Wonder Lab',thinking:'Brain Training Bay'},pick:'Choose your year first',empty:'This school-year map is still being prepared.',review:'Foundation review',note:'Each school system selects its own year-level goals. These are labelled supplementary activities, not translated Japanese lessons or a complete certified curriculum.',US:'School structures vary in the US. Choose Grade 6 only if it applies to your primary school.',INT:'General grade labels, rather than a national curriculum.',start:'Enter gate',back:'Change country',current:' adventure map',progress:'Year progress',cleared:'gates cleared',gate:'Gate',knowledge:'Year mission',action:'Hands-on challenge',locked:'Clear the previous gate',complete:'Cleared',open:'Ready',map:'School-year quest map',learning:'Learning language',stages:'stages',englishGoal:'Original EIKEN-style vocabulary, dialogue, word-order and reading tasks with progressive CEFR labels.'},
 ja:{title:'がくねんの ぼうけんを えらぼう',intro:'がくねんごとの マップで、きょうかの 1ばんめの かんもんから ほしを あつめよう。',profile:'がっこうの しくみ',choose:'えらんでね',free:'ゲームを えらぶ',subjects:{all:'ぜんぶの マップ',math:'かずの みなと',english:'英語チャレンジの しま',coding:'プログラムきち',art:'かたちこうぼう',music:'リズムガーデン',language:'ことばの もり',science:'ふしぎラボ',thinking:'のうトレきち'},pick:'がくねんを えらぼう',empty:'この がくねんの マップは じゅんび中だよ。',review:'きほんの ふくしゅう',note:'それぞれの がっこうの しくみに あわせた もくひょうを えらんでいます。にほんの もんだいの ほんやくではなく、いまは ほじょ れんしゅうです。',US:'Grade 6は がっこうに あわせて えらんでね。',INT:'くにの きょういくかていではなく、きほんの れんしゅうです。',start:'かんもんへ',back:'くにを えらびなおす',current:'の ぼうけんマップ',progress:'がくねんの きろく',cleared:'こ クリア',gate:'かんもん',knowledge:'がくねんミッション',action:'そうさゲーム',locked:'まえの かんもんを クリア',complete:'クリア',open:'ちょうせんできる',map:'がくねん かんもんマップ',learning:'まなぶ ことば',stages:'ステージ',englishGoal:'CEFRの めやすで すすむ、オリジナルの 英検ふう語彙・会話・語順・読解もんだい。'}
};
const params=new URLSearchParams(location.search);let storage;try{storage=localStorage;}catch{}
const country=normalizeCountry(params.get('country'))||readCountry(storage),locale=['en','zh','ja'].includes(params.get('locale'))?params.get('locale'):languageForCountry(country),w=strings[locale],names=TEXT[locale],fw=FOUNDATION_TEXT[locale];
const allowed=profileOptions(country);let saved;try{saved=JSON.parse(storage.getItem(`piko-grade-${country||'INT'}`));}catch{}
let profile=params.get('curriculum')||saved?.profile||defaultProfile(country)||'',year=params.get('year')||saved?.year||'',subject='all';
if(!allowed.includes(profile))profile='';if(!PROFILES[profile]?.years.includes(year))year='';
const app=document.querySelector('#grade-app'),icons=['🌱','🪁','🚀','🌈','🪐','⭐','🌻','🧭','🎈'];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const gateArt={circuit:'🔌',sudoku:'▦',code:'🔐',set:'◈',balance:'⚖️',order:'🚉',water:'💧',network:'⚡'};
const subjectArt={math:'🔢',english:'🔤',language:'📖',science:'🔬',coding:'🤖',art:'🎨',music:'🎵',thinking:'🧠'};
document.documentElement.lang=locale;document.title=`Piko Play · ${w.title}`;
document.querySelector('#free-play').textContent=w.free;document.querySelector('#free-play').href=`world.html${country?`?country=${country}`:''}`;

function save(){try{storage.setItem(`piko-grade-${country||'INT'}`,JSON.stringify({profile,year}));}catch{}const q=new URLSearchParams();if(country)q.set('country',country);if(profile)q.set('curriculum',profile);if(year)q.set('year',year);q.set('locale',locale);history.replaceState(null,'',`grades.html?${q}`);}
function scoreSummary(targetYear){const scores=readJourneyScores(storage,profile,targetYear,locale),gates=journeyState(profile,targetYear,scores);return {done:gates.filter(gate=>gate.complete).length,total:gates.length};}
function gateName(gate){return gate.kind==='lesson'?gate.title[locale]:names.games[gate.game][0];}
function gateObjective(gate){return gate.kind==='lesson'?(gate.subject==='english'?w.englishGoal:gate.subject==='language'?`${w.learning}: ${gate.learningLanguage==='zh'?'中文':'English'}`:fw.intro):gate.skill[locale];}
function renderWorld(subjectId,gates){
 const done=gates.filter(gate=>gate.complete).length;
 const series=[...new Map(gates.map(gate=>[gate.seriesId||gate.id,[]])).entries()].map(([id])=>gates.filter(gate=>(gate.seriesId||gate.id)===id));
 return `<section class="quest-world world-${subjectId}" aria-labelledby="world-${subjectId}"><div class="quest-world-head"><div class="world-title"><span aria-hidden="true">${subjectArt[subjectId]}</span><div><p>${w.map}</p><h3 id="world-${subjectId}">${escape(w.subjects[subjectId])}</h3></div></div><strong>${done} / ${gates.length} ${w.cleared}</strong></div><div class="journey-track">${series.map((group,index)=>{
  const gate=group[0],seriesDone=group.filter(item=>item.complete).length,open=group.some(item=>item.unlocked),complete=seriesDone===group.length,status=complete?w.complete:open?w.open:w.locked;
  const stages=group.map(item=>{const label=`${w.gate} ${item.stage}`;if(!item.unlocked)return`<button class="gate-stage is-locked" type="button" disabled aria-label="${escape(label)} · ${escape(w.locked)}"><span>${item.stage}</span><b aria-hidden="true">🔒</b></button>`;const href=gateUrl(item,{profile,year,country,locale});return`<a class="gate-stage ${item.complete?'is-complete':'is-open'}" href="${escape(href)}" aria-label="${escape(label)} · ${escape(item.complete?w.complete:w.open)}"><span>${item.stage}</span><b aria-hidden="true">${item.complete?'✓':'▶'}</b></a>`;}).join('');
  return `<article class="journey-gate gate-series ${complete?'is-complete':open?'is-open':'is-locked'}"><div class="gate-orbit" aria-hidden="true"><span>${gate.kind==='game'?gateArt[gate.game]:subjectArt[gate.subject]}</span></div><div class="gate-copy"><p class="gate-number">${gate.kind==='game'?w.action:w.knowledge} ${index+1}</p><h4>${escape(gateName(gate))}</h4><p>${escape(gateObjective(gate))}</p>${gate.review?`<span class="review-tag">${w.review}</span>`:''}<span class="gate-status">${seriesDone} / ${group.length} ${w.stages} · ${escape(status)}</span><div class="gate-stage-grid">${stages}</div></div></article>`;
 }).join('')}</div></section>`;
}
function render(){
 const allScores=year?readJourneyScores(storage,profile,year,locale):{},allGates=year?journeyState(profile,year,allScores):[],shown=subject==='all'?allGates:journeyState(profile,year,allScores,subject),summary={done:allGates.filter(gate=>gate.complete).length,total:allGates.length};
 const worlds=[...new Set(shown.map(gate=>gate.subject))].map(subjectId=>renderWorld(subjectId,shown.filter(gate=>gate.subject===subjectId))).join('');
 app.innerHTML=`<a class="grade-return" href="index.html">← ${w.back}</a><section class="grade-hero"><div><p class="eyebrow">PIKO PLAY · GRADE QUEST</p><h1>${w.title}</h1><p>${w.intro}</p></div><div class="grade-hero-planet" aria-hidden="true">🪐</div></section><div class="grade-controls"><label for="school-system">${w.profile}<select id="school-system"><option value="">${w.choose}</option>${allowed.map(id=>`<option value="${id}" ${id===profile?'selected':''}>${escape(PROFILES[id].names[locale])}</option>`).join('')}</select></label></div>${PROFILES[profile]?.note?`<p class="grade-note">${w[PROFILES[profile].note]}</p>`:''}<div class="year-grid">${(PROFILES[profile]?.years||[]).map((key,i)=>{const item=scoreSummary(key);return `<button class="year-card" type="button" data-year="${key}" aria-pressed="${key===year}"><span aria-hidden="true">${icons[i]}</span><b>${escape(yearLabel(key,locale))}</b><small>${item.done}/${item.total}</small></button>`;}).join('')}</div>${year?`<section class="grade-map-head"><div><p class="eyebrow">${escape(PROFILES[profile].names[locale])}</p><h2>${escape(yearLabel(year,locale))}${w.current}</h2></div><div class="grade-total"><span>${w.progress}</span><strong>${summary.done} / ${summary.total} ${w.cleared}</strong><div><i style="width:${summary.total?summary.done/summary.total*100:0}%"></i></div></div></section><div class="subject-tabs" aria-label="${w.map}">${SUBJECTS.map(id=>`<button type="button" data-subject="${id}" aria-pressed="${id===subject}">${w.subjects[id]}</button>`).join('')}</div>${worlds||`<p class="grade-empty">${w.empty}</p>`}<p class="grade-note grade-curriculum-note">${w.note}</p>`:`<p class="grade-empty">${w.pick}</p>`}`;
 app.querySelector('#school-system').onchange=e=>{profile=e.target.value;year='';subject='all';save();render();};
 const label=document.createElement('label');label.textContent=fw.locale;const picker=document.createElement('select');picker.id='grade-locale';picker.setAttribute('aria-label',fw.locale);
 for(const [value,name] of [['en','English'],['zh','中文'],['ja','日本語']]){const option=document.createElement('option');option.value=value;option.textContent=name;option.selected=value===locale;picker.append(option);}picker.onchange=()=>{save();const q=new URLSearchParams(location.search);q.set('locale',picker.value);location.assign(`grades.html?${q}`);};label.append(picker);app.querySelector('.grade-controls').append(label);
}
app.addEventListener('click',e=>{const yearButton=e.target.closest('[data-year]'),subjectButton=e.target.closest('[data-subject]');if(yearButton){year=yearButton.dataset.year;subject='all';save();render();}else if(subjectButton){subject=subjectButton.dataset.subject;render();}});
render();
