import {GAMES,makeRounds,evaluate,solution,rotateMask} from './WorldRules.mjs';
import {TEXT} from './WorldText.mjs';
import {AuthManager} from '../auth/AuthManager.js?v=3';
import {readCountry,saveCountry,normalizeCountry,languageForCountry} from '../location/Country.mjs';
import {validateGradeRoute,availableTasks,yearLabel} from './GradePaths.mjs';
import {gameGateId,gateUrl,journeyProgressKey,journeyState,nextGate,readJourneyScores} from './GradeJourney.mjs';
import {createInteractionFeedback} from './InteractionFeedback.mjs';
import {isEarlyPrimaryChinese,rubyPinyin} from './PinyinRuby.mjs';

const app=document.querySelector('#app'),localeSelect=document.querySelector('#locale'),params=new URLSearchParams(location.search);
let locale='en',country=null,localeTouched=false;
try{country=normalizeCountry(params.get('country'))||readCountry(localStorage);if(country)saveCountry(localStorage,country);locale=country?languageForCountry(country):localStorage.getItem('world-locale')||'en';}catch{country=normalizeCountry(params.get('country'));locale=languageForCountry(country);}
if(!TEXT[locale])locale='en';if(TEXT[params.get('locale')])locale=params.get('locale');
let level=1,view='home',game='circuit',run=null,answer=[],timer,epoch=0,busy=false,interacted=false;
let feedback='',feedbackGood=false,nextState=null,fatal=false;
const gradeCandidate=validateGradeRoute(params);let gradeScores={};try{if(gradeCandidate)gradeScores=readJourneyScores(localStorage,gradeCandidate.profile,gradeCandidate.year,locale);}catch{}
const gradeGate=gradeCandidate?journeyState(gradeCandidate.profile,gradeCandidate.year,gradeScores).find(gate=>gate.id===gameGateId(gradeCandidate.game,gradeCandidate.stage)):null,gradeRoute=gradeCandidate===null?null:gradeCandidate&&gradeGate?.unlocked?gradeCandidate:false;
document.body.classList.toggle('quest-adventure',!!gradeRoute);if(gradeRoute)level=gradeRoute.level;
if(gradeRoute===false)feedback={en:'This school-year link is invalid. Please choose your year again.',zh:'学年链接无效，请重新选择年级。',ja:'がくねんを えらびなおしてね。'}[locale];

const art={circuit:['🔌 ╋','#47e8ff'],sudoku:['▦ ⑥','#ffd166'],code:['🔐 ◉','#bb86ff'],set:['◈ ▲','#ff72ad'],balance:['⚖️ ◆','#6bf0ad'],order:['🚉 ↔','#ff9966'],water:['💧 ⇄','#58a6ff'],network:['⚡ ⬡','#d6ff66']};
const shapes=['●','▲','◆'],mascots=['🦊','🐼','🐰','🐯','🐸','🦁'],codeMarks=['●','▲','■','◆','★'];
const t=()=>TEXT[locale],esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(action,text,cls='')=>`<button type="button" data-action="${action}" class="${cls}">${esc(text)}</button>`;
const auth=new AuthManager({apiBase:'/api',turnstileSiteKey:document.querySelector('meta[name="turnstile-site-key"]').content});let member=false;
const interaction=createInteractionFeedback(),soundToggle=document.querySelector('#sound-toggle');

render();
if(!country)fetch('/api/location',{cache:'no-store',signal:AbortSignal.timeout(4000)}).then(r=>r.json()).then(data=>{if(view==='home'&&!country&&!localeTouched){country=normalizeCountry(data.country);locale=languageForCountry(country);render();}}).catch(()=>{});
auth.initialize().then(session=>{member=session.mode==='authenticated';document.querySelector('#login').textContent=member?t().logged:t().login;}).catch(()=>{});
if(gradeRoute)void start(gradeRoute.game);
document.querySelector('#login').onclick=()=>{if(!member){if(auth.localMode){feedback=t().noAuth;render();}else auth.showLogin({message:t().privacy});}};
soundToggle.onclick=()=>{interaction.toggle();syncSoundToggle();};
localeSelect.onchange=()=>{interaction.tap();localeTouched=true;locale=localeSelect.value;try{localStorage.setItem('world-locale',locale);}catch{}feedback='';render();if(view==='board')loadBoard();};

async function api(path,body){const response=await fetch(`/api/world/${path}`,{method:body?'POST':'GET',credentials:'include',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(12000)}),data=await response.json();if(!response.ok){const error=new Error(data.error||'API_ERROR');error.status=response.status;throw error;}return data;}
function syncSoundToggle(){const muted=interaction.isMuted();soundToggle.setAttribute('aria-pressed',String(muted));soundToggle.textContent=`${muted?'🔇':'🔊'} ${muted?t().soundOff:t().soundOn}`;}
function leave(){epoch++;clearInterval(timer);run=null;nextState=null;busy=false;fatal=false;feedback='';localeSelect.disabled=false;}
function gradeMapUrl(){const query=new URLSearchParams({curriculum:gradeRoute.profile,year:gradeRoute.year,locale});if(country)query.set('country',country);return`grades.html?${query}`;}
function goHome(){if(gradeRoute){leave();location.assign(gradeMapUrl());return;}leave();view='home';render();window.scrollTo(0,0);}
function saveGradeProgress(){if(!gradeRoute||!run||run.timedOut||run.score<800)return false;try{const key=journeyProgressKey(gradeRoute.profile,gradeRoute.year,gameGateId(game,gradeRoute.stage));localStorage.setItem(key,String(Math.max(Number(localStorage.getItem(key)||0),run.score)));return true;}catch{return false;}}

function render(){
 document.documentElement.lang=locale;localeSelect.value=locale;document.body.dataset.game=view==='play'?game:'';document.title=`Piko Play · ${locale==='zh'?'逻辑实验室':locale==='ja'?'ロジックラボ':'Logic Lab'}`;
 syncSoundToggle();
 const gradeLink=document.querySelector('#grade-entry-link');gradeLink.textContent=locale==='zh'?'按年级学习':locale==='ja'?'がくねん':'School year';const back=new URLSearchParams();if(country)back.set('country',country);if(gradeRoute){back.set('curriculum',gradeRoute.profile);back.set('year',gradeRoute.year);}back.set('locale',locale);gradeLink.href=country==='JP'?'index.html?course=jp':`grades.html?${back}`;
 document.querySelector('#login').textContent=member?t().logged:t().login;document.querySelector('#footer-text').textContent=t().footer;
 if(view==='home'){
  app.innerHTML=`<section class="hero"><div><p class="eyebrow">${t().kicker}</p><h1>${t().title}</h1><p>${t().intro}</p></div><div class="orbit" aria-hidden="true"><span>🧩</span><small>DEDUCE · PLAN · SOLVE</small></div></section><div class="section-top"><div><h2>${t().choose}</h2><p class="muted">${t().skills}</p></div><label>${t().level} <select id="level">${t().levels.map((name,i)=>`<option value="${i+1}" ${level===i+1?'selected':''}>${name}</option>`).join('')}</select></label></div>${feedback?`<p class="status" role="status">${esc(feedback)}</p>`:''}<div class="cards">${GAMES.map(id=>`<article class="card"><div class="card-art" style="--tint:${art[id][1]}" aria-hidden="true">${art[id][0]}</div><div class="card-body"><span class="tag">${t().games[id][1]}</span><h3>${t().games[id][0]}</h3><p>${t().games[id][2]}</p><div class="actions">${button(`play:${id}`,t().play,'primary')}${button(`board:${id}`,t().board)}</div></div></article>`).join('')}</div><aside class="rules"><p><b>${t().rules}</b></p><p>${t().privacy}</p></aside>`;
  const picker=document.querySelector('#level');picker.disabled=!!gradeRoute;if(gradeRoute)app.querySelector('.section-top .muted').textContent=yearLabel(gradeRoute.year,locale);picker.onchange=e=>{level=Number(e.target.value);};
  if(gradeRoute)app.querySelectorAll('.card').forEach(card=>{const id=card.querySelector('[data-action^="play:"]').dataset.action.split(':')[1];if(!availableTasks(gradeRoute.profile,gradeRoute.year,gradeRoute.subject).some(task=>task.game===id))card.remove();});
 }else if(view==='board'){
  app.innerHTML=`<div class="play-head">${button('home',`← ${t().home}`)}<h1>${t().board}</h1></div><section class="board"><p>${t().privacy}</p><div class="board-picker"><select id="board-game" aria-label="${t().home}">${GAMES.map(id=>`<option value="${id}" ${game===id?'selected':''}>${t().games[id][0]}</option>`).join('')}</select><select id="board-level" aria-label="${t().level}">${t().levels.map((name,i)=>`<option value="${i+1}" ${level===i+1?'selected':''}>${name}</option>`).join('')}</select>${button('refresh',t().retry)}</div><div id="board-result" aria-live="polite">${t().loading}</div><p class="muted">${t().rules}</p>${button(`play:${game}`,t().play,'primary')}</section>`;
  document.querySelector('#board-game').onchange=e=>{game=e.target.value;render();loadBoard();};document.querySelector('#board-level').onchange=e=>{level=Number(e.target.value);loadBoard();};if(gradeRoute){const ids=availableTasks(gradeRoute.profile,gradeRoute.year,gradeRoute.subject).map(task=>task.game);app.querySelectorAll('#board-game option').forEach(option=>{if(!ids.includes(option.value))option.remove();});document.querySelector('#board-level').disabled=true;}
 }else if(view==='play'&&run)renderPlay();
 else if(view==='result'){
  const passed=run&&run.score>=800&&!run.timedOut;if(passed)saveGradeProgress();let scores={};try{if(gradeRoute)scores=readJourneyScores(localStorage,gradeRoute.profile,gradeRoute.year,locale);}catch{}const next=passed&&gradeRoute?nextGate(gradeRoute.profile,gradeRoute.year,gameGateId(game,gradeRoute.stage),scores):null,nextUrl=next?gateUrl(next,{profile:gradeRoute.profile,year:gradeRoute.year,country,locale}):null;
  app.innerHTML=`<div class="play-head">${button('home',`← ${t().home}`)}<h1>${t().games[game][0]}</h1></div><section class="board result"><div class="big" aria-hidden="true">${passed?'🏆':'🧠'}</div><h2>${run?.timedOut?t().timeout:passed?t().solved:t().failed}</h2><p class="target">${run?.score||0} / 1000</p><p>${run?.ranked&&!run.timedOut?t().saved:t().guest}</p><div class="controls">${button(`play:${game}`,t().again,'primary')}${button(`board:${game}`,t().board)}${nextUrl?`<a class="pill primary" href="${esc(nextUrl)}">${t().next} →</a>`:''}${button('home',t().home)}</div></section>`;
 }
}

function answerReady(){if(!interacted)return false;if(game==='sudoku')return answer.every(Boolean);if(game==='code')return answer.every(n=>n>=0);if(game==='set')return answer.length===3;if(game==='balance')return answer[0]>=0;if(game==='water')return answer.length>0;if(game==='network')return answer.length===run.question.count-1;return true;}
function renderPlay(){
 const pinyin=isEarlyPrimaryChinese(gradeRoute?.profile,gradeRoute?.year),instruction=rubyPinyin(t().games[game][3],pinyin),stageLabel=gradeRoute?` · ${t().stage} ${gradeRoute.stage}`:'';
 app.innerHTML=`<div class="play-head">${button('home',`← ${t().home}`)}<h1>${t().games[game][0]}</h1></div><section class="board game-shell game-${game} ${pinyin?'with-pinyin':''}"><div class="fx-layer" aria-hidden="true"></div><div class="hud"><span>${t().mission} ${Math.min(run.index+1,10)}/10${stageLabel}</span><span>${t().score}: ${run.score}</span><span>${t().time}: <span id="clock"></span></span></div><div class="progress"><span style="width:${run.index*10}%"></span></div><p class="muted">${t().levels[level-1]} · ${run.ranked?t().member:t().guest}</p><p class="instruction">${instruction}</p><div class="stage" id="stage">${stageMarkup()}</div><div class="feedback ${feedbackGood?'good':''}" role="status">${esc(feedback||t().rules)}</div><div class="controls">${fatal?button(`play:${game}`,t().newRun,'primary'):nextState?button('next',nextState.complete?t().solved:t().next,'primary'):button('check',t().check,'primary')}${!nextState&&!fatal?button('clear',t().clear):''}</div></section>`;
 const check=app.querySelector('[data-action="check"]');if(check&&!answerReady())check.disabled=true;app.querySelectorAll('button').forEach(el=>{if(busy&&el.dataset.action!=='home')el.disabled=true;});if(gradeRoute){const task=availableTasks(gradeRoute.profile,gradeRoute.year,gradeRoute.subject).find(item=>item.game===game),context=document.createElement('p');context.className='grade-note';context.textContent=`${yearLabel(gradeRoute.year,locale)} · ${task.skill[locale]}${task.review?locale==='zh'?' · 基础复习':locale==='ja'?' · きほんの ふくしゅう':' · Foundation review':''}`;app.querySelector('.board').prepend(context);}if(nextState||fatal)app.querySelectorAll('#stage button').forEach(el=>{el.disabled=true;});tick();
}

function pipeGlyph(mask){return({3:'└',5:'│',6:'┌',9:'┘',10:'─',12:'┐'})[mask]||'·';}
function sudokuCellClass(q,i){const row=Math.floor(i/q.size),col=i%q.size;return`${(col+1)%q.boxCols===0&&col<q.size-1?' box-right':''}${(row+1)%q.boxRows===0&&row<q.size-1?' box-bottom':''}`;}
function peg(value){return`<span class="code-peg code-color-${value}">${codeMarks[value]}</span>`;}
function cardFace(card){const[shape,color,fill]=card;return`<span class="set-shape code-color-${color} fill-${fill}">${shapes[shape]}</span>`;}
function waterState(q,moves){let[a,b]=[0,0];for(const op of moves){const[ca,cb]=q.capacities;if(op===0)a=ca;if(op===1)b=cb;if(op===2)a=0;if(op===3)b=0;if(op===4){const n=Math.min(a,cb-b);a-=n;b+=n;}if(op===5){const n=Math.min(b,ca-a);b-=n;a+=n;}}return[a,b];}
function stageMarkup(){
 const q=run.question;
 if(game==='circuit')return`<div class="circuit-wrap"><span class="socket source" style="--row:${q.startRow}">⚡</span><div class="circuit-grid" style="--grid:${q.size}">${q.tiles.map((mask,i)=>{const row=Math.floor(i/q.size),col=i%q.size;return`<button type="button" data-action="rotate:${i}" class="pipe ${col===0&&row===q.startRow?'start':''} ${col===q.size-1&&row===q.endRow?'finish':''}" aria-label="${t().cell} ${i+1}">${pipeGlyph(rotateMask(mask,answer[i]))}</button>`;}).join('')}</div><span class="socket goal" style="--row:${q.endRow}">🏁</span></div>`;
 if(game==='sudoku')return`<div class="sudoku-grid" style="--grid:${q.size}">${answer.map((value,i)=>q.givens[i]?`<div class="sudoku-cell given${sudokuCellClass(q,i)}">${value}</div>`:`<button type="button" class="sudoku-cell${sudokuCellClass(q,i)}" data-action="sudoku:${i}" aria-label="${t().cell} ${i+1}">${value||'·'}</button>`).join('')}</div>`;
 if(game==='code')return`<div class="code-clues">${q.clues.map(clue=>`<div class="code-clue"><span>${clue.guess.map(peg).join('')}</span><b>${clue.exact} ${t().exact}</b><b>${clue.color} ${t().misplaced}</b></div>`).join('')}</div><div class="code-answer">${answer.map((value,i)=>`<button type="button" data-action="code:${i}" aria-label="${t().cell} ${i+1}">${value<0?'?':peg(value)}</button>`).join('')}</div>`;
 if(game==='set')return`<b>${t().selectThree} · ${answer.length}/3</b><div class="set-board">${q.cards.map((card,i)=>`<button type="button" data-action="select:${i}" class="set-card ${answer.includes(i)?'selected':''}" aria-pressed="${answer.includes(i)}">${cardFace(card)}<small>${i+1}</small></button>`).join('')}</div>`;
 if(game==='balance')return`<div class="balance-equations">${q.equations.map(eq=>`<div>${eq.counts.map((count,i)=>count?`<span>${count>1?`${count}×`:''}${shapes[i]}</span>`:'').filter(Boolean).join('<b> + </b>')}<b> = ${eq.total}</b></div>`).join('')}</div><div class="balance-target">${t().findWeight} <span class="code-color-${q.target}">${shapes[q.target]}</span> ?</div><div class="number-pad">${Array.from({length:q.max},(_,i)=>i+1).map(n=>`<button type="button" data-action="number:${n}" class="${answer[0]===n?'selected':''}" aria-pressed="${answer[0]===n}">${n}</button>`).join('')}</div>`;
 if(game==='order')return`<div class="logic-clues">${q.constraints.map(rule=>`<span>${mascots[rule.a]} ${rule.type==='before'?t().before:t().beside} ${mascots[rule.b]}</span>`).join('')}</div><div class="order-row">${answer.map((id,pos)=>`<div class="order-card"><b>${mascots[id]}</b><small>${String.fromCharCode(65+id)}</small><div>${button(`left:${pos}`,'←')}${button(`right:${pos}`,'→')}</div></div>`).join('')}</div>`;
 if(game==='water'){const state=waterState(q,answer);return`<div class="water-goal">${t().target}: <b>${q.target}L</b> · ${t().limit}: ${q.limit}</div><div class="tanks">${state.map((amount,i)=>`<div><div class="tank"><span style="height:${amount/q.capacities[i]*100}%"></span><b>${amount}L</b></div><strong>${i?'B':'A'} · ${q.capacities[i]}L</strong></div>`).join('')}</div><div class="move-program">${answer.map((op,i)=>`<span>${i+1}. ${t().ops[op]}</span>`).join('')||'…'}</div><div class="operation-pad">${t().ops.map((name,i)=>button(`water:${i}`,name)).join('')}${button('undo',t().undo)}</div>`;}
 const selected=new Set(answer),total=answer.reduce((sum,i)=>sum+q.edges[i][2],0);return`<p class="network-goal">${t().connect}</p><svg class="network-map" viewBox="0 0 100 100" role="img">${q.edges.map((edge,i)=>`<line x1="${q.nodes[edge[0]][0]}" y1="${q.nodes[edge[0]][1]}" x2="${q.nodes[edge[1]][0]}" y2="${q.nodes[edge[1]][1]}" class="${selected.has(i)?'chosen':''}"/>`).join('')}${q.nodes.map((node,i)=>`<g><circle cx="${node[0]}" cy="${node[1]}" r="6"/><text x="${node[0]}" y="${node[1]+2}">${String.fromCharCode(65+i)}</text></g>`).join('')}</svg><b>${t().energy}: ${total}</b><div class="edge-pad">${q.edges.map((edge,i)=>`<button type="button" data-action="edge:${i}" class="${selected.has(i)?'selected':''}" aria-pressed="${selected.has(i)}">${String.fromCharCode(65+edge[0])}–${String.fromCharCode(65+edge[1])}<small>${edge[2]}⚡</small></button>`).join('')}</div>`;
}

function initialAnswer(q){interacted=false;if(game==='circuit')return Array(q.tiles.length).fill(0);if(game==='sudoku')return[...q.givens];if(game==='code')return Array(q.length).fill(-1);if(game==='set'||game==='water'||game==='network')return[];if(game==='balance')return[-1];if(game==='order')return Array.from({length:q.count},(_,i)=>i);return[];}
async function start(id){if(gradeRoute&&!availableTasks(gradeRoute.profile,gradeRoute.year,gradeRoute.subject).some(task=>task.game===id))return;if(gradeRoute){const query=new URLSearchParams(location.search);query.set('game',id);history.replaceState(null,'',`world.html?${query}`);level=gradeRoute.level;}leave();game=id;const token=epoch;view='home';feedback=t().loading;render();let session=null;try{session=await auth.getSession();}catch{}if(token!==epoch)return;if(member&&!session?.authenticated){member=false;feedback=t().noAuth;render();return;}member=!!session?.authenticated;try{let state;if(member)state={...await api('start',{game,level,stage:gradeRoute?.stage||1}),ranked:true,tries:0};else{const seed=(crypto.getRandomValues(new Uint32Array(1))[0]^Math.imul(gradeRoute?.stage||1,0x9E3779B1))>>>0,rounds=makeRounds(game,level,seed);state={rounds,question:rounds[0],index:0,score:0,tries:0,ranked:false,expiresAt:Date.now()+180000};}if(token!==epoch)return;run=state;answer=initialAnswer(run.question);view='play';feedback='';feedbackGood=false;localeSelect.disabled=true;render();window.scrollTo(0,0);timer=setInterval(tick,250);}catch{if(token===epoch){feedback=t().error;view='home';render();}}}
function tick(){if(!run||view!=='play')return;if(nextState?.complete){clearInterval(timer);const clock=app.querySelector('#clock');if(clock)clock.textContent='✓';return;}const seconds=Math.max(0,Math.ceil((run.expiresAt-Date.now())/1000)),clock=app.querySelector('#clock');if(clock)clock.textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;if(!seconds&&!busy){run.timedOut=true;view='result';clearInterval(timer);localeSelect.disabled=false;interaction.error();render();}}
function burstFx(kind){const shell=app.querySelector('.game-shell');if(!shell)return;shell.classList.add(`fx-${kind}`);setTimeout(()=>shell.classList.remove(`fx-${kind}`),500);if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const layer=shell.querySelector('.fx-layer');for(let i=0;i<(kind==='good'?14:6);i++){const spark=document.createElement('i');spark.style.setProperty('--i',i);spark.textContent=kind==='good'?['✦','●','★'][i%3]:'·';layer.append(spark);setTimeout(()=>spark.remove(),800);}}
async function submit(){if(!run||busy||nextState||fatal||!answerReady())return;const token=epoch;let effect='bad';busy=true;renderPlay();try{let result;if(run.ranked)result=await api('answer',{id:run.id,revision:run.revision,answer});else{const verdict=evaluate(game,run.question,answer,run.tries),index=run.index+(verdict.done?1:0);result={...verdict,index,score:run.score+verdict.points,complete:index===10,question:run.rounds[index]||null,explanation:verdict.done&&!verdict.correct?solution(game,run.question):null};}if(token!==epoch)return;run.score=result.score;run.tries=result.tries;run.revision=result.revision;feedbackGood=result.correct;effect=result.correct?'good':'bad';feedback=result.correct?t().correct:result.done?`${t().explain} ${formatSolution(result.explanation)}`:result.tries===1?t().first:t().games[game][4];if(result.done)nextState=result;}catch(error){if(token!==epoch)return;fatal=[401,404,409,410].includes(error.status);feedback=fatal?t().ended:t().unsaved;}busy=false;renderPlay();if(effect==='good')interaction.correct();else interaction.error();burstFx(effect);}
function formatSolution(value){if(!value)return'';if(game==='circuit')return value.map(n=>'↻'.repeat(n)||'·').join(' ');if(game==='sudoku')return value.join(' ');if(game==='code')return value.map(n=>codeMarks[n]).join(' ');if(game==='set')return value.map(n=>`#${n+1}`).join(' · ');if(game==='balance')return`${value[0]}`;if(game==='order')return value.map(n=>mascots[n]).join(' → ');if(game==='water')return value.map(n=>t().ops[n]).join(' → ');if(game==='network')return value.map(i=>{const edge=run.question.edges[i];return`${String.fromCharCode(65+edge[0])}–${String.fromCharCode(65+edge[1])}`;}).join(' · ');return value.join(' / ');}
async function loadBoard(){const token=++epoch,target=app.querySelector('#board-result');if(!target)return;target.textContent=t().loading;try{const result=await api(`leaderboard?game=${game}&level=${level}`);if(epoch!==token||view!=='board')return;target.innerHTML=result.entries.length?`<div class="table-wrap"><table><thead><tr><th>${t().rank}</th><th>${t().name}</th><th>${t().score}</th></tr></thead><tbody>${result.entries.map(row=>`<tr><td>${row.rank}</td><td>${esc(row.name)}</td><td>${row.score}</td></tr>`).join('')}</tbody></table></div>`:`<p>${t().empty}</p>`;}catch{if(epoch===token&&view==='board')target.textContent=t().error;}}

app.addEventListener('click',event=>{
 const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const[action,value]=el.dataset.action.split(':');
 interaction.tap();
 if(action==='home')return goHome();if(action==='play')return void start(value);if(action==='board'){leave();game=value;view='board';render();window.scrollTo(0,0);return void loadBoard();}if(action==='refresh')return void loadBoard();if(action==='check')return void submit();if(!run||busy||fatal)return;
 if(action==='next'&&nextState){if(nextState.complete){view='result';clearInterval(timer);localeSelect.disabled=false;render();if(run.score>=800&&!run.timedOut)interaction.victory();return;}run.index=nextState.index;run.question=nextState.question;answer=initialAnswer(run.question);nextState=null;feedback='';feedbackGood=false;renderPlay();return;}if(nextState)return;
 const i=Number(value);interacted=true;
 if(action==='rotate')answer[i]=(answer[i]+1)%4;
 if(action==='sudoku'&&!run.question.givens[i])answer[i]=(answer[i]%run.question.size)+1;
 if(action==='code')answer[i]=(answer[i]+1)%run.question.symbols;
 if(action==='select'){if(answer.includes(i))answer=answer.filter(n=>n!==i);else if(answer.length<3)answer=[...answer,i];}
 if(action==='number')answer=[i];
 if(action==='left'&&i>0)[answer[i-1],answer[i]]=[answer[i],answer[i-1]];
 if(action==='right'&&i<answer.length-1)[answer[i],answer[i+1]]=[answer[i+1],answer[i]];
 if(action==='water'&&answer.length<run.question.limit)answer.push(i);
 if(action==='edge'){if(answer.includes(i))answer=answer.filter(n=>n!==i);else answer=[...answer,i];}
 if(action==='undo')answer.pop();
 if(action==='clear')answer=initialAnswer(run.question);
 const focus=el.dataset.action;renderPlay();app.querySelector(`[data-action="${focus}"]`)?.focus({preventScroll:true});
});
window.addEventListener('pagehide',leave);
