export const TEXT={
 en:{
  title:'Eight puzzles worth solving.',intro:'No copying, no answers hidden in the question. Deduce, plan, test and improve across eight interactive puzzle systems.',kicker:'PIKO LOGIC LAB',choose:'Choose a real challenge',level:'Difficulty',levels:['Starter','Master'],play:'Play',board:'Rankings',login:'Log in',logged:'Logged in',back:'Back',home:'All games',check:'Submit solution',next:'Next puzzle',again:'Play again',clear:'Reset',undo:'Undo',loading:'Loading…',error:'Could not connect. Please try again.',empty:'No ranked solvers yet. You could be first!',rank:'Rank',name:'Solver',score:'Score',time:'Time',mission:'Puzzle',guest:'Guest practice · scores stay off the public board',member:'Ranked challenge · your system nickname may appear publicly',rules:'10 unique puzzles · 3 minutes · 800 points to clear · tied scores share rank',privacy:'Everyone can view rankings. Log in before a challenge to save your server-checked score under a random nickname. Real names and email addresses are never shown.',skills:'Every puzzle hides its solution and requires deduction or planning. Each game has a separate two-level ranking.',first:'That attempt does not satisfy every rule yet. Recheck the result of each move.',second:'Final try: isolate one constraint, test it, then combine it with the others.',correct:'Solved! Logic core charged.',explain:'Solution revealed after three attempts:',solved:'Challenge cleared!',failed:'Training complete. Try again to reach 800!',timeout:'Time is up. This attempt is not ranked.',saved:'Your best score is saved.',unsaved:'Score was not saved. Start a fresh challenge.',retry:'Retry',ended:'This challenge expired or changed. Start again.',newRun:'New challenge',noAuth:'Log in on the main page to enter rankings.',footer:'Think it through.',target:'Target',answer:'Your solution',cell:'Cell',exact:'exact place',misplaced:'right symbol, wrong place',selectThree:'Choose exactly three cards',findWeight:'Find the weight of',before:'is before',beside:'is beside',moves:'Moves',limit:'Move limit',energy:'Energy',connect:'Connect every island using the least total energy.',soundOn:'Sound on',soundOff:'Sound off',stage:'Stage',
  ops:['Fill A','Fill B','Empty A','Empty B','Pour A → B','Pour B → A'],
  games:{
   circuit:['Circuit Relay','SPATIAL PLANNING','Rotate a scrambled pipe board into a working energy route.','Turn pipe pieces until power can travel from the left socket to the right socket.','Start at the left socket. Follow only openings that meet; a gap breaks the circuit.'],
   sudoku:['Number Vault','CONSTRAINT LOGIC','Complete a compact Sudoku without breaking any region.','Fill every blank so each row, column and outlined region uses every number once.','Choose one blank and eliminate numbers already present in its row, column and region.'],
   code:['Codebreaker','DEDUCTIVE REASONING','Use several imperfect scans to discover a hidden symbol code.','Build the only code that matches every exact-position and wrong-position clue.','A symbol can repeat. Compare two clues and look for what changed between them.'],
   set:['Triple Set','CLASSIFICATION','Find three cards whose features form a valid triple.','Choose three cards. For every feature, the values must be all the same or all different.','Check shape, colour and fill separately. One mixed feature makes the triple invalid.'],
   balance:['Weight Detective','ALGEBRAIC REASONING','Infer hidden object weights from three balance equations.','Use all three equations to find the requested object’s weight.','Compare equations that share an object; their difference removes that shared part.'],
   order:['Logic Lineup','READING · LOGIC','Arrange travellers using only relative-position clues.','Move every traveller until all “before” and “beside” clues are true together.','Place the beside pairs first, then use before clues to orient and combine them.'],
   water:['Water Lab','MULTI-STEP PLANNING','Measure an exact amount using two unmarked tanks.','Program fills, empties and pours to reach the target within the optimal move limit.','Work backward from the target: which pour could create exactly that remainder?'],
   network:['Island Grid','OPTIMISATION','Power every island without wasting a single unit of energy.','Choose links that connect all islands with the minimum possible total cost and no loops.','Add cheap links first, but skip any link that only creates a cycle.']
  }
 },
 zh:{
  title:'八款真正需要破解的游戏。',intro:'不再照抄题面，也不把答案摆在眼前。通过推理、规划、试验和修正，破解八套互动谜题。',kicker:'皮可逻辑实验室',choose:'选择一项真正的挑战',level:'难度',levels:['启航级','大师级'],play:'开始挑战',board:'排行榜',login:'登录',logged:'已登录',back:'返回',home:'所有游戏',check:'提交方案',next:'下一谜题',again:'再玩一次',clear:'重置',undo:'撤销',loading:'正在加载…',error:'暂时无法连接，请重试。',empty:'还没有上榜的解谜者，你可以成为第一位！',rank:'名次',name:'解谜者',score:'得分',time:'剩余',mission:'谜题',guest:'游客练习 · 成绩不进入公开榜单',member:'排名挑战 · 将以系统昵称公开成绩',rules:'10道不重复谜题 · 3分钟 · 800分通关 · 同分同名次',privacy:'所有人都能查看排行榜。登录后挑战，服务端验算的成绩会以随机昵称保存，不展示真实姓名和邮箱。',skills:'每道谜题都隐藏答案，必须推理或规划；每款游戏都有两档独立排行榜。',first:'当前方案还没有满足全部规则，逐步检查每次操作的结果。',second:'最后一次机会：先锁定一条约束，再把其他约束合并进来。',correct:'破解成功！逻辑核心已充能。',explain:'三次尝试后展示一种解法：',solved:'挑战通关！',failed:'训练完成，再试一次向800分出发！',timeout:'时间到了，本次不上榜。',saved:'已保存你的最佳成绩。',unsaved:'成绩未保存，请开始新的挑战。',retry:'重试',ended:'挑战已过期或状态变化，请重新开始。',newRun:'重新挑战',noAuth:'请在主页登录后参加排名。',footer:'想清楚，再行动。',target:'目标',answer:'你的方案',cell:'格子',exact:'位置和符号都正确',misplaced:'符号正确但位置错误',selectThree:'请正好选择三张卡片',findWeight:'求出重量',before:'排在前面',beside:'紧挨着',moves:'步骤',limit:'步数上限',energy:'能量',connect:'用最低总能量连接全部岛屿。',soundOn:'声音已开启',soundOff:'声音已关闭',stage:'关卡',
  ops:['装满 A','装满 B','倒空 A','倒空 B','A 倒入 B','B 倒入 A'],
  games:{
   circuit:['能量管网','空间规划','把打乱方向的管道旋转成一条完整能源通路。','转动管道，接通电路。','从左侧入口开始追踪；相邻开口必须正好接住，任何缺口都会断路。'],
   sudoku:['数独秘舱','约束推理','补全迷你数独，同时满足所有区域规则。','每行、每列和每个小宫，数字不能重复。','先找一个空格，排除同行、同列和同宫已经出现的数字。'],
   code:['密码猎手','演绎推理','根据多次不完整扫描，找出真正隐藏的符号密码。','让密码同时符合所有提示。','符号可以重复。比较两条线索，观察它们只改变了什么。'],
   set:['三元星群','分类观察','找出三张在所有特征上构成完整关系的卡片。','选三张卡，每种特征要全同或全不同。','把形状、颜色、纹理分开检查；任何一个特征混杂都不成立。'],
   balance:['重量侦探','代数推理','从三条天平等式中推断隐藏物体的重量。','用三条等式，求出图形重量。','比较含有相同物体的两条等式，相减可以消去共有部分。'],
   order:['逻辑站台','阅读 · 推理','只依据相对位置线索，安排所有旅客的顺序。','移动旅客，让前后和相邻线索成立。','先组合紧挨着的人，再用前后线索确定方向并连接组合。'],
   water:['量水实验室','多步规划','只用两个没有刻度的水箱量出精确水量。','装满、倒空或互倒，量出目标水量。','从目标倒推：最后哪一次互倒能恰好留下这个余量？'],
   network:['群岛电网','优化策略','不浪费任何能量，让所有岛屿接入电网。','不成环，用最少能量连通所有岛。','优先考虑低成本连线；若只会形成环路，就跳过它。']
  }
 },
 ja:{
  title:'ほんとうに とく 8つの パズル。',intro:'うつすだけの もんだいは おしまい。すいりして、けいかくして、ためして、なおして 8つの パズルを とこう。',kicker:'ピコ ロジックラボ',choose:'ほんものの ちょうせんを えらぼう',level:'むずかしさ',levels:['スタート','マスター'],play:'ちょうせん',board:'ランキング',login:'ログイン',logged:'ログイン中',back:'もどる',home:'ゲームいちらん',check:'こたえを おくる',next:'つぎの パズル',again:'もういちど',clear:'やりなおす',undo:'ひとつもどす',loading:'よみこみ中…',error:'つながりませんでした。もういちど ためしてね。',empty:'まだ きろくがないよ。さいしょの ひとに なろう！',rank:'じゅんい',name:'チャレンジャー',score:'てんすう',time:'のこり',mission:'パズル',guest:'ゲストれんしゅう · ランキングには のりません',member:'ランキングに ちょうせん · ランダムな なまえで のるよ',rules:'ちがう10もん · 3ぷん · 800てんで クリア · おなじ点は おなじ じゅんい',privacy:'だれでも ランキングを みられます。ログインすると、サーバーで たしかめた てんすうを ランダムな なまえで きろくします。本名やメールは でません。',skills:'どのパズルも こたえは かくれているよ。すいりや けいかくが ひつようで、2つの なんいどに べつべつの ランキングが あるよ。',first:'まだ すべての ルールを みたしていないよ。ひとつずつ けっかを たしかめよう。',second:'さいごの ちょうせん。ひとつの じょうけんを きめてから、ほかと くみあわせよう。',correct:'とけた！ロジックコアが ひかったよ。',explain:'3かいの あとで、ひとつの こたえを みよう：',solved:'チャレンジ クリア！',failed:'れんしゅう かんりょう。もういちど 800てんを めざそう！',timeout:'じかんに なったよ。こんかいは ランキングに のらないよ。',saved:'ベストスコアを きろくしたよ。',unsaved:'きろくできませんでした。あたらしく はじめてね。',retry:'もういちど',ended:'この ちょうせんは おわりました。',newRun:'あたらしく あそぶ',noAuth:'ホームで ログインしてね。',footer:'よく かんがえて、うごかそう。',target:'もくひょう',answer:'きみの こたえ',cell:'ます',exact:'ばしょも しるしも せいかい',misplaced:'しるしだけ せいかい',selectThree:'カードを 3まい えらぼう',findWeight:'おもさを みつけよう',before:'より まえ',beside:'の となり',moves:'てじゅん',limit:'てじゅんの かず',energy:'エネルギー',connect:'いちばん すくない エネルギーで ぜんぶの しまを つなごう。',soundOn:'音あり',soundOff:'音なし',stage:'ステージ',
  ops:['Aを いっぱい','Bを いっぱい','Aを からに','Bを からに','AからBへ','BからAへ'],
  games:{
   circuit:['エネルギーかいろ','くうかん · けいかく','ばらばらの パイプを まわして、ひとつの みちにしよう。','パイプを まわし、ひだりの いりぐちから みぎの でぐちまで つなごう。','ひだりから たどろう。となりの あなが ぴったり あわないと とおれないよ。'],
   sudoku:['ナンバーそうこ','じょうけん · すいり','ミニすうどくを すべての ルールに あわせて うめよう。','たて、よこ、ふとい わくの なかで、おなじ すうじを 1かいずつ つかおう。','ひとつの からマスで、たて・よこ・わくに ある すうじを けそう。'],
   code:['あんごうハンター','えんえき · すいり','いくつもの スキャンから、かくれた あんごうを みつけよう。','ばしょが あう かずと、しるしだけ あう かずを ぜんぶ みたす あんごうを つくろう。','おなじ しるしも つかえるよ。2つの ヒントで かわった ところを くらべよう。'],
   set:['トリプルスター','なかまわけ','3つの とくちょうが きれいに そろう カードを みつけよう。','かたち、いろ、もようが、それぞれ ぜんぶ おなじか ぜんぶ ちがう 3まいを えらぼう。','かたち、いろ、もようを ひとつずつ べつに たしかめよう。'],
   balance:['おもさたんてい','しき · すいり','3つの てんびんの しきから、ものの おもさを みつけよう。','3つの しきを つかって、きかれた ものの おもさを こたえよう。','おなじ ものが ある 2つの しきを くらべると、ひとつを けせるよ。'],
   order:['ロジックえき','ことば · すいり','ばしょの ヒントだけで、みんなを ただしく ならべよう。','「まえ」と「となり」の ヒントが ぜんぶ あうように うごかそう。','となりの ふたりを さきに くみあわせ、まえの ヒントで むきを きめよう。'],
   water:['みずラボ','なんてじゅん · けいかく','めもりの ない 2つの タンクで ぴったりの みずを はかろう。','いっぱい、から、うつすを ならべ、きめられた てじゅんで もくひょうを つくろう。','さいごの うつしかたから ぎゃくに かんがえてみよう。'],
   network:['しまの でんりょくもう','さいてきか','いちばん すくない エネルギーで すべての しまを つなごう。','わを つくらず、ぜんぶの しまを いちばん やすく つなぐ せんを えらぼう。','やすい せんから えらぶ。でも わになる せんは とばそう。']
  }
 }
};
