import {DESIGN_KITS,DESIGN_PALETTE,resolveKit} from './DesignerCatalog.mjs';
import {renderDesignScene,designTransform,thumbnail} from './DesignerRender.mjs';
export const BUBBLE_DIFFICULTY=Object.freeze({lives:0,targets:16});
const COPY={
 zh:{lab:'产品设计工坊',plane:'航空设计',car:'汽车设计',phone:'手机设计',library:'零件库',required:'核心零件',optional:'装饰',assembled:'已组装',move:'移动',paint:'零件配色',brush:'画笔',eraser:'橡皮',undo:'撤销',redo:'重做',remove:'移除',rotate:'旋转',scale:'尺寸',up:'上一层',down:'下一层',grid:'网格',guide:'组装参考',demo:'示范预览',edit:'返回设计',finish:'完成作品',export:'导出作品',screenshot:'屏幕截图',save:'保存截图',close:'关闭',clear:'重新设计',tip:'拖拽零件到画布，或点击零件自动装入。选中后可配色、旋转和调整尺寸。',incomplete:'请先组装全部核心零件，再添加涂鸦或自定义配色。',demoTip:'示范预览：点击“返回设计”继续组装。',selected:'已选中',idle:'选择零件 · 画笔自由创作',capture:'工作台屏幕截图',custom:'个性化',reset:'重置布局'},
 en:{lab:'Product Design Studio',plane:'Aircraft',car:'Vehicles',phone:'Phones',library:'Parts library',required:'Core parts',optional:'Optional',assembled:'Installed',move:'Move',paint:'Paint part',brush:'Draw',eraser:'Erase',undo:'Undo',redo:'Redo',remove:'Remove',rotate:'Rotate',scale:'Size',up:'Forward',down:'Backward',grid:'Grid',guide:'Assembly guide',demo:'Preview example',edit:'Back to design',finish:'Finish',export:'Export artwork',screenshot:'Screenshot',save:'Save screenshot',close:'Close',clear:'New design',tip:'Drag parts onto the canvas or click to install. Select parts to paint, rotate and resize.',incomplete:'Install every core part and add drawing or a custom color.',demoTip:'Example preview: return to design to assemble.',selected:'Selected',idle:'Select parts · Draw your ideas',capture:'Studio screenshot',custom:'Personalized',reset:'Reset layout'},
 ja:{lab:'プロダクト デザイン工房',plane:'ひこうき',car:'くるま',phone:'スマートフォン',library:'パーツ',required:'メインパーツ',optional:'かざり',assembled:'できた',move:'うごかす',paint:'いろぬり',brush:'ペン',eraser:'けしゴム',undo:'もどす',redo:'やりなおす',remove:'はずす',rotate:'かいてん',scale:'サイズ',up:'まえへ',down:'うしろへ',grid:'グリッド',guide:'くみたてガイド',demo:'おてほん',edit:'デザインに もどる',finish:'かんせい',export:'さくひんを ほぞん',screenshot:'スクリーンショット',save:'ほぞん',close:'とじる',clear:'あたらしく',tip:'パーツを ドラッグ、または タップで くみたてよう。いろや サイズも かえられるよ。',incomplete:'メインパーツを くみたてて、いろや えを くふうしよう。',demoTip:'おてほんです。デザインに もどって つくろう。',selected:'えらんだ パーツ',idle:'パーツを えらんで じゆうに かこう',capture:'スクリーンショット',custom:'じぶんの デザイン',reset:'はいちを もどす'}
};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createBubbleGame({canvas,onHud,onEnd,locale='en',autoStart=true}={}){
 const t=COPY[locale]||COPY.en,doc=canvas.ownerDocument,win=doc?.defaultView,ctx=canvas.getContext('2d');
 const originalParent=canvas.parentElement,originalNext=canvas.nextSibling;let root=null,board=null,observer=null,disposed=false,running=false,ended=false;
 let kitId='airliner',kit=DESIGN_KITS.airliner,parts=[],strokes=[],selected=null,tool='move',color='#3887b0',brushSize=6,grid=true,guides=true,demo=false,score=0,message=t.tip,active=null,focus=false;
 let history=[],future=[],captureUrl='',customizations=0,viewWidth=900,viewHeight=560;const drafts=new Map(),thumbCache=new Map();
 const name=p=>p.names[locale]||p.names.en,kitName=k=>k.name[locale]||k.name.en;
 const snapshot=()=>JSON.stringify({parts,strokes,selected,customizations});
 function restore(data){const state=JSON.parse(data);parts=state.parts;strokes=state.strokes;selected=state.selected;customizations=state.customizations||0;}
 function remember(before=snapshot()){history.push(before);if(history.length>40)history.shift();future=[];}
 function mutate(fn){if(!running||ended||demo)return false;remember();fn();sync();return true;}
 function thumb(k,p=null){if(!doc)return '';const key=k.name.en+(p?.id||'kit');if(!thumbCache.has(key))thumbCache.set(key,thumbnail(doc,k,p));return thumbCache.get(key);}
 const button=(attr,text,extra='')=>`<button type="button" ${attr} ${extra}>${esc(text)}</button>`;
 if(doc&&originalParent){
  root=doc.createElement('div');root.className='designer-studio';root.innerHTML=`<header class="designer-header"><div class="designer-brand"><span>PIKO / DESIGN LAB</span><strong>${t.lab}</strong></div><nav class="designer-categories" aria-label="${t.lab}">${['plane','car','phone'].map(c=>button(`data-project="${c}"`,t[c])).join('')}</nav><div class="designer-kits"></div></header><aside class="designer-library"><div class="designer-library-heading"><strong>${t.library}</strong><span data-designer-count></span></div><p class="designer-library-tip">${t.tip}</p><div class="designer-parts"></div></aside><main class="designer-main"><div class="designer-document-heading"><div><h2 data-kit-name></h2><p data-kit-subtitle></p></div><div class="designer-view-tools">${button('data-focus',({zh:'专注画布',en:'Focus canvas',ja:'キャンバス'}[locale]||'Focus canvas'))}${button('data-demo',t.demo)}${button('data-guide',t.guide,'aria-pressed="true"')}${button('data-grid',t.grid,'aria-pressed="true"')}</div></div><div class="designer-board"></div><div class="designer-inspector"><span data-selection>${t.idle}</span><div>${button('data-rotate="-15"','↶ '+t.rotate)}${button('data-rotate="15"','↷')}${button('data-resize="-.1"','− '+t.scale)}${button('data-resize=".1"','+')}${button('data-layer="1"',t.up)}${button('data-layer="-1"',t.down)}${button('data-remove',t.remove)}</div></div></main><footer class="designer-toolbar"><div class="designer-tools">${['move','paint','brush','eraser'].map((v,i)=>button(`data-tool="${v}"`,['↖ ','◉ ','✎ ','▱ '][i]+t[v])).join('')}${button('data-undo','↶ '+t.undo)}${button('data-redo','↷ '+t.redo)}</div><div class="designer-colors">${DESIGN_PALETTE.map(c=>`<button type="button" data-color="${c}" style="--swatch:${c}" aria-label="${c}"></button>`).join('')}<input type="color" data-custom-color value="#3887b0" aria-label="${{zh:'自定义颜色',en:'Custom color',ja:'じゆうな いろ'}[locale]}"><label>${t.scale}<input data-brush-size type="range" min="2" max="22" value="6" aria-label="${t.brush}"></label></div><div class="designer-status"><p role="status" data-designer-message>${t.tip}</p>${button('data-clear',t.clear)}${button('data-download',t.export)}${button('data-screenshot','▣ '+t.screenshot)}${button('data-finish',t.finish,'class="designer-finish"')}</div></footer>`;
  originalParent.append(root);board=root.querySelector('.designer-board');board.append(canvas);canvas.classList.add('designer-canvas');
  root.addEventListener('click',click);root.addEventListener('pointerdown',libraryDown);root.addEventListener('input',input);
  canvas.addEventListener('pointerdown',canvasDown);win.addEventListener('pointermove',pointerMove);win.addEventListener('pointerup',pointerUp);win.addEventListener('pointercancel',pointerCancel);win.addEventListener('keydown',key);canvas.addEventListener('arcade-resize',resize);canvas.addEventListener('arcade-export',exportArtwork);
  observer=new ResizeObserver(resize);observer.observe(board);
 }
 function resize(){if(!doc||disposed)return;const r=board.getBoundingClientRect();viewWidth=Math.max(100,r.width);viewHeight=Math.max(100,r.height);const dpr=Math.min(win.devicePixelRatio||1,2);canvas.width=Math.round(viewWidth*dpr);canvas.height=Math.round(viewHeight*dpr);render();}
 function render(){if(!doc||disposed)return;ctx.setTransform(canvas.width/viewWidth,0,0,canvas.height/viewHeight,0,0);ctx.clearRect(0,0,viewWidth,viewHeight);renderDesignScene(ctx,{kit,parts,strokes,selected,grid,ghosts:guides,demo},viewWidth,viewHeight);ctx.setTransform(1,0,0,1,0,0);}
 function updateLibrary(){if(!root)return;root.querySelector('.designer-kits').innerHTML=Object.entries(DESIGN_KITS).filter(([,k])=>k.category===kit.category).map(([id,k])=>`<button type="button" class="designer-kit" data-kit="${id}" aria-pressed="${id===kitId}"><img src="${thumb(k)}" alt=""><span>${esc(kitName(k))}</span></button>`).join('');root.querySelector('.designer-parts').innerHTML=parts.map(p=>`<button type="button" class="designer-part" data-part="${p.id}" aria-label="${esc(name(p))}" aria-pressed="${p.id===selected}" data-installed="${p.placed}"><img src="${thumb(kit,p)}" alt="" draggable="false"><span>${esc(name(p))}</span><span class="designer-drag-handle" aria-hidden="true">↟</span><small>${p.placed?'✓ '+t.assembled:p.required?t.required:t.optional}</small></button>`).join('');root.querySelector('.designer-parts').scrollTop=0;root.querySelector('.designer-parts').scrollLeft=0;root.querySelector('[data-kit-name]').textContent=kitName(kit);root.querySelector('[data-kit-subtitle]').textContent=kit.subtitle[locale]||kit.subtitle.en;}
 function sync(){const done=parts.filter(p=>p.required&&p.placed).length,total=parts.filter(p=>p.required).length;onHud?.({score,lives:'—',extra:`${done}/${total} · ${t.lab}`});if(root){root.querySelector('[data-designer-count]').textContent=`${done}/${total}`;root.querySelector('[data-selection]').textContent=selected?`${t.selected}: ${name(parts.find(p=>p.id===selected))}`:t.idle;root.querySelector('[data-designer-message]').textContent=demo?t.demoTip:message;root.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===tool)));root.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.color===color)));root.querySelectorAll('[data-project]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.project===kit.category)));root.querySelectorAll('[data-part]').forEach(b=>{const p=parts.find(p=>p.id===b.dataset.part);b.dataset.installed=String(p.placed);b.setAttribute('aria-pressed',String(p.id===selected));b.querySelector('small').textContent=p.placed?'✓ '+t.assembled:p.required?t.required:t.optional;});root.querySelector('[data-undo]').disabled=!history.length||demo;root.querySelector('[data-redo]').disabled=!future.length||demo;root.querySelector('[data-finish]').disabled=demo;root.querySelector('[data-demo]').textContent=demo?t.edit:t.demo;root.querySelector('[data-guide]').setAttribute('aria-pressed',String(guides));root.querySelector('[data-grid]').setAttribute('aria-pressed',String(grid));root.querySelectorAll('[data-rotate],[data-resize],[data-layer],[data-remove]').forEach(b=>b.disabled=!selected||demo);}
  render();
 }
 function selectProject(id,{reset=false}={}){if(disposed||ended||(!running&&parts.length))return false;const next=resolveKit(id);if(!next)return false;if(parts.length&&!reset)drafts.set(kitId,snapshot());kit=next;kitId=Object.keys(DESIGN_KITS).find(k=>DESIGN_KITS[k]===kit);if(drafts.has(kitId)&&!reset)restore(drafts.get(kitId));else{parts=kit.parts.map(p=>({...p,placed:false,rotation:0,scale:1}));strokes=[];selected=null;customizations=0;}history=[];future=[];tool='move';demo=false;active=null;score=0;message=t.tip;updateLibrary();sync();return true;}
 function scenePoint(e){const r=canvas.getBoundingClientRect(),t=designTransform(viewWidth,viewHeight,kit);return {x:((e.clientX-r.left)*viewWidth/r.width-t.x)/t.scale,y:((e.clientY-r.top)*viewHeight/r.height-t.y)/t.scale,inside:e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom};}
 function hit(point){return [...parts].filter(p=>p.placed).sort((a,b)=>b.z-a.z).find(p=>{const a=-(p.rotation||0)*Math.PI/180,dx=(point.x-p.x)/(p.scale||1),dy=(point.y-p.y)/(p.scale||1),x=dx*Math.cos(a)-dy*Math.sin(a),y=dx*Math.sin(a)+dy*Math.cos(a);if(Math.abs(x)>p.w/2+4||Math.abs(y)>p.h/2+4)return false;if(p.kind==='path')return ctx.isPointInPath(new Path2D(p.path),x,y);return true;});}
 function placePart(id,x,y){const p=parts.find(p=>p.id===id);if(!p)return false;return mutate(()=>{p.placed=true;p.x=Number.isFinite(x)?x:p.tx;p.y=Number.isFinite(y)?y:p.ty;selected=id;message=t.tip;});}
 function choosePart(id){const p=parts.find(p=>p.id===id);if(p?.placed){selected=id;sync();return true;}return placePart(id);}
 function libraryDown(e){const b=e.target.closest('[data-part]');if(!b||!running||ended||demo||e.button>0)return;if(e.pointerType!=='touch')e.preventDefault();active={id:b.dataset.part,source:'library',before:snapshot(),clientX:e.clientX,clientY:e.clientY,moved:false};selected=b.dataset.part;sync();}
 function canvasDown(e){if(!running||ended||demo||e.button>0)return;e.preventDefault();const point=scenePoint(e);if(!point.inside)return;const item=hit(point);if(tool==='paint'){if(item)mutate(()=>{item.color=color;selected=item.id;customizations++;});return;}if(tool==='move'){selected=item?.id||null;if(item)active={id:item.id,source:'canvas',before:snapshot(),clientX:e.clientX,clientY:e.clientY,dx:item.x-point.x,dy:item.y-point.y,moved:false};sync();}else if(strokes.length<120){const stroke={color,size:brushSize,erase:tool==='eraser',points:[{x:point.x,y:point.y},{x:point.x+.05,y:point.y}]};const before=snapshot();strokes.push(stroke);active={source:'stroke',before,stroke};render();}}
 function pointerMove(e){if(!active||!running||ended)return;const point=scenePoint(e);if(active.source==='stroke'){if(point.inside&&active.stroke.points.length<3000)active.stroke.points.push({x:point.x,y:point.y});render();return;}if(Math.hypot(e.clientX-active.clientX,e.clientY-active.clientY)>6)active.moved=true;if(!active.moved||!point.inside)return;const p=parts.find(p=>p.id===active.id),b=kit.bounds;p.x=Math.max(b.x,Math.min(b.x+b.w,point.x+(active.dx||0)));p.y=Math.max(b.y,Math.min(b.y+b.h,point.y+(active.dy||0)));p.placed=true;render();}
 function pointerUp(e){if(!active)return;const current=active;active=null;if(!running||ended){restore(current.before);sync();return;}if(current.source==='stroke'){remember(current.before);}else if(!current.moved&&current.source==='library'){restore(current.before);choosePart(current.id);return;}else if(current.moved){if(!scenePoint(e).inside)restore(current.before);else{const p=parts.find(p=>p.id===current.id);if(Math.hypot(p.x-p.tx,p.y-p.ty)<28){p.x=p.tx;p.y=p.ty;}remember(current.before);}}sync();}
 function pointerCancel(){if(active){restore(active.before);active=null;sync();}}
 function undo(){if(!running||ended||demo||!history.length)return;future.push(snapshot());restore(history.pop());sync();}
 function redo(){if(!running||ended||demo||!future.length)return;history.push(snapshot());restore(future.pop());sync();}
 function transformPart(action,value){if(!selected)return false;return mutate(()=>{const p=parts.find(p=>p.id===selected);if(action==='rotate')p.rotation=((p.rotation||0)+value+360)%360;if(action==='resize')p.scale=Math.max(.55,Math.min(1.8,(p.scale||1)+value));if(action==='layer'){const layers=parts.filter(q=>q.placed&&q.id!==p.id).map(q=>q.z);p.z=value>0?Math.max(...layers,0)+1:Math.min(...layers,0)-1;}customizations++;});}
 function download(url,filename){const a=doc.createElement('a');a.href=url;a.download=filename;a.click();}
 function exportArtwork(){if(!doc)return null;const points=[];for(const p of parts.filter(p=>p.placed)){const a=(p.rotation||0)*Math.PI/180,s=p.scale||1,rx=(Math.abs(Math.cos(a))*p.w+Math.abs(Math.sin(a))*p.h)*s/2+22,ry=(Math.abs(Math.sin(a))*p.w+Math.abs(Math.cos(a))*p.h)*s/2+22;points.push({x:p.x-rx,y:p.y-ry},{x:p.x+rx,y:p.y+ry});}for(const stroke of strokes)if(!stroke.erase)points.push(...stroke.points);let exportKit=kit;if(points.length){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of points){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y);}const x=minX-24,y=minY-24;exportKit={...kit,bounds:{x,y,w:Math.max(50,maxX-x+24),h:Math.max(50,maxY-y+24)}};}const out=doc.createElement('canvas');out.width=1800;out.height=1200;renderDesignScene(out.getContext('2d'),{kit:exportKit,parts,strokes,grid:false,ghosts:false,demo:false,clean:true},1800,1200);const url=out.toDataURL('image/png');download(url,`piko-${kitId}-artwork.png`);return url;}
 /** Rasterize the visible studio's own DOM geometry and native canvas; no screen permissions or remote media. */
 function screenshot(){if(!doc)return null;render();const rect=root.getBoundingClientRect(),out=doc.createElement('canvas'),dpr=2;out.width=Math.round(rect.width*dpr);out.height=Math.round(rect.height*dpr);const c=out.getContext('2d');c.scale(dpr,dpr);c.fillStyle='#eff3f8';c.fillRect(0,0,rect.width,rect.height);
  function drawElement(el){if(el.classList.contains('designer-capture'))return;const r=el.getBoundingClientRect(),style=win.getComputedStyle(el);if(!r.width||!r.height||style.display==='none'||style.visibility==='hidden')return;const x=r.left-rect.left,y=r.top-rect.top;c.save();if(/hidden|auto|scroll/.test(style.overflow+style.overflowY)){c.beginPath();c.rect(x,y,r.width,r.height);c.clip();}if(style.backgroundColor!=='rgba(0, 0, 0, 0)'){c.fillStyle=style.backgroundColor;const radius=parseFloat(style.borderRadius)||0;c.beginPath();c.roundRect(x,y,r.width,r.height,radius);c.fill();}if(el===canvas)c.drawImage(canvas,x,y,r.width,r.height);else if(el.tagName==='IMG'){if(el.complete)c.drawImage(el,x,y,r.width,r.height);}else if(!el.children.length&&el.textContent.trim()){c.fillStyle=style.color;c.font=`${style.fontWeight} ${style.fontSize} ${style.fontFamily}`;c.textAlign=style.textAlign==='center'?'center':'left';c.textBaseline='middle';const pad=parseFloat(style.paddingLeft)||0;c.fillText(el.textContent.trim(),style.textAlign==='center'?x+r.width/2:x+pad,y+r.height/2,Math.max(4,r.width-pad*2));}for(const child of el.children)drawElement(child);c.restore();}
  drawElement(root);captureUrl=out.toDataURL('image/png');let panel=root.querySelector('.designer-capture');if(!panel){panel=doc.createElement('div');panel.className='designer-capture';panel.setAttribute('role','dialog');panel.setAttribute('aria-label',t.capture);panel.innerHTML=`<div><h3>${t.capture}</h3><img alt="${t.capture}"><p>${kitName(kit)} · PIKO DESIGN LAB</p><div>${button('data-capture-save',t.save)}${button('data-capture-close',t.close)}</div></div>`;root.append(panel);}panel.querySelector('img').src=captureUrl;panel.hidden=false;return captureUrl;
 }
 function finish(){if(!running||ended||demo)return false;const valid=parts.filter(p=>p.required).every(p=>p.placed);const art=strokes.some(s=>!s.erase&&s.points.length>2)||customizations>0;if(!valid||!art){message=t.incomplete;sync();return false;}score=400+Math.min(100,customizations*10)+Math.min(100,strokes.filter(s=>!s.erase&&s.points.length>2).length*10);ended=true;running=false;root?.classList.add('designer-ended');onEnd?.({cleared:true,score,detail:`${kitName(kit)} · ${parts.filter(p=>p.placed).length} ${t.assembled}`});return true;}
 function click(e){const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-capture-save')){download(captureUrl,`piko-${kitId}-screenshot.png`);return;}if(b.hasAttribute('data-capture-close')){b.closest('.designer-capture').hidden=true;return;}if(!running||ended)return;if(b.dataset.project){const id=Object.keys(DESIGN_KITS).find(id=>DESIGN_KITS[id].category===b.dataset.project);selectProject(id);return;}if(b.dataset.kit){selectProject(b.dataset.kit);return;}if(b.dataset.part&&e.detail===0){choosePart(b.dataset.part);return;}if(b.dataset.tool)tool=b.dataset.tool;if(b.dataset.color){color=b.dataset.color;if(tool==='move')tool='paint';if(tool==='paint'&&selected)mutate(()=>{parts.find(p=>p.id===selected).color=color;customizations++;});}if(b.hasAttribute('data-undo'))undo();if(b.hasAttribute('data-redo'))redo();if(b.hasAttribute('data-remove')&&selected)mutate(()=>{parts.find(p=>p.id===selected).placed=false;selected=null;});if(b.dataset.rotate)transformPart('rotate',Number(b.dataset.rotate));if(b.dataset.resize)transformPart('resize',Number(b.dataset.resize));if(b.dataset.layer)transformPart('layer',Number(b.dataset.layer));if(b.hasAttribute('data-clear')){drafts.delete(kitId);selectProject(kitId,{reset:true});}if(b.hasAttribute('data-focus')){focus=!focus;root.classList.toggle('designer-focus',focus);b.setAttribute('aria-pressed',String(focus));resize();}if(b.hasAttribute('data-demo'))demo=!demo;if(b.hasAttribute('data-guide'))guides=!guides;if(b.hasAttribute('data-grid'))grid=!grid;if(b.hasAttribute('data-finish'))finish();if(b.hasAttribute('data-download'))exportArtwork();if(b.hasAttribute('data-screenshot'))screenshot();sync();}
 function input(e){if(e.target.matches('[data-custom-color]')&&running&&!ended&&!demo){color=e.target.value;if(tool==='move')tool='paint';if(selected&&tool==='paint')mutate(()=>{parts.find(p=>p.id===selected).color=color;customizations++;});else sync();}if(e.target.matches('[data-brush-size]'))brushSize=Number(e.target.value);}
 function key(e){if(!running||ended||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if(e.key==='Delete'&&selected){e.preventDefault();mutate(()=>{parts.find(p=>p.id===selected).placed=false;selected=null;});}if(e.key==='Escape')root?.querySelector('.designer-capture')?.setAttribute('hidden','');}
 function pause(){pointerCancel();running=false;if(root)root.hidden=true;}
 function resume(){if(disposed||ended)return;running=true;if(root)root.hidden=false;resize();}
 function start(){ended=false;running=true;root?.classList.remove('designer-ended');if(root)root.hidden=false;drafts.clear();selectProject(kitId,{reset:true});resize();}
 function destroy(){if(disposed)return;disposed=true;running=false;observer?.disconnect();canvas.removeEventListener('pointerdown',canvasDown);canvas.removeEventListener('arcade-resize',resize);canvas.removeEventListener('arcade-export',exportArtwork);win?.removeEventListener('pointermove',pointerMove);win?.removeEventListener('pointerup',pointerUp);win?.removeEventListener('pointercancel',pointerCancel);win?.removeEventListener('keydown',key);if(root&&originalParent){canvas.classList.remove('designer-canvas');originalParent.insertBefore(canvas,originalNext?.parentElement===originalParent?originalNext:null);root.remove();}}
 if(autoStart)start();
 return {start,pause,resume,destroy,tick(){},draw:render,selectProject,placePart,transformPart,undo,redo,finish,exportArtwork,screenshot,getState:()=>({game:'bubble',project:kit.category,kitId,parts:parts.map(p=>({...p})),strokes:strokes.length,selected,customizations,score,ended,paused:!running,demo,gl:false})};
}
