/** Vector product rendering: local paths, layered finishes and optical/mechanical detail. */
export function mixColor(hex,other='#ffffff',amount=.3){const parse=s=>[1,3,5].map(i=>parseInt(s.slice(i,i+2),16));const a=parse(hex),b=parse(other);return '#'+a.map((v,i)=>Math.round(v+(b[i]-v)*amount).toString(16).padStart(2,'0')).join('');}
const rounded=(c,x,y,w,h,r=8)=>{c.beginPath();c.roundRect(x,y,w,h,r);};
function gradient(c,w,h,color,metal=true){const g=c.createLinearGradient(-w/2,-h/2,w/2,h/2);g.addColorStop(0,mixColor(color,'#ffffff',metal ? .56 : .24));g.addColorStop(.38,color);g.addColorStop(.65,mixColor(color,'#ffffff',.2));g.addColorStop(1,mixColor(color,'#152638',.35));return g;}
function circle(c,x,y,r,fill,stroke=null){c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.stroke();}}
export function renderDesignPart(c,p,{ghost=false,shadow=true}={}){
 c.save();c.translate(p.x,p.y);c.rotate((p.rotation||0)*Math.PI/180);c.scale(p.scale||1,p.scale||1);const w=p.w,h=p.h,color=p.color;c.lineWidth=1.3;c.strokeStyle=mixColor(color,'#142c40',.45);c.fillStyle=gradient(c,w,h,color);if(ghost){c.globalAlpha*=.19;shadow=false;}if(shadow){c.shadowColor='#17253726';c.shadowBlur=10;c.shadowOffsetY=5;}
 switch(p.kind){
 case 'path':{const path=new Path2D(p.path);c.fill(path);c.shadowColor='transparent';c.stroke(path);if(color==='#243e51'||color==='#233f53'){c.save();c.clip(path);c.strokeStyle='#b7e6ff6b';c.lineWidth=5;c.beginPath();c.moveTo(-w*.3,-h/2);c.lineTo(w*.4,h/2);c.stroke();c.restore();}break;}
 case 'round':case 'stripe':case 'window':case 'light':case 'phone-back':{rounded(c,-w/2,-h/2,w,h,p.radius||Math.min(14,w/3,h/3));c.fill();c.shadowColor='transparent';c.stroke();if(p.kind==='phone-back'){c.save();rounded(c,-w/2,-h/2,w,h,24);c.clip();c.strokeStyle='#ffffff18';c.lineWidth=.5;for(let y=-h/2;y<h/2;y+=3){c.beginPath();c.moveTo(-w/2,y);c.lineTo(w/2,y);c.stroke();}c.restore();}if(p.kind==='window'){c.fillStyle='#c2edff88';rounded(c,-w*.3,-h*.35,w*.25,h*.58,2);c.fill();}break;}
 case 'phone-body':{rounded(c,-w/2,-h/2,w,h,29);c.fill();c.shadowColor='transparent';c.strokeStyle=mixColor(color,'#ffffff',.7);c.lineWidth=2;c.stroke();rounded(c,-w/2+3,-h/2+3,w-6,h-6,27);c.strokeStyle=mixColor(color,'#182d39',.45);c.lineWidth=1;c.stroke();for(const y of [-h*.33,h*.33]){c.fillStyle='#d1d9dc';c.fillRect(-w/2,y,5,4);c.fillRect(w/2-5,y,5,4);}break;}
 case 'screen':{rounded(c,-w/2,-h/2,w,h,24);c.fillStyle='#101b2c';c.fill();c.shadowColor='transparent';c.clip();const g=c.createLinearGradient(-w/2,-h/2,w/2,h/2);g.addColorStop(0,'#152849');g.addColorStop(.5,'#376483');g.addColorStop(1,'#b58179');c.fillStyle=g;c.fillRect(-w/2,-h/2,w,h);for(let i=0;i<4;i++){c.beginPath();c.ellipse(w*.28-i*23,25+i*58,w*.72,h*.36,-.65,0,Math.PI*2);const g=c.createLinearGradient(0,-h*.1,0,h*.6);g.addColorStop(0,['#efcfc5','#d7c2dc','#92b5d5','#446585'][i]);g.addColorStop(1,'#152b49');c.fillStyle=g;c.fill();}c.font='300 41px system-ui';c.textAlign='center';c.fillStyle='#ffffffdd';c.fillText('09:41',0,-h*.24);c.font='11px system-ui';c.fillText('SATURDAY, OCTOBER 3',0,-h*.17);break;}
 case 'camera-island':{rounded(c,-w/2,-h/2,w,h,22);c.fill();c.shadowColor='transparent';c.strokeStyle='#ffffff80';c.stroke();break;}
 case 'camera-ring':{circle(c,0,0,w/2,gradient(c,w,h,color),'#e3ebe6');circle(c,0,0,w*.43,'#1b302e','#cbd8cf');circle(c,0,0,w*.38,gradient(c,w,h,'#334947'));c.shadowColor='transparent';c.lineWidth=.5;c.strokeStyle='#ffffff28';for(let i=0;i<72;i++){const a=i*Math.PI/36;c.beginPath();c.moveTo(Math.cos(a)*w*.45,Math.sin(a)*w*.45);c.lineTo(Math.cos(a)*w*.49,Math.sin(a)*w*.49);c.stroke();}break;}
 case 'lens':{circle(c,0,0,w/2,gradient(c,w,h,color),'#d0d6dd');c.shadowColor='transparent';circle(c,0,0,w*.42,'#111820','#718190');circle(c,0,0,w*.32,'#101e2a','#344a59');const g=c.createRadialGradient(-5,-6,1,0,0,w*.3);g.addColorStop(0,'#70afc1');g.addColorStop(.25,'#1e475d');g.addColorStop(.7,'#111e35');g.addColorStop(1,'#1c3451');circle(c,0,0,w*.29,g);circle(c,-w*.1,-w*.12,w*.06,'#94bddeaa');circle(c,w*.12,w*.13,w*.09,'#787bd760');break;}
 case 'flash':circle(c,0,0,w/2,'#f6eccc','#b9afa0');circle(c,0,0,w*.31,'#fff9e6');break;
 case 'sensor':circle(c,0,0,w/2,'#1c2b39','#a5b5bf');circle(c,0,0,w*.2,'#3d6582');break;
 case 'camera-pill':{rounded(c,-w/2,-h/2,w,h,h/2);c.fillStyle='#0c141f';c.fill();circle(c,w*.27,0,4,'#183f57');circle(c,w*.28-1,-1,1,'#6790b6');break;}
 case 'status':{c.shadowColor='transparent';c.fillStyle='#f7f9ff';c.font='600 10px system-ui';c.fillText('9:41',-w/2+3,3);for(let i=0;i<4;i++)c.fillRect(w/2-36+i*4,3-i*2,2,3+i*2);rounded(c,w/2-15,-4,13,7,2);c.strokeStyle='#edf4ff';c.stroke();c.fillRect(w/2-13,-2,8,3);break;}
 case 'icons':{c.shadowColor='transparent';const colors=['#578ae0','#61b298','#a488c9','#c9907e','#5d92ae','#c3984e','#5681a5','#8ab1a5'];for(let i=0;i<8;i++){const x=(i%4-1.5)*33,y=(Math.floor(i/4)-.5)*43;rounded(c,x-12,y-12,24,24,7);c.fillStyle=colors[i];c.fill();c.strokeStyle='#ffffffbd';c.lineWidth=1.6;c.beginPath();c.arc(x,y,5+i%3,0,Math.PI*1.6);c.stroke();}break;}
 case 'volume':{for(const y of [-h*.25,h*.25]){rounded(c,-w/2,y-h*.18,w,h*.36,2);c.fill();}break;}
 case 'speaker':{c.shadowColor='transparent';for(let i=0;i<7;i++)circle(c,(i-3)*5,0,1.3,'#2a3946');break;}
 case 'port':{rounded(c,-w/2,-h/2,w,h,h/2);c.fillStyle='#152330';c.fill();rounded(c,-w/2+5,-1,w-10,2,1);c.fillStyle='#9eb1bf';c.fill();break;}
 case 'case':{c.shadowColor='transparent';rounded(c,-w/2,-h/2,w,h,32);c.strokeStyle='#e8f6f3cc';c.lineWidth=4;c.stroke();c.lineWidth=1;c.strokeStyle='#7d9a9855';c.stroke();break;}
 case 'wordmark':{c.shadowColor='transparent';c.textAlign='center';c.font='600 13px system-ui';c.fillStyle=color;c.fillText('P I K O',0,4);c.font='6px system-ui';c.fillText('DESIGNED BY YOU',0,16);break;}
 case 'wheel':{c.scale(1,h/w);circle(c,0,0,w/2,'#131d29','#263342');c.shadowColor='transparent';circle(c,0,0,w*.43,'#293442');c.lineWidth=1;c.strokeStyle='#546171';for(let i=0;i<36;i++){const a=i*Math.PI/18;c.beginPath();c.moveTo(Math.cos(a)*w*.44,Math.sin(a)*w*.44);c.lineTo(Math.cos(a+.08)*w*.48,Math.sin(a+.08)*w*.48);c.stroke();}circle(c,0,0,w*.34,gradient(c,w,h,color),'#dae0e5');circle(c,0,0,w*.27,'#253445');c.strokeStyle='#bbcbd9';c.lineWidth=5;for(let i=0;i<10;i++){const a=i*Math.PI/5;c.beginPath();c.moveTo(Math.cos(a)*w*.09,Math.sin(a)*w*.09);c.lineTo(Math.cos(a+.17)*w*.29,Math.sin(a+.17)*w*.29);c.stroke();}circle(c,0,0,w*.09,'#718da4','#dce7f2');break;}
 case 'engine':{rounded(c,-w/2,-h/2,w,h,h*.47);c.fill();c.shadowColor='transparent';c.stroke();c.save();c.translate(w*.27,0);c.scale(.48,1);circle(c,0,0,h*.43,'#122435','#738d9f');c.strokeStyle='#899fb1';c.lineWidth=1;for(let i=0;i<16;i++){const a=i*Math.PI/8;c.beginPath();c.moveTo(0,0);c.lineTo(Math.cos(a)*h*.35,Math.sin(a)*h*.35);c.stroke();}circle(c,0,0,h*.07,'#a5b8c9');c.restore();c.strokeStyle='#ffffff88';c.beginPath();c.moveTo(-w*.32,-h*.25);c.lineTo(w*.13,-h*.25);c.stroke();break;}
 case 'gear':{c.fillStyle='#586d7e';c.fillRect(-3,-h/2,6,h*.8);circle(c,-w*.24,h*.31,w*.22,'#172a39');circle(c,w*.24,h*.31,w*.22,'#172a39');circle(c,-w*.24,h*.31,w*.08,'#97afc3');circle(c,w*.24,h*.31,w*.08,'#97afc3');break;}
 case 'door':{rounded(c,-w/2,-h/2,w,h,10);c.shadowColor='transparent';c.strokeStyle=mixColor(color,'#172c3d',.4);c.lineWidth=1.5;c.stroke();c.strokeStyle=mixColor(color,'#ffffff',.5);c.beginPath();c.moveTo(-w/2+6,h*.2);c.lineTo(w/2-6,h*.2);c.stroke();break;}
 case 'mirror':{rounded(c,-w/2,-h/2,w,h,Math.min(w,h)*.35);c.fill();c.shadowColor='transparent';rounded(c,-w*.3,-h*.32,w*.6,h*.55,3);c.fillStyle=gradient(c,w,h,'#7195ab');c.fill();break;}
 case 'headlight':{rounded(c,-w/2,-h/2,w,h,Math.min(h/2,8));c.fillStyle='#162a3c';c.fill();c.shadowColor='#a4e7ff66';c.shadowBlur=8;c.strokeStyle='#e9fcff';c.lineWidth=3;c.beginPath();c.moveTo(-w*.35,0);c.lineTo(w*.35,0);c.stroke();c.lineWidth=1;for(let i=0;i<5;i++){c.beginPath();c.moveTo(-w*.3+i*w*.15,-h*.25);c.lineTo(-w*.3+i*w*.15,h*.25);c.stroke();}break;}
 case 'vent':{rounded(c,-w/2,-h/2,w,h,5);c.fillStyle='#182a3a';c.fill();c.shadowColor='transparent';c.strokeStyle='#536c7b';c.lineWidth=1;for(let y=-h*.35;y<h*.4;y+=5){c.beginPath();c.moveTo(-w*.4,y);c.lineTo(w*.4,y);c.stroke();}break;}
 case 'spoiler':{c.fillStyle=color;c.fillRect(-w*.25,0,7,h*.5);c.fillRect(w*.25,0,7,h*.5);rounded(c,-w/2,-h*.3,w,h*.3,5);c.fill();c.strokeStyle='#8fa3b266';c.beginPath();c.moveTo(-w*.45,-h*.24);c.lineTo(w*.45,-h*.24);c.stroke();break;}
 case 'exhaust':{for(const x of [-w*.24,w*.24]){rounded(c,x-w*.2,-h/2,w*.4,h,h/2);c.fillStyle='#b0c0ce';c.fill();rounded(c,x-w*.15,-h*.3,w*.3,h*.6,h/3);c.fillStyle='#172634';c.fill();}break;}
 case 'badge':{circle(c,0,0,Math.min(w,h)/2,color);c.shadowColor='transparent';c.fillStyle='#172c3d';c.textAlign='center';c.font=`700 ${h*.45}px system-ui`;c.fillText('7',0,h*.17);break;}
 case 'cargo':{rounded(c,-w/2,-h/2,w,h,7);c.fill();c.shadowColor='transparent';c.stroke();c.strokeStyle='#809aad66';c.lineWidth=1;for(let x=-w*.46;x<w*.5;x+=15){c.beginPath();c.moveTo(x,-h*.43);c.lineTo(x,h*.43);c.stroke();}c.fillStyle='#99b0c1';c.fillRect(-w/2,h/2-8,w,8);break;}
 case 'locks':{c.fillStyle=color;for(const x of [-w*.3,w*.3]){c.fillRect(x-1,-h/2,3,h);for(const y of [-h*.36,h*.32]){rounded(c,x-5,y-4,11,8,2);c.fill();}}break;}
 case 'cargo-mark':{c.shadowColor='transparent';c.strokeStyle=color;c.lineWidth=5;c.beginPath();c.moveTo(-w*.4,-h*.1);c.lineTo(w*.08,-h*.1);c.lineTo(-w*.08,-h*.35);c.moveTo(w*.08,-h*.1);c.lineTo(-w*.08,h*.17);c.stroke();c.fillStyle=color;c.textAlign='center';c.font='600 16px system-ui';c.fillText('PIKO CARGO',0,h*.4);break;}
 case 'rack':{c.fillStyle=color;c.fillRect(-w/2,-h/2,w,5);for(const x of [-w*.38,w*.38])c.fillRect(x,-h/2,8,h);break;}
 }
 c.restore();
}
export function designTransform(width,height,kit){const b=kit.bounds,s=Math.min((width-40)/b.w,(height-64)/b.h);return {scale:Math.max(.05,s),x:(width-b.w*s)/2-b.x*s,y:(height-b.h*s)/2-b.y*s};}
export function renderDesignScene(c,{kit,parts,strokes=[],selected=null,grid=true,ghosts=true,demo=false,clean=false},width,height){
 c.save();c.fillStyle='#f5f7fa';c.fillRect(0,0,width,height);if(!clean&&grid){c.strokeStyle='#dce3ed';c.lineWidth=.5;for(let x=20;x<width;x+=24){c.beginPath();c.moveTo(x,0);c.lineTo(x,height);c.stroke();}for(let y=20;y<height;y+=24){c.beginPath();c.moveTo(0,y);c.lineTo(width,y);c.stroke();}}
 const t=designTransform(width,height,kit);c.translate(t.x,t.y);c.scale(t.scale,t.scale);
 const ordered=[...parts].sort((a,b)=>a.z-b.z);if(ghosts&&!clean&&!demo)for(const p of ordered)if(!p.placed)renderDesignPart(c,{...p,x:p.tx,y:p.ty,rotation:0,scale:1},{ghost:true,shadow:false});
 for(const p of ordered)if(p.placed||demo)renderDesignPart(c,demo?{...p,x:p.tx,y:p.ty,rotation:0,scale:1}:p);

 if(strokes.length&&c.canvas?.ownerDocument){const layer=c.canvas.ownerDocument.createElement('canvas');layer.width=Math.ceil(width);layer.height=Math.ceil(height);const ink=layer.getContext('2d');ink.translate(t.x,t.y);ink.scale(t.scale,t.scale);for(const stroke of strokes){ink.globalCompositeOperation=stroke.erase?'destination-out':'source-over';ink.strokeStyle=stroke.color;ink.lineWidth=stroke.size;ink.lineCap='round';ink.lineJoin='round';ink.beginPath();stroke.points.forEach((p,i)=>i?ink.lineTo(p.x,p.y):ink.moveTo(p.x,p.y));ink.stroke();}c.save();c.translate(-t.x/t.scale,-t.y/t.scale);c.scale(1/t.scale,1/t.scale);c.drawImage(layer,0,0);c.restore();}

 if(selected&&!clean&&!demo){const p=parts.find(p=>p.id===selected&&p.placed);if(p){c.save();c.translate(p.x,p.y);c.rotate((p.rotation||0)*Math.PI/180);c.scale(p.scale||1,p.scale||1);c.strokeStyle='#c98c48';c.lineWidth=1.5/t.scale;c.setLineDash([5/t.scale,4/t.scale]);c.strokeRect(-p.w/2-5,-p.h/2-5,p.w+10,p.h+10);c.setLineDash([]);c.fillStyle='#c98c48';for(const x of [-p.w/2-5,p.w/2+5])for(const y of [-p.h/2-5,p.h/2+5])c.fillRect(x-3/t.scale,y-3/t.scale,6/t.scale,6/t.scale);c.restore();}}
 c.restore();if(!clean){c.fillStyle='#8795a7';c.font='10px system-ui';c.textAlign='left';c.fillText('PIKO / PRODUCT DESIGN STUDIO',18,height-15);c.textAlign='right';c.fillText('FRONT / REAR',width-18,height-15);}
 return t;
}
export function thumbnail(doc,kit,part=null){const canvas=doc.createElement('canvas');canvas.width=180;canvas.height=100;const c=canvas.getContext('2d');if(part){c.fillStyle='#edf1f6';c.fillRect(0,0,180,100);const s=Math.min(144/part.w,74/part.h);c.translate(90,50);c.scale(s,s);renderDesignPart(c,{...part,x:0,y:0},{shadow:false});}else renderDesignScene(c,{kit,parts:kit.parts,demo:true,grid:false,clean:true},180,100);return canvas.toDataURL('image/png');}
