export const ARCADE_TEXT={
 zh:{title:'闯关群岛 · 冒险没有尽头',tag:'挑一座岛，出发去冒险吧！',play:'进入岛屿',resume:'继续闯关',stage:'关卡',best:'最远关卡',coins:'星币',shop:'冒险商店',back:'返回小镇',next:'下一关',retry:'再来一次',jump:'跳跃',rotateLeft:'镜头向左转',rotateRight:'镜头向右转',camera:'镜头复位',controls:'WASD / 方向键移动 · 空格跳跃 · 拖动旋转视角 · 滚轮缩放',touch:'按住方向键移动，点「跳跃」。左右镜头按钮可转向。',guide:'自动带路',guideNote:'点答案按钮会带角色前往对应平台；也可以亲自走过去。',correct:'过关啦！',wrong:'再仔细看看。',fall:'回到存档点，再来一次！',over:'先歇一会儿，再挑战这一关。',hearts:'剩余机会',streak:'连续答对',earned:'获得',hint:'用一张提示卡',hintEmpty:'去商店换提示卡吧',watch:'先记住颜色顺序',repeat:'现在照顺序踩上地板',replay:'再看一次',memoryStep:'已走对',saved:'每座岛的进度分开保存，随时回来接着玩。',owned:'已拥有',buy:'换购',equip:'戴上',equipped:'戴着呢',remove:'摘下配饰',empty:'星币不够',bag:'我的道具',characters:'选一个 3D 角色',drag:'拖动角色可以转着看',selected:'使用中',skins:'六个角色随便选',shoes:'走路永远变快。',spring:'跳得永远更高。',backpack:'在小镇和小游戏里背上背包。',crown:'在小镇和小游戏里戴上王冠。',shield:'答错时自动用掉一枚，机会和连续答对都不会少。',hintDescription:'告诉你这道题该怎么想。',savedRun:'这一关已经存好。数学和英语难度从下一关开始生效。',webgl:'3D 小镇需要 WebGL 2。请在浏览器里打开硬件加速，然后刷新页面。',loading:'3D 小镇搭建中…',settings:'角色和难度',portal:'闯关群岛',returnHelp:'小店的故事还能接着玩；每座闯关岛都会不断出现新关卡。',modes:{obby:['数学跳跳岛','跳过浮空平台，落在正确答案上。','跳台 · 数学'],tower:['数字登高塔','逐层向上跳跃，解题点亮下一层。','高塔 · 数学'],runner:['单词闯关门','看懂英文，躲开障碍，冲进图案对的那扇门。','跑酷 · 英语'],memory:['翻翻记忆格','记住英文颜色的顺序，照着顺序踩地板。','记忆 · 英语'],garden:['欢乐小农场','读订单、算收成，每一关种出新作物。','农场 · 数学＋英语']}},
 en:{title:'Quest Islands · Endless Adventures',tag:'Pick an island and set off on your next adventure!',play:'Enter island',resume:'Continue',stage:'Stage',best:'Best stage',coins:'Star coins',shop:'Adventure shop',back:'Back to town',next:'Next stage',retry:'Try again',jump:'Jump',rotateLeft:'Rotate camera left',rotateRight:'Rotate camera right',camera:'Reset camera',controls:'WASD / arrows to move · Space to jump · Drag to orbit · Scroll to zoom',touch:'Hold an arrow to move. Tap Jump. Use camera arrows to turn.',guide:'Guide me',guideNote:'Answer buttons guide your character to a platform. You can also walk there yourself.',correct:'Stage clear!',wrong:'Have another look!',fall:'Back to the checkpoint. Try again!',over:'Take a breather, then try this stage again.',hearts:'Tries left',streak:'Streak',earned:'Earned',hint:'Use a hint card',hintEmpty:'Get hint cards at the shop',watch:'Remember the colour order',repeat:'Now step on the colours in order',replay:'Watch again',memoryStep:'Steps done',saved:'Each island saves your progress. Come back anytime!',owned:'Owned',buy:'Get',equip:'Wear',equipped:'Wearing',remove:'Take off',empty:'Not enough coins',bag:'My items',characters:'Pick a 3D character',drag:'Drag to spin your character',selected:'Selected',skins:'All six characters are free!',shoes:'Walk faster – for good!',spring:'Jump higher – for good!',backpack:'Wear a backpack in town and in games.',crown:'Wear a crown in town and in games.',shield:'Used up automatically when you get one wrong, so you keep your tries and your streak.',hintDescription:'Shows you how to think about this question.',savedRun:'Stage saved. New difficulty starts next stage.',webgl:'The 3D town needs WebGL 2. Turn on hardware acceleration in your browser and reload.',loading:'Building your 3D town…',settings:'Character & difficulty',portal:'Quest Islands',returnHelp:'Carry on with the shop story, or visit an island for never-ending new challenges.',modes:{obby:['Maths Hop Islands','Jump across floating platforms and land on the right answer.','PARKOUR · MATHS'],tower:['Number Climb','Climb higher and solve a problem on every floor.','TOWER · MATHS'],runner:['Word Dash','Read the word, dodge the obstacles and run through the matching picture gate.','RUN · ENGLISH'],memory:['Tile Recall','Remember the English colours and step on them in order.','MEMORY · ENGLISH'],garden:['Happy Harvest','Read orders, count your harvest and grow new crops each stage.','FARM · MATHS + ENGLISH']}},
 ja:{title:'ぼうけんじま · まだまだつづくよ',tag:'すきなしまをえらんで、つぎのぼうけんへ！',play:'島へ行く',resume:'つづきから',stage:'ステージ',best:'さいこうステージ',coins:'スターコイン',shop:'ぼうけんショップ',back:'まちにもどる',next:'つぎのステージ',retry:'もういちど',jump:'ジャンプ',rotateLeft:'カメラを左へ',rotateRight:'カメラを右へ',camera:'カメラをもとにもどす',controls:'WASD / 矢印で移動 · スペースでジャンプ · ドラッグで視点回転 · ホイールでズーム',touch:'矢印を押して移動。ジャンプをタップ。カメラの矢印で向きを変えます。',guide:'道案内',guideNote:'答えのボタンでキャラクターを案内できます。自分で歩いて選ぶこともできます。',correct:'クリア！',wrong:'もういちど よく見てみよう。',fall:'チェックポイントから、もういちど！',over:'ひと休みして、このステージにもういちどチャレンジ！',hearts:'のこりチャレンジ',streak:'れんぞくせいかい',earned:'ゲット',hint:'ヒントカードをつかう',hintEmpty:'ショップでヒントカードをゲットしよう',watch:'いろのじゅんばんをおぼえよう',repeat:'おなじじゅんばんで、いろのゆかにのろう',replay:'もういちど見る',memoryStep:'できたステップ',saved:'しまごとにきろくをほぞん。いつでもつづきからあそべるよ。',owned:'もってる',buy:'ゲット',equip:'つける',equipped:'つけてる',remove:'かざりをはずす',empty:'コインがたりない',bag:'もちもの',characters:'3Dキャラをえらぶ',drag:'ドラッグでキャラをくるっと回せるよ',selected:'えらんでいる',skins:'6人とも、すきにえらべるよ',shoes:'歩くのがずっとはやくなる！',spring:'ジャンプがずっと高くなる！',backpack:'まちやゲームでリュックをせおえるよ。',crown:'まちやゲームでおうかんをかぶれるよ。',shield:'まちがえたとき 1まいつかって、チャレンジとれんぞくせいかいをまもるよ。',hintDescription:'いまのもんだいの かんがえかたを見せてくれるよ。',savedRun:'このステージをほぞんしたよ。むずかしさは つぎのステージからかわるよ。',webgl:'3DのまちにはWebGL 2がひつようです。ブラウザーのハードウェアアクセラレーションをオンにして、ページを読みこみなおしてね。',loading:'3Dのまちをつくっているよ…',settings:'キャラとむずかしさ',portal:'ぼうけんじま',returnHelp:'おみせのおはなしもつづけられるよ。ぼうけんじまでは、あたらしいステージがどんどん出てくるよ。',modes:{obby:['ぴょんさんすう','空の足場をジャンプして、正しい答えに着地。','アスレチック · さんすう'],tower:['のぼれ！タワー','ジャンプで登って、各階の問題を解こう。','タワー · さんすう'],runner:['えいごダッシュ','えいごを読んで、しょうがいぶつをよけて、正しい絵のゲートへ！','ラン · えいご'],memory:['おぼえてタイル','えいごのいろのじゅんばんをおぼえて、同じじゅんに歩こう。','きおく · えいご'],garden:['わくわくはたけ','ちゅうもんを読んで、しゅうかくをけいさん。あたらしいやさいをそだてよう。','はたけ · さんすう＋えいご']}}
};

const cameraText={
 zh:{firstPerson:'第一人称',thirdPerson:'第三人称',switchFirst:'切换到第一人称（V）',switchThird:'切换到第三人称（V）',guide:'自己操作',guideNote:'答案只是标记。用方向键走、按空格或跳跃键起跳，自己跳到正确的平台上。',controls:'WASD / 方向键移动 · 空格跳跃 · V 切换视角 · 拖动观察',touch:'按住方向键移动，点击跳跃。拖动场景转头，视角按钮切换第一／第三人称。'},
 en:{firstPerson:'First person',thirdPerson:'Third person',switchFirst:'Switch to first person (V)',switchThird:'Switch to third person (V)',guide:'Move yourself',guideNote:'The answers are just labels. Walk with the arrows and jump with Space or the Jump button to reach the right platform.',controls:'WASD / arrows · Space to jump · V switches view · Drag to look',touch:'Hold arrows to move, tap Jump, and drag to look. The view button switches first / third person.'},
 ja:{firstPerson:'一人称',thirdPerson:'三人称',switchFirst:'一人称に切り替え（V）',switchThird:'三人称に切り替え（V）',guide:'じぶんでうごかす',guideNote:'こたえは目じるしだよ。やじるしで歩いて、スペースかジャンプボタンで正しい足場へとぼう。',controls:'WASD / 矢印で移動 · スペースでジャンプ · V で視点切替 · ドラッグで見回す',touch:'矢印を押して移動、ジャンプをタップ。ドラッグで見回し、視点ボタンで一人称／三人称を切り替えます。'}
};
for(const lang of Object.keys(cameraText))Object.assign(ARCADE_TEXT[lang],cameraText[lang]);
ARCADE_TEXT.zh.modes.obby[1]='浮空平台大小、间距、方向都不一样，跳到正确答案上！';
ARCADE_TEXT.zh.modes.tower[1]='台阶忽高忽低、有宽有窄，自己跳上去解题！';
ARCADE_TEXT.en.modes.obby[1]='Hop across floating islands of every size and spacing to land on the right answer.';
ARCADE_TEXT.en.modes.tower[1]='Climb a twisty tower of tall, short, wide and narrow steps.';
ARCADE_TEXT.ja.modes.obby[1]='大きさやばしょがかわる足場をジャンプして、正しいこたえへ！';
ARCADE_TEXT.ja.modes.tower[1]='高さもはばもバラバラのルートを、ジャンプでのぼろう！';

Object.assign(ARCADE_TEXT.zh,{districtTip:'沿路向南走进游戏街区 · 进入建筑选择游戏',play:'开始游戏'});
Object.assign(ARCADE_TEXT.en,{districtTip:'Walk south along the road · Enter a building to play',play:'Play'});
Object.assign(ARCADE_TEXT.ja,{districtTip:'道を南へ · 建物に入ってゲームを選ぼう',play:'あそぶ'});

Object.assign(ARCADE_TEXT.zh,{districtPark:'果园区',districtDojo:'忍者道场',districtAlley:'游戏街',districtTrack:'夜间赛道',districtLearn:'学习街',districtPlaza:'广场',districtTip:'点地面或用方向键逛逛，走近建筑就能进去。',firstPerson:'第一人称',thirdPerson:'第三人称',switchFirst:'切换成第一人称',switchThird:'切换成第三人称',hardVenue:'高手挑战馆'});
Object.assign(ARCADE_TEXT.en,{districtPark:'Orchard',districtDojo:'Ninja Dojo',districtAlley:'Arcade Alley',districtTrack:'Night Track',districtLearn:'Learning Lane',districtPlaza:'Plaza',districtTip:'Tap the ground or use the arrows to explore. Walk up to a building to go in.',firstPerson:'My view',thirdPerson:'Follow view',switchFirst:'Switch to my view',switchThird:'Switch to follow view',hardVenue:'Challenge Hall'});
Object.assign(ARCADE_TEXT.ja,{districtPark:'くだものばたけ',districtDojo:'にんじゃどうじょう',districtAlley:'ゲームよこちょう',districtTrack:'ナイトコース',districtLearn:'まなびどおり',districtPlaza:'ひろば',districtTip:'じめんをタップするか やじるしキーで たんけん。ちかづいたら たてものに入れるよ。',firstPerson:'じぶん目線',thirdPerson:'うしろから',switchFirst:'じぶん目線にする',switchThird:'うしろからにする',hardVenue:'チャレンジかいじょう'});

Object.assign(ARCADE_TEXT.zh,{touch:'左下摇杆：上下走、左右转；拖动画面看四周。右下按钮跳跃，开飞机时按住 ↑ / ↓ 升降。',controls:'摇杆走路转向 · WASD / 方向键 · 空格跳跃 / 上升 · Shift 下降 · V 换视角'});
Object.assign(ARCADE_TEXT.en,{touch:'Left stick: move and steer. Drag the screen to look around. Tap Jump – in a plane, hold ↑ / ↓ to go up or down.',controls:'Stick to move & steer · WASD / arrows · Space: jump / up · Shift: down · V: change view'});
Object.assign(ARCADE_TEXT.ja,{touch:'左のスティックで歩く・まがる。画面をドラッグで見まわす。右下でジャンプ、ひこうきは ↑ / ↓ でのぼる・おりる。',controls:'スティックで歩く・まがる · WASD / やじるし · スペース：ジャンプ／のぼる · Shift：おりる · V：見かたをかえる'});
