export const ARCADE_TEXT={
 zh:{title:'学习群岛 · 无限冒险',tag:'选一座岛，开始你的下一次冒险',play:'进入岛屿',resume:'继续挑战',stage:'关卡',best:'最高关卡',coins:'星币',shop:'冒险商店',back:'返回小镇',next:'下一关',retry:'再试一次',jump:'跳跃',rotateLeft:'向左旋转镜头',rotateRight:'向右旋转镜头',camera:'重置镜头',controls:'WASD / 方向键移动 · 空格跳跃 · 拖动旋转视角 · 滚轮缩放',touch:'按住方向键移动，点「跳跃」。左右镜头按钮可转向。',guide:'自动带路',guideNote:'点答案按钮会带角色前往对应平台；也可以亲自走过去。',correct:'挑战成功！',wrong:'再观察一下。',fall:'回到检查点，再来一次！',over:'休息一下，再挑战同一关。',hearts:'练习机会',streak:'连胜',earned:'获得',hint:'使用提示卡',hintEmpty:'在商店兑换提示卡',watch:'先记住颜色的顺序',repeat:'现在按顺序走上地板',replay:'再看一次',memoryStep:'已完成步骤',saved:'各岛进度独立保存，随时回来继续。',owned:'已拥有',buy:'兑换',equip:'佩戴',equipped:'已佩戴',remove:'取下配饰',empty:'星币不足',bag:'我的道具',characters:'选择 3D 角色',drag:'拖动角色可旋转查看',selected:'正在使用',skins:'六种角色均可自由选择',shoes:'永久提升移动速度。',spring:'永久提升跳跃高度。',backpack:'在小镇和小游戏中显示背包。',crown:'在小镇和小游戏中显示王冠。',shield:'答错时自动消耗一枚，保留机会与连胜。',hintDescription:'显示当前题目的解题提示。',savedRun:'已保留本关。数学与英语难度在下一关生效。',webgl:'3D 场景需要 WebGL 2。请开启浏览器硬件加速后刷新页面。',loading:'正在搭建 3D 小镇…',settings:'角色与难度',portal:'学习群岛',returnHelp:'原有小店故事仍可继续；每座学习岛都能持续生成新关卡。',modes:{obby:['数学跳岛','跳过浮空平台，落在正确答案上。','OBBY · MATH'],tower:['算术攀塔','逐层向上跳跃，解题点亮下一层。','TOWER · MATH'],runner:['英语传送门','读懂英文，躲开障碍，进入正确图案的门。','RUN · ENGLISH'],memory:['记忆地板','记住英文颜色序列，按顺序踏上地板。','MEMORY · ENGLISH'],garden:['双语农场','读订单、算收成，每关种出新的作物。','FARM · MATH + ENGLISH']}},
 en:{title:'Learning islands · Endless adventures',tag:'Choose an island. Start a new adventure.',play:'Enter island',resume:'Continue',stage:'Stage',best:'Best stage',coins:'Coins',shop:'Adventure shop',back:'Back to town',next:'Next stage',retry:'Try again',jump:'Jump',rotateLeft:'Rotate camera left',rotateRight:'Rotate camera right',camera:'Reset camera',controls:'WASD / arrows to move · Space to jump · Drag to orbit · Scroll to zoom',touch:'Hold an arrow to move. Tap Jump. Use camera arrows to turn.',guide:'Guide me',guideNote:'Answer buttons guide your character to a platform. You can also walk there yourself.',correct:'Stage cleared!',wrong:'Take another look.',fall:'Back to the checkpoint. Try again!',over:'Take a breath. Try this stage again.',hearts:'Attempts',streak:'Streak',earned:'Earned',hint:'Use hint card',hintEmpty:'Get hint cards in the shop',watch:'Remember the color sequence',repeat:'Now step on the colors in order',replay:'Watch again',memoryStep:'Steps completed',saved:'Each island saves its own progress. Come back anytime.',owned:'Owned',buy:'Exchange',equip:'Wear',equipped:'Wearing',remove:'Remove accessory',empty:'Not enough coins',bag:'My items',characters:'Choose a 3D character',drag:'Drag the character to rotate',selected:'Selected',skins:'All six characters are free to choose',shoes:'Permanently increases walking speed.',spring:'Permanently increases jump height.',backpack:'Shows a backpack in town and games.',crown:'Shows a crown in town and games.',shield:'Automatically protects an attempt and streak after a wrong answer.',hintDescription:'Reveals an explanation for this challenge.',savedRun:'Stage saved. Difficulty changes take effect next stage.',webgl:'The 3D world needs WebGL 2. Enable browser hardware acceleration and reload.',loading:'Building your 3D town…',settings:'Character & difficulty',portal:'Learning islands',returnHelp:'Continue the original shop story, or visit an island for endlessly generated challenges.',modes:{obby:['Math sky islands','Jump across floating platforms and land on the right answer.','OBBY · MATH'],tower:['Number tower','Climb higher and solve a problem on every floor.','TOWER · MATH'],runner:['English portals','Read the request, avoid obstacles, enter the matching picture gate.','RUN · ENGLISH'],memory:['Memory floor','Remember English colors and step on them in order.','MEMORY · ENGLISH'],garden:['Bilingual farm','Read orders, calculate harvests and grow new crops each stage.','FARM · MATH + ENGLISH']}},
 ja:{title:'まなびの島 · ずっと冒険',tag:'好きな島を選んで、次の冒険へ。',play:'島へ行く',resume:'つづきから',stage:'ステージ',best:'最高ステージ',coins:'コイン',shop:'ぼうけんショップ',back:'町にもどる',next:'次のステージ',retry:'もう一度',jump:'ジャンプ',rotateLeft:'カメラを左へ',rotateRight:'カメラを右へ',camera:'カメラをもどす',controls:'WASD / 矢印で移動 · スペースでジャンプ · ドラッグで視点回転 · ホイールでズーム',touch:'矢印を押して移動。ジャンプをタップ。カメラの矢印で向きを変えます。',guide:'道案内',guideNote:'答えのボタンでキャラクターを案内できます。自分で歩いて選ぶこともできます。',correct:'クリア！',wrong:'もう一度よく見よう。',fall:'チェックポイントから、もう一度！',over:'ひと休みして、同じステージに挑戦しよう。',hearts:'チャレンジ回数',streak:'連続クリア',earned:'獲得',hint:'ヒントカードを使う',hintEmpty:'ショップでヒントカードを交換',watch:'色の順番をおぼえよう',repeat:'同じ順番で色の床に乗ろう',replay:'もう一度見る',memoryStep:'できた手順',saved:'島ごとに進み具合を保存。いつでも続けられます。',owned:'持っています',buy:'交換',equip:'つける',equipped:'つけています',remove:'かざりを外す',empty:'コインが足りません',bag:'持ちもの',characters:'3D キャラクターを選ぶ',drag:'ドラッグでキャラクターを回転',selected:'選択中',skins:'6人とも自由に選べます',shoes:'歩く速さがずっとアップ。',spring:'ジャンプの高さがずっとアップ。',backpack:'町とゲームでリュックを表示。',crown:'町とゲームで王冠を表示。',shield:'まちがえたときに1枚使って、回数と連続記録を守ります。',hintDescription:'いまの問題の考え方を表示。',savedRun:'このステージを保存しました。難易度は次のステージから変わります。',webgl:'3D の町には WebGL 2 が必要です。ブラウザーのハードウェアアクセラレーションを有効にして再読み込みしてください。',loading:'3D の町をつくっています…',settings:'キャラクターと難易度',portal:'まなびの島',returnHelp:'お店の物語もつづけられます。学習の島では新しいステージをずっと作り出します。',modes:{obby:['算数スカイアイランド','空の足場をジャンプして、正しい答えに着地。','OBBY · MATH'],tower:['数字タワー','ジャンプで登って、各階の問題を解こう。','TOWER · MATH'],runner:['英語のゲート','英語を読み、障害物をよけて正しい絵の門へ。','RUN · ENGLISH'],memory:['メモリーフロア','英語の色の順番をおぼえて、同じ順に歩こう。','MEMORY · ENGLISH'],garden:['バイリンガル農場','注文を読んで収穫を計算。新しい作物を育てよう。','FARM · MATH + ENGLISH']}}
};

const cameraText={
 zh:{firstPerson:'第一人称',thirdPerson:'第三人称',switchFirst:'切换到第一人称（V）',switchThird:'切换到第三人称（V）',guide:'手动操作',guideNote:'答案只作提示。用方向键移动、空格或跳跃按钮起跳，亲自到达正确平台。',controls:'WASD / 方向键移动 · 空格跳跃 · V 切换视角 · 拖动观察',touch:'按住方向键移动，点击跳跃。拖动场景转头，视角按钮切换第一／第三人称。'},
 en:{firstPerson:'First person',thirdPerson:'Third person',switchFirst:'Switch to first person (V)',switchThird:'Switch to third person (V)',guide:'Manual controls',guideNote:'Answers are labels only. Move with the arrows and jump with Space or the Jump button to reach the correct platform yourself.',controls:'WASD / arrows · Space to jump · V switches view · Drag to look',touch:'Hold arrows to move, tap Jump, and drag to look. The view button switches first / third person.'},
 ja:{firstPerson:'一人称',thirdPerson:'三人称',switchFirst:'一人称に切り替え（V）',switchThird:'三人称に切り替え（V）',guide:'手動操作',guideNote:'答えは表示だけです。矢印で移動し、スペースかジャンプボタンで正しい足場へ自分で跳ぼう。',controls:'WASD / 矢印で移動 · スペースでジャンプ · V で視点切替 · ドラッグで見回す',touch:'矢印を押して移動、ジャンプをタップ。ドラッグで見回し、視点ボタンで一人称／三人称を切り替えます。'}
};
for(const lang of Object.keys(cameraText))Object.assign(ARCADE_TEXT[lang],cameraText[lang]);
ARCADE_TEXT.zh.modes.obby[1]='随机大小、间距和走向的浮空台阶，跳到正确答案上。';
ARCADE_TEXT.zh.modes.tower[1]='随机高度与宽窄的上升路线，亲自起跳、落地解题。';
ARCADE_TEXT.en.modes.obby[1]='Jump across islands with randomized sizes, spacing and turns to reach the right answer.';
ARCADE_TEXT.en.modes.tower[1]='Climb a randomized route with changing heights and platform widths.';
ARCADE_TEXT.ja.modes.obby[1]='大きさ・間隔・向きが変わる足場を跳んで、正しい答えへ。';
ARCADE_TEXT.ja.modes.tower[1]='高さや幅が変わるランダムなルートを、自分でジャンプして登ろう。';
