import {MODES,AVATARS,ITEMS,startRun,questionFor,answerRun,nextStage,retryStage,buyItem,useHint} from './ArcadeRules.mjs?v=2';
import {ARCADE_TEXT} from './ArcadeText.mjs?v=2';
import {previewAvatar} from './Models3D.mjs?v=2';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createExpansion({state,scene,persist,refresh,shell,close,getLocale}){
 const w=()=>ARCADE_TEXT[getLocale()],name=o=>o[getLocale()]||o.en;let active=null,feedback='',previewDispose=null,watchStart=null,watchIndex=-1;
 const $=id=>document.getElementById(id),root=document.createElement('section');root.className='islands-section';root.id='learning-islands';$('save-status').before(root);
 const panel=document.createElement('aside');panel.className='arcade-panel';panel.hidden=true;document.querySelector('.town-layout').append(panel);
 const worldTask=document.createElement('div');worldTask.className='world-task';worldTask.hidden=true;document.querySelector('.world-card').append(worldTask);
 const controls=document.createElement('div');controls.className='camera-controls';controls.innerHTML='<button type="button" data-camera="left">↶</button><button type="button" data-camera="right">↷</button><button type="button" data-camera="reset">⌖</button><button type="button" data-camera="view" class="view-toggle"></button><button type="button" data-camera="jump" class="jump-button">↑</button>';document.querySelector('.world-controls').append(controls);
 controls.onclick=e=>{const k=e.target.closest('[data-camera]')?.dataset.camera;if(k==='jump'){if(e.detail===0)scene.jump();$('town-canvas').focus({preventScroll:true});}if(k==='left')scene.orbit(-.35);if(k==='right')scene.orbit(.35);if(k==='reset')scene.resetCamera();if(k==='view')scene.toggleView();if(k)$('town-canvas').focus({preventScroll:true});};
 controls.querySelector('[data-camera="jump"]').addEventListener('pointerdown',e=>{e.preventDefault();scene.jump();});
 function disposePreview(){previewDispose?.();previewDispose=null;}
 function renderCards(){
  root.innerHTML=`<div class="islands-heading"><div><p class="eyebrow">PIKO PLAY · 3D WORLDS</p><h2>${w().title}</h2><p>${w().tag}</p></div><button type="button" class="primary" data-arcade-shop>🎒 ${w().shop}</button></div><div class="island-grid">${MODES.map((id,i)=>{const m=w().modes[id],r=state.expansion.runs[id];return `<article class="island-card island-${id}"><div class="island-art" aria-hidden="true"><div class="island-cube"></div><span>${['＋','×','ABC','▦','🌱'][i]}</span><b>0${i+1} / ∞</b></div><div class="island-copy"><small>${m[2]}</small><h3>${m[0]}</h3><p>${m[1]}</p><div class="island-record">${w().best} <b>${state.expansion.best[id]||0}</b></div><button type="button" data-game="${id}">${r?`${w().resume} · ${w().stage} ${r.stage}`:w().play} <span>↗</span></button></div></article>`;}).join('')}</div><p class="muted">${w().saved}</p>`;
  const view=controls.querySelector('[data-camera="view"]');view.textContent=scene.viewMode==='first'?w().firstPerson:w().thirdPerson;view.setAttribute('aria-pressed',String(scene.viewMode==='first'));view.setAttribute('aria-label',scene.viewMode==='first'?w().switchThird:w().switchFirst);$('walk-tip').textContent=w().controls;for(const [key,label]of [['left','rotateLeft'],['right','rotateRight'],['reset','camera'],['jump','jump']]){const b=controls.querySelector(`[data-camera="${key}"]`);b.setAttribute('aria-label',w()[label]);if(key==='jump')b.textContent='↑ '+w().jump;}
 }
 function hud(){if(!active)return;const r=state.expansion.runs[active],q=questionFor(r),watching=watchStart!==null;
  panel.innerHTML=`<div class="arcade-top"><span class="eyebrow">${w().modes[active][2]}</span><button type="button" data-exit-game aria-label="${w().back}">×</button></div><h2>${w().modes[active][0]}</h2><div class="arcade-stats"><b>${w().stage} ${r.stage}</b><span aria-label="${w().hearts}: ${r.hearts}">${'♥'.repeat(r.hearts)}${'♡'.repeat(3-r.hearts)}</span><small>${w().streak} ${r.streak}</small></div><p class="arcade-question" id="arcade-question" ${active==='runner'||active==='garden'?'lang="en"':''}>${active==='memory'?(watching?w().watch:w().repeat):esc(q.question)}</p>${active==='memory'?`<div id="memory-cue" class="memory-cue" aria-live="polite">${watching?'…':`${w().memoryStep} ${r.memoryIndex} / ${q.sequence.length}`}</div>`:''}<p class="arcade-feedback ${r.solved?'success':''}" id="arcade-feedback" role="status">${esc(feedback|| (r.solved?w().correct:r.hearts===0?w().over:''))}</p>${r.hinted?`<p class="hint-box">${esc(q.explanation)}</p>`:''}${r.solved?`<button type="button" data-next-stage class="primary wide">${w().next} →</button>`:r.hearts===0?`<button type="button" data-retry-stage class="primary wide">${w().retry}</button>`:`<div class="answer-platforms">${q.options.map((o,i)=>`<div class="answer-label" data-answer-label="${i}"><span>${i+1}</span>${esc(o)}</div>`).join('')}</div><small class="muted">${w().guideNote}</small><div class="arcade-tools">${active==='memory'?`<button type="button" data-memory-replay ${watching?'disabled':''}>↻ ${w().replay}</button>`:''}<button type="button" data-arcade-hint ${r.hinted||!state.expansion.inventory.hint||watching?'disabled':''}>💡 ${w().hint} (${state.expansion.inventory.hint})</button></div>`}<p class="arcade-help">${w().modes[active][1]}</p><button type="button" data-exit-game class="wide">⌂ ${w().back}</button><small class="muted">${w().savedRun}</small>`;
  worldTask.hidden=false;worldTask.textContent=`${w().stage} ${r.stage} · ${active==='memory'?(watching?w().watch:w().repeat):q.question}`;$('chapter').textContent=w().modes[active][0];
  scene.arcadeLocked=r.solved||r.hearts<=0||watching;panel.dataset.stage=String(r.stage);panel.dataset.solved=String(r.solved);
 }
 function watch(){watchStart=scene.clock;watchIndex=-1;scene.arcadeLocked=true;scene.respawn();hud();}
 function loadStage(){const r=state.expansion.runs[active],q=questionFor(r);watchStart=null;scene.enterGame(active,q,r.stage,choose,fall,r);feedback='';if(active==='memory'&&!r.solved&&r.hearts>0)watch();else hud();}
 function enter(mode){disposePreview();if($('town-dialog').open)close();state.started=true;startRun(state,mode);active=mode;persist();refresh();document.body.classList.add('playing-island');document.querySelector('.quest-panel').hidden=true;panel.hidden=false;loadStage();$('town-canvas').scrollIntoView({block:'center',behavior:'instant'});$('town-canvas').focus({preventScroll:true});}
 function leave(){if(!active)return;watchStart=null;active=null;worldTask.hidden=true;scene.arcadeLocked=false;scene.exitGame();panel.hidden=true;document.querySelector('.quest-panel').hidden=false;document.body.classList.remove('playing-island');persist();refresh();renderCards();$('town-canvas').focus({preventScroll:true});}
 function choose(index){if(!active||watchStart!==null)return;const result=answerRun(state,active,index);if(result.ignored)return;persist();refresh();if(result.partial){scene.respawn();feedback='✓';}else if(result.ok){feedback=`${w().correct} +${result.coins} ${w().coins} · ${result.explanation}`;scene.stop();}else{feedback=`${result.shield?'🛡 ':''}${result.over?w().over:w().wrong} ${result.explanation}`;scene.respawn();}hud();renderCards();}
 function fall(){if(!active)return;const q=questionFor(state.expansion.runs[active]);const result=answerRun(state,active,(q.answer+1)%q.options.length);if(result.ignored)return;feedback=result.over?w().over:w().fall;persist();refresh();hud();}
 function showShop(){disposePreview();scene.stop();const e=state.expansion;shell(w().shop,`<p>${w().bag} · <b>✦ ${state.coins}</b></p><div class="item-grid">${ITEMS.map(i=>{const owned=e.gear.includes(i.id);return `<article class="shop-item"><span class="item-icon">${i.icon}</span><h3>${name(i)}</h3><p>${w()[i.id==='hint'?'hintDescription':i.id]}</p><small>${i.kind==='use'?`${w().bag}: ${e.inventory[i.id]}`:owned?w().owned:`${i.price} ✦`}</small><button type="button" data-buy-item="${i.id}" ${owned||state.coins<i.price||i.kind==='use'&&e.inventory[i.id]>=99?'disabled':''}>${owned?'✓ '+w().owned:`${w().buy} · ${i.price} ✦`}</button>${i.kind==='style'&&owned?`<button type="button" data-equip-item="${i.id}" aria-pressed="${e.accessory===i.id}">${e.accessory===i.id?w().equipped:w().equip}</button>`:''}</article>`;}).join('')}</div>${e.accessory?`<button type="button" data-equip-item="">${w().remove}</button>`:''}`,'expansion-shop');}
 function decorateSettings(){disposePreview();const wrap=document.createElement('section');wrap.className='avatar-studio';wrap.innerHTML=`<div class="avatar-preview-wrap"><canvas id="avatar-preview" aria-label="${w().characters}"></canvas><small>${w().drag}</small></div><div><h3>${w().characters}</h3><p>${w().skins}</p><div class="avatar-choices">${AVATARS.map(a=>`<button type="button" data-character-id="${a.id}" aria-pressed="${state.expansion.character===a.id}" style="--avatar-color:#${a.color.toString(16).padStart(6,'0')}"><span class="avatar-head"></span><b>${name(a)}</b><small>${state.expansion.character===a.id?'✓ '+w().selected:'3D'}</small></button>`).join('')}</div></div>`;document.querySelector('#dialog-body .dialog-content').prepend(wrap);try{previewDispose=previewAvatar($('avatar-preview'),state.expansion.character,state.expansion.accessory,state.avatar>0?['#ec825f','#509fd4','#9c82cf','#62a67a'][state.avatar]:undefined,state.expansion.gear);}catch{$('avatar-preview').replaceWith(document.createTextNode(w().webgl));}}
 function rerender(){renderCards();if(active)hud();}
 root.addEventListener('click',e=>{const mode=e.target.closest('[data-game]')?.dataset.game;if(mode)enter(mode);if(e.target.closest('[data-arcade-shop]'))showShop();});
 panel.addEventListener('click',e=>{const el=e.target.closest('button');if(!el||el.disabled)return;if(el.hasAttribute('data-exit-game'))leave();else if(el.hasAttribute('data-next-stage')){if(nextStage(state,active)){persist();loadStage();}}else if(el.hasAttribute('data-retry-stage')){retryStage(state,active);persist();loadStage();}else if(el.hasAttribute('data-memory-replay')){state.expansion.runs[active].memoryIndex=0;persist();watch();}else if(el.hasAttribute('data-arcade-hint')){if(useHint(state,active)){persist();hud();}}});
 $('town-dialog').addEventListener('click',e=>{const el=e.target.closest('button');if(!el||el.disabled)return;if(el.dataset.characterId){state.expansion.character=el.dataset.characterId;persist();scene.syncAvatar();disposePreview();document.querySelector('.avatar-studio')?.remove();decorateSettings();}else if(el.dataset.buyItem){buyItem(state,el.dataset.buyItem);persist();refresh();showShop();}else if(el.hasAttribute('data-equip-item')){const id=el.dataset.equipItem;if(!id||state.expansion.gear.includes(id))state.expansion.accessory=id||null;persist();scene.syncAvatar();showShop();}});
 $('town-dialog').addEventListener('close',disposePreview);$('locale').addEventListener('change',()=>{if(!active)scene.buildTown();rerender();});scene.onViewChange=()=>{persist();renderCards();};scene.onArcade=()=>{if(active)return;root.scrollIntoView({behavior:'smooth',block:'start'});root.querySelector('[data-game]')?.focus({preventScroll:true});scene.stop();};
 function frame(){if(active&&watchStart!==null){const r=state.expansion.runs[active],q=questionFor(r),elapsed=scene.clock-watchStart,index=Math.floor(elapsed/1.15);if(index>=q.sequence.length){watchStart=null;scene.highlight(-1);hud();}else {const showing=elapsed%1.15<.85,key=index*2+(showing?0:1);if(key!==watchIndex){watchIndex=key;scene.highlight(showing?q.sequence[index]:-1);const cue=$('memory-cue');if(cue){cue.textContent=showing?`${index+1} / ${q.sequence.length} · ${q.options[q.sequence[index]]}`:'· · ·';cue.style.background=showing?'#'+q.colors[q.sequence[index]].toString(16):'#edf2e7';}}}}requestAnimationFrame(frame);}frame();renderCards();return {decorateSettings,disposePreview,rerender,leave,isPlaying:()=>!!active};
}
